import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {chromium,webkit} from 'playwright';

const workerModule=()=>import('../apps/admin-worker/src/index.ts?responsive='+Date.now());
const env={ADMIN_EMAILS:'admin@example.com'};
const overview={generatedAt:Date.now(),summary:{users:1,entries:15,attachments:2,attachmentBytes:2048,activeSessions:2,pendingDeletions:0,inflightUploads:0,backupLocks:0},resources:{d1:{bytes:356352,limitBytes:500000000},r2:{objects:2,bytes:2048,limitBytes:8*1024**3,classA:3,classB:4,classALimitMonthly:800000,classBLimitMonthly:8000000},workers:{requestsMonth:20,errorsMonth:0,requestLimitDaily:100000}},users:[{username:'自动化测试二号',createdAt:1776032802000,entries:15,attachments:2,attachmentBytes:2048,activeSessions:2,lastSeenAt:1776055826000,lastAuthMethod:'password',passkeys:0}],health:{dbMs:3,r2Ms:4,r2:true},registration:{enabled:true,inviteCodeSet:true},trend:[],healthEvents:[],audit:[],runtime:{version:'responsive-test',appVersion:'2.2.0'}};

async function serve(){const {default:worker}=await workerModule();const server=createServer(async(req,res)=>{if(req.url==='/api/overview'){res.setHeader('content-type','application/json');res.end(JSON.stringify(overview));return}const response=await worker.fetch(new Request(`http://127.0.0.1${req.url}`,{headers:{'cf-access-authenticated-user-email':'admin@example.com'}}),env);res.statusCode=response.status;response.headers.forEach((v,k)=>res.setHeader(k,v));res.end(Buffer.from(await response.arrayBuffer()))});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return{server,url:`http://127.0.0.1:${server.address().port}`}}

for(const engine of [chromium,webkit])test(`Admin ${engine.name()} 在桌面、中等窗口和手机采用完整响应式编排`,{timeout:180000},async()=>{const {server,url}=await serve(),browser=await engine.launch({headless:true}),page=await browser.newPage();try{for(const viewport of (engine===webkit?[{width:900,height:900},{width:390,height:844}]:[{width:1280,height:900},{width:900,height:900},{width:390,height:844},{width:320,height:700}])){await page.setViewportSize(viewport);await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await page.getByText('自动化测试二号',{exact:true}).waitFor({timeout:60000});const g=await page.evaluate(()=>{const user=document.querySelector('.user'),actions=user.querySelector('.row-actions'),userSection=[...document.querySelectorAll('section')].find(x=>x.querySelector('h2')?.textContent==='用户'),controls=userSection.querySelector('.controls'),maintenance=[...document.querySelectorAll('section')].find(x=>x.querySelector('h2')?.textContent==='运维任务'),maintenanceHead=maintenance.querySelector('.section-head'),maintenanceGrid=maintenance.querySelector('.detail-grid'),usersList=userSection.querySelector('.users'),userHeaderBottom=Math.max(...[...userSection.querySelector('.section-head').children].map(x=>x.getBoundingClientRect().bottom)),actionRects=[...actions.querySelectorAll('button')].map(x=>x.getBoundingClientRect()),headerBottom=Math.max(...[...maintenanceHead.children].map(x=>x.getBoundingClientRect().bottom));return{vw:innerWidth,overflow:document.documentElement.scrollWidth-innerWidth,userRight:user.getBoundingClientRect().right,sectionRight:userSection.getBoundingClientRect().right,controlsRight:controls.getBoundingClientRect().right,controlsWidth:controls.getBoundingClientRect().width,actionsTop:actions.getBoundingClientRect().top,userTop:user.getBoundingClientRect().top,actionSameRow:Math.max(...actionRects.map(x=>x.top))-Math.min(...actionRects.map(x=>x.top))<2,userListGap:usersList.getBoundingClientRect().top-userHeaderBottom,maintenanceGap:maintenanceGrid.getBoundingClientRect().top-headerBottom,maintenanceColumns:getComputedStyle(maintenanceGrid).gridTemplateColumns.split(' ').length}});assert.ok(g.overflow<=0,JSON.stringify(g));assert.ok(g.userRight<=g.sectionRight+1,JSON.stringify(g));assert.ok(g.controlsRight<=g.sectionRight+1,JSON.stringify(g));assert.ok(g.userListGap>=16,JSON.stringify(g));assert.ok(g.maintenanceGap>=14,JSON.stringify(g));assert.equal(g.maintenanceColumns,3,JSON.stringify(g));if(viewport.width>=1100){assert.ok(g.actionsTop<g.userTop+70,JSON.stringify(g));assert.equal(g.actionSameRow,true,JSON.stringify(g))}else{assert.ok(g.actionsTop>g.userTop,JSON.stringify(g))}if(viewport.width<=520)assert.ok(g.controlsWidth>=viewport.width-64,JSON.stringify(g))} }finally{await browser.close();await new Promise(resolve=>server.close(resolve))}});
