import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {chromium,webkit} from 'playwright';
import {generateKeyPairSync,sign} from 'node:crypto';

const workerModule=()=>import('../apps/admin-worker/src/index.ts?responsive-sidebar='+Date.now());
const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048}),jwk=publicKey.export({format:'jwk'});Object.assign(jwk,{kid:'responsive-key',use:'sig',alg:'RS256'});const b=x=>Buffer.from(JSON.stringify(x)).toString('base64url'),h=b({alg:'RS256',kid:'responsive-key'}),p=b({iss:'https://test.cloudflareaccess.com',aud:'responsive-aud',email:'admin@example.com',exp:4102444800}),jwt=h+'.'+p+'.'+sign('RSA-SHA256',Buffer.from(h+'.'+p),privateKey).toString('base64url'),accessHeaders={'cf-access-authenticated-user-email':'admin@example.com','cf-access-jwt-assertion':jwt};
const env={ADMIN_EMAILS:'admin@example.com',ACCESS_ISSUER:'https://test.cloudflareaccess.com',ACCESS_AUD:'responsive-aud',ACCESS_JWKS:JSON.stringify({keys:[jwk]})};
const overview={generatedAt:Date.now(),summary:{users:1,entries:15,attachments:2,attachmentBytes:2048,activeSessions:2,pendingDeletions:0,inflightUploads:0,backupLocks:0},resources:{d1:{bytes:356352,limitBytes:500000000},r2:{objects:2,bytes:2048,limitBytes:8*1024**3,classA:3,classB:4,classALimitMonthly:800000,classBLimitMonthly:8000000},workers:{requestsMonth:20,errorsMonth:0,requestLimitDaily:100000}},users:[{username:'自动化测试二号',createdAt:1776032802000,entries:15,attachments:2,attachmentBytes:2048,activeSessions:2,lastSeenAt:1776055826000,lastAuthMethod:'password',passkeys:0,riskFlags:{},quota:{entryLimit:1000,attachmentCountLimit:50,attachmentBytesLimit:524288000,source:'default'}}],health:{dbMs:3,r2Ms:4,r2:true},registration:{enabled:true,inviteCodeSet:true,inviteCodes:[]},trend:[],healthEvents:[],securityEvents:[],quotaAlerts:[],quotaHistory:{},audit:[],riskSummary:{attention:0,quotaNearLimit:0,inactive:0,noPasskey:1,manySessions:0},securitySummary:{failed24h:0,maintenanceFailures:0},maintenance:{},runtime:{version:'responsive-test',appVersion:'2.2.0'}};

async function serve(){const {default:worker}=await workerModule();const server=createServer(async(req,res)=>{if(req.url?.startsWith('/api/overview')){res.setHeader('content-type','application/json');res.end(JSON.stringify(overview));return}if(req.url?.startsWith('/api/users')){res.setHeader('content-type','application/json');res.end(JSON.stringify({users:overview.users,pagination:{page:1,pageSize:20,total:overview.users.length,pages:1}}));return}if(req.url?.startsWith('/api/audit')){res.setHeader('content-type','application/json');res.end(JSON.stringify({audit:overview.audit,pagination:{page:1,pageSize:20,total:overview.audit.length,pages:1}}));return}const response=await worker.fetch(new Request(`http://127.0.0.1${req.url}`,{headers:accessHeaders}),env);res.statusCode=response.status;response.headers.forEach((v,k)=>res.setHeader(k,v));res.end(Buffer.from(await response.arrayBuffer()))});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return{server,url:`http://127.0.0.1:${server.address().port}`}}

for(const engine of [chromium,webkit])test(`Admin ${engine.name()} 侧栏在桌面、平板和手机完整响应`,{timeout:180000},async()=>{const {server,url}=await serve(),browser=await engine.launch({headless:true}),page=await browser.newPage();try{for(const viewport of (engine===webkit?[{width:900,height:900},{width:390,height:844}]:[{width:1280,height:900},{width:900,height:900},{width:390,height:844},{width:320,height:700}])){await page.setViewportSize(viewport);await page.goto(url+'?page=overview',{waitUntil:'domcontentloaded',timeout:60000});await page.locator('[data-page="overview"] > .page-heading > h2').waitFor({timeout:60000});const headingFocus=await page.locator('[data-page="overview"] > .page-heading > h2').evaluate(h=>{h.setAttribute('tabindex','-1');h.focus();const s=getComputedStyle(h);return{active:document.activeElement===h,outline:s.outlineStyle,shadow:s.boxShadow}});assert.equal(headingFocus.active,true);assert.equal(headingFocus.outline,'none',`${engine.name()} ${viewport.width}px 页面标题不应显示焦点蓝框`);assert.equal(headingFocus.shadow,'none',`${engine.name()} ${viewport.width}px 页面标题不应显示焦点阴影`);const mobile=viewport.width<=760;if(mobile){await page.getByRole('button',{name:'打开管理菜单'}).click();await page.getByRole('button',{name:'用户管理',exact:true}).click()}else await page.getByRole('button',{name:'用户管理',exact:true}).click();await page.getByText('自动化测试二号',{exact:true}).waitFor();const g=await page.evaluate(()=>{const visible=[...document.querySelectorAll('[data-page]')].filter(x=>!x.hidden),sidebar=document.querySelector('[data-sidebar]'),toggle=document.querySelector('[data-nav-toggle]'),user=document.querySelector('.user');return{vw:innerWidth,overflow:document.documentElement.scrollWidth-innerWidth,visiblePages:visible.length,page:visible[0]?.dataset.page,sidebarPosition:getComputedStyle(sidebar).position,sidebarTransform:getComputedStyle(sidebar).transform,toggleDisplay:getComputedStyle(toggle).display,userRight:user.getBoundingClientRect().right}});assert.ok(g.overflow<=1,`${engine.name()} ${viewport.width}px 横向溢出 ${g.overflow}px`);assert.equal(g.visiblePages,1);assert.equal(g.page,'users');assert.ok(g.userRight<=g.vw+1);if(mobile){assert.equal(g.sidebarPosition,'fixed');assert.notEqual(g.toggleDisplay,'none');assert.notEqual(g.sidebarTransform,'none')}else{assert.equal(g.sidebarPosition,'sticky');assert.equal(g.toggleDisplay,'none')}}}finally{await browser.close();await new Promise(resolve=>server.close(resolve))}});

for(const engine of [chromium,webkit])test(`Admin ${engine.name()} 注册控制按钮在手机端等宽`,{timeout:180000},async()=>{const {server,url}=await serve(),browser=await engine.launch({headless:true}),page=await browser.newPage({viewport:{width:390,height:844}});try{await page.goto(url+'?page=registration',{waitUntil:'domcontentloaded',timeout:60000});const toggle=page.locator('[data-registration-toggle]'),manage=page.locator('[data-invite-manage]');await toggle.waitFor();const geometry=await Promise.all([toggle,manage].map(x=>x.evaluate(el=>{const r=el.getBoundingClientRect();return{width:r.width,height:r.height}})));assert.ok(Math.abs(geometry[0].width-geometry[1].width)<=1,`${engine.name()} 两个注册控制按钮应等宽`);assert.ok(Math.abs(geometry[0].height-geometry[1].height)<=1,`${engine.name()} 两个注册控制按钮应等高`);assert.ok(geometry[0].height>=44&&geometry[1].height>=44);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)<=1)}finally{await browser.close();await new Promise(resolve=>server.close(resolve))}});
