import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';

const mod=()=>import('../apps/admin-worker/src/index.ts?test='+Date.now());

const rows={
 users:[{id:'u1',username:'admin',created_at:1000,password_hash:'SECRET_HASH',password_salt:'SECRET_SALT',wrapped_key:'SECRET_KEY',password_iterations:100000},{id:'u2',username:'agent',created_at:2000,password_hash:'X',password_salt:'Y',wrapped_key:'Z',password_iterations:100000}],
 entries:[{user_id:'u1'},{user_id:'u1'}],attachments:[{user_id:'u1',ciphertext_size:1200,object_key:'SECRET_OBJECT'}],sessions:[{user_id:'u1',expires_at:9999999999999,auth_method:'password',last_seen_at:4000},{user_id:'u2',expires_at:1,auth_method:'passkey',last_seen_at:3000}],passkeys:[{user_id:'u2'}]
};
class DB{prepare(sql){return{all:async()=>({results:sql.includes('FROM users u')?[{username:'admin',created_at:1000,entry_count:2,attachment_count:1,attachment_bytes:1200,active_sessions:1,last_seen_at:4000,last_auth_method:'password',passkey_count:0,password_iterations:100000},{username:'agent',created_at:2000,entry_count:0,attachment_count:0,attachment_bytes:0,active_sessions:0,last_seen_at:3000,last_auth_method:'passkey',passkey_count:1,password_iterations:100000}]:[]}),run:async()=>({results:[{users:2,entries:2,attachments:1,attachment_bytes:1200,active_sessions:1,pending_deletions:0,inflight_uploads:0,backup_locks:0,class_a:3,class_b:4}],meta:{size_after:356352}})}}}
const env={DB:new DB(),ATTACHMENTS:{list:async()=>({objects:[{size:1200}],truncated:false})},ADMIN_EMAIL:'admin@example.com',CF_VERSION_METADATA:{id:'version-1'}};
const req=(path='/',headers={})=>new Request('https://admin.example.com'+path,{headers});

test('未经过Cloudflare Access的请求一律拒绝且不泄露页面',async()=>{const {default:worker}=await mod();const r=await worker.fetch(req(),env);assert.equal(r.status,401);assert.match(r.headers.get('cache-control'),/no-store/)});
test('Access邮箱必须与唯一管理员邮箱完全匹配',async()=>{const {default:worker}=await mod();const r=await worker.fetch(req('/api/overview',{'cf-access-authenticated-user-email':'other@example.com'}),env);assert.equal(r.status,403)});
test('只读概览仅返回用户元数据和资源统计且不包含任何敏感字段',async()=>{const {default:worker}=await mod();const r=await worker.fetch(req('/api/overview',{'cf-access-authenticated-user-email':'admin@example.com'}),env);assert.equal(r.status,200);const text=await r.text();const data=JSON.parse(text);assert.equal(data.users.length,2);assert.equal(data.resources.r2.objects,1);assert.equal(data.resources.d1.bytes,356352);assert.equal(data.resources.d1.limitBytes,500000000);assert.equal(data.resources.r2.limitBytes,10000000000);for(const secret of ['password_hash','password_salt','wrapped_key','object_key','SECRET_HASH','SECRET_KEY'])assert.equal(text.includes(secret),false);assert.match(r.headers.get('content-security-policy'),/default-src 'none'/);assert.match(r.headers.get('cache-control'),/no-store/)});
test('管理Worker仍拒绝概览写请求',async()=>{const {default:worker}=await mod();const r=await worker.fetch(new Request('https://admin.example.com/api/overview',{method:'POST',headers:{'cf-access-authenticated-user-email':'admin@example.com'}}),env);assert.equal(r.status,405)});
test('删除用户要求同源及精确输入用户名，并删除账户全部D1数据与R2对象',async()=>{const {default:worker}=await mod();const events=[];class DeleteDB{prepare(sql){const stmt={sql,args:[],bind(...args){this.args=args;return this},first:async()=>sql.startsWith('SELECT id FROM users')?{id:'u1'}:null,all:async()=>sql.startsWith('SELECT object_key')?{results:[{object_key:'vault/u1/a',ciphertext_size:1200}]}:{results:[]},run:async()=>({results:[],meta:{changes:1}})};events.push(stmt);return stmt}async batch(stmts){events.push({batch:stmts});return stmts.map(()=>({meta:{changes:1}}))}}const deleted=[];const deleteEnv={...env,DB:new DeleteDB(),ATTACHMENTS:{...env.ATTACHMENTS,delete:async key=>deleted.push(key)}};const headers={'cf-access-authenticated-user-email':'admin@example.com',origin:'https://admin.example.com','x-confirm-username':'admin'};let r=await worker.fetch(new Request('https://admin.example.com/api/users/admin',{method:'DELETE',headers:{...headers,'x-confirm-username':'wrong'}}),deleteEnv);assert.equal(r.status,400);assert.equal(deleted.length,0);r=await worker.fetch(new Request('https://admin.example.com/api/users/admin',{method:'DELETE',headers}),deleteEnv);assert.equal(r.status,200);const data=await r.json();assert.equal(data.deleted,true);assert.deepEqual(deleted,['vault/u1/a']);const sql=events.flatMap(x=>x.batch||[x]).map(x=>x.sql||'').join('\n');assert.match(sql,/INSERT INTO pending_r2_deletions/);assert.match(sql,/DELETE FROM users/);assert.match(sql,/DELETE FROM pending_r2_deletions/);assert.match(sql,/UPDATE r2_storage_usage/)});
test('容量指标紧凑展示已用总量剩余且不显示NaN',async()=>{const {default:worker}=await mod();let rendered='';const root={set innerHTML(v){rendered=v},get innerHTML(){return rendered},querySelectorAll(){return[]}};const fetch=async()=>({ok:true,json:async()=>({summary:{users:2,entries:256,attachments:5,attachmentBytes:1406248,activeSessions:1,pendingDeletions:0,inflightUploads:0,backupLocks:0},resources:{r2:{objects:5,bytes:1406248,limitBytes:10000000000,classA:43,classB:116,classALimitMonthly:1000000,classBLimitMonthly:10000000},d1:{bytes:356352,limitBytes:500000000},workers:{requestsMonth:15354,errorsMonth:4,requestLimitDaily:100000}},users:[{username:'<admin&"',createdAt:1000,entries:2,attachments:1,activeSessions:1,lastAuthMethod:'password',lastSeenAt:4000}],runtime:{version:'v'}})});const r=await worker.fetch(req('/app.js',{'cf-access-authenticated-user-email':'admin@example.com'}),env);vm.runInNewContext(await r.text(),{Intl,Date,fetch,document:{querySelector:()=>root}});await new Promise(resolve=>setTimeout(resolve,0));assert.doesNotMatch(rendered,/NaN/);assert.match(rendered,/D1 存储/);assert.match(rendered,/356 KB \/ 500 MB/);assert.match(rendered,/R2 存储/);assert.match(rendered,/1\.41 MB \/ 10 GB/);assert.match(rendered,/剩余/);assert.match(rendered,/系统状态/);assert.match(rendered,/运行正常/);assert.match(rendered,/D1 正常/);assert.match(rendered,/R2 正常/);assert.match(rendered,/删除用户/);assert.match(rendered,/data-delete-index/);assert.doesNotMatch(rendered,/<admin&"/);assert.ok((rendered.match(/class="card metric"/g)||[]).length<=4)});
