import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import { generateKeyPairSync, sign } from 'node:crypto';
import { readFile } from 'node:fs/promises';

const mod=()=>import('../apps/admin-worker/src/index.ts?test='+Date.now());

const rows={
 users:[{id:'u1',username:'admin',created_at:1000,password_hash:'SECRET_HASH',password_salt:'SECRET_SALT',wrapped_key:'SECRET_KEY',password_iterations:100000},{id:'u2',username:'agent',created_at:2000,password_hash:'X',password_salt:'Y',wrapped_key:'Z',password_iterations:100000}],
 entries:[{user_id:'u1'},{user_id:'u1'}],attachments:[{user_id:'u1',ciphertext_size:1200,object_key:'SECRET_OBJECT'}],sessions:[{user_id:'u1',expires_at:9999999999999,auth_method:'password',last_seen_at:4000},{user_id:'u2',expires_at:1,auth_method:'passkey',last_seen_at:3000}],passkeys:[{user_id:'u2'}]
};
class DB{prepare(sql){const stmt={bind(){return stmt},all:async()=>({results:sql.includes('FROM users u')?[{username:'admin',created_at:1000,entry_count:2,attachment_count:1,attachment_bytes:1200,active_sessions:1,last_seen_at:4000,last_auth_method:'password',passkey_count:0,password_iterations:100000},{username:'agent',created_at:2000,entry_count:0,attachment_count:0,attachment_bytes:0,active_sessions:0,last_seen_at:3000,last_auth_method:'passkey',passkey_count:1,password_iterations:100000}]:[]}),run:async()=>({results:[{users:2,entries:2,attachments:1,attachment_bytes:1200,active_sessions:1,pending_deletions:0,inflight_uploads:0,backup_locks:0,class_a:3,class_b:4}],meta:{size_after:356352}})};return stmt}}
const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048}),jwk=publicKey.export({format:'jwk'});Object.assign(jwk,{kid:'test-key',use:'sig',alg:'RS256'});const b=x=>Buffer.from(JSON.stringify(x)).toString('base64url'),token=(email,claims={},header={})=>{const h=b({alg:'RS256',kid:'test-key',typ:'JWT',...header}),p=b({iss:'https://test.cloudflareaccess.com',aud:'test-audience',email:email.trim().toLowerCase(),exp:4102444800,nbf:0,...claims}),input=h+'.'+p;return input+'.'+sign('RSA-SHA256',Buffer.from(input),privateKey).toString('base64url')},access=(email,claims={},header={})=>({'cf-access-authenticated-user-email':email,'cf-access-jwt-assertion':token(email,claims,header)});
const env={DB:new DB(),ATTACHMENTS:{list:async()=>({objects:[{size:1200}],truncated:false})},ADMIN_EMAILS:'admin@example.com, second@example.com',MAIN_SITE_URL:'https://pass.example.com',ACCESS_ISSUER:'https://test.cloudflareaccess.com',ACCESS_AUD:'test-audience',ACCESS_JWKS:JSON.stringify({keys:[jwk]}),INVITE_CODE_PEPPER:'test-only-pepper',CF_VERSION_METADATA:{id:'version-1'}};
const req=(path='/',headers={})=>new Request('https://admin.example.com'+path,{headers});

test('未经过Cloudflare Access的请求一律拒绝且不泄露页面',async()=>{const {default:worker}=await mod();const r=await worker.fetch(req(),env);assert.equal(r.status,401);assert.match(r.headers.get('cache-control'),/no-store/)});
test('伪造Access邮箱头但没有有效JWT时必须拒绝',async()=>{const {default:worker}=await mod();const r=await worker.fetch(req('/api/overview',{'cf-access-authenticated-user-email':'admin@example.com'}),env);assert.equal(r.status,401);assert.equal((await r.json()).error,'access_required')});
test('Access JWT 对畸形 NumericDate、错误签名/issuer/audience/算法与邮箱不一致全部 fail-closed',async()=>{const {default:worker}=await mod();for(const headers of [access('admin@example.com',{exp:'4102444800'}),access('admin@example.com',{nbf:'invalid'}),access('admin@example.com',{exp:1}),access('admin@example.com',{iss:'https://evil.example'}),access('admin@example.com',{aud:'wrong'}),access('admin@example.com',{}, {alg:'HS256'}),{'cf-access-authenticated-user-email':'other@example.com','cf-access-jwt-assertion':token('admin@example.com')},{'cf-access-authenticated-user-email':'admin@example.com','cf-access-jwt-assertion':token('admin@example.com').slice(0,-2)+'aa'}])assert.equal((await worker.fetch(req('/api/overview',headers),env)).status,401)});
test('Access JWT 对畸形 JWKS 稳定返回401而不是抛出500',async()=>{const {default:worker}=await mod();for(const ACCESS_JWKS of ['{}','{"keys":{}}','{"keys":[null]}','{"keys":[42]}','{"keys":[{"kid":"test-key","kty":"RSA","alg":"HS256"}]}','{"keys":[{"kid":"test-key","kty":"RSA","alg":"RS256","use":"sig","key_ops":"verify"}]}','{"keys":[{"kid":"test-key","kty":"RSA","alg":"RS256","use":"sig","key_ops":["verify","encrypt"]}]}'])assert.equal((await worker.fetch(req('/api/overview',access('admin@example.com')),{...env,ACCESS_JWKS})).status,401)});
test('Access邮箱必须与管理员白名单精确匹配并允许多个邮箱',async()=>{const {default:worker}=await mod();let r=await worker.fetch(req('/api/overview',access('other@example.com')),env);assert.equal(r.status,403);r=await worker.fetch(req('/api/overview',access(' SECOND@example.com ')),env);assert.equal(r.status,200)});
test('只读概览仅返回用户元数据和资源统计且不包含任何敏感字段',async()=>{const {default:worker}=await mod();const r=await worker.fetch(req('/api/overview',access('admin@example.com')),env);assert.equal(r.status,200);const text=await r.text();const data=JSON.parse(text);assert.equal(data.users.length,2);assert.equal(data.resources.r2.objects,1);assert.equal(data.resources.d1.bytes,356352);assert.equal(data.resources.d1.limitBytes,500000000);assert.equal(data.resources.r2.limitBytes,8*1024**3);assert.equal(data.resources.r2.classALimitMonthly,800000);assert.equal(data.resources.r2.classBLimitMonthly,8000000);for(const secret of ['password_hash','password_salt','wrapped_key','object_key','SECRET_HASH','SECRET_KEY'])assert.equal(text.includes(secret),false);assert.match(r.headers.get('content-security-policy'),/default-src 'none'/);assert.match(r.headers.get('cache-control'),/no-store/)});
test('Admin 概览 GET 不写 D1 且Cloudflare可运行的10万次密码策略标记为当前策略',async()=>{const {default:worker}=await mod();const writes=[];class ReadOnlyOverviewDB extends DB{prepare(sql){const stmt=super.prepare(sql);if(sql.includes('FROM users u'))stmt.all=async()=>({results:[{username:'current',created_at:1000,entry_count:0,attachment_count:0,attachment_bytes:0,active_sessions:0,last_seen_at:0,last_auth_method:null,passkey_count:0,password_iterations:100000},{username:'invalid',created_at:1000,entry_count:0,attachment_count:0,attachment_bytes:0,active_sessions:0,last_seen_at:0,last_auth_method:null,passkey_count:0,password_iterations:0}]});const originalRun=stmt.run;stmt.run=async()=>{if(/^\s*(?:INSERT|UPDATE|DELETE|REPLACE)/i.test(sql))writes.push(sql);return originalRun()};return stmt}}const r=await worker.fetch(req('/api/overview',access('admin@example.com')),{...env,DB:new ReadOnlyOverviewDB()});assert.equal(r.status,200);const data=await r.json();assert.equal(writes.length,0);assert.equal(data.users.find(x=>x.username==='current').passwordPolicy,'当前策略');assert.equal(data.users.find(x=>x.username==='invalid').passwordPolicy,'需检查')});

test('管理Worker仍拒绝概览写请求且HEAD不执行概览查询',async()=>{const {default:worker}=await mod();const headers=access('admin@example.com');const r=await worker.fetch(new Request('https://admin.example.com/api/overview',{method:'POST',headers}),env);assert.equal(r.status,405);let prepared=0;const headEnv={...env,DB:{...env.DB,prepare(){prepared++;throw new Error('HEAD must not query D1')}}};const head=await worker.fetch(new Request('https://admin.example.com/api/overview',{method:'HEAD',headers}),headEnv);assert.equal(head.status,200);assert.equal(await head.text(),'');assert.equal(prepared,0)});
test('删除用户要求同源及精确输入用户名，并删除账户全部D1数据与R2对象',async()=>{const {default:worker}=await mod();const events=[];class DeleteDB{prepare(sql){const stmt={sql,args:[],bind(...args){this.args=args;return this},first:async()=>sql.startsWith('SELECT id FROM users')?{id:'u1'}:null,all:async()=>sql.startsWith('SELECT object_key')?{results:[{object_key:'vault/u1/a',ciphertext_size:1200}]}:{results:[]},run:async()=>({results:[],meta:{changes:1}})};events.push(stmt);return stmt}async batch(stmts){events.push({batch:stmts});return stmts.map(()=>({meta:{changes:1}}))}}const deleted=[];const deleteEnv={...env,DB:new DeleteDB(),ATTACHMENTS:{...env.ATTACHMENTS,delete:async key=>deleted.push(key)}};const headers={...access('admin@example.com'),origin:'https://admin.example.com','x-confirm-username':'admin'};let r=await worker.fetch(new Request('https://admin.example.com/api/users/admin',{method:'DELETE',headers:{...headers,'x-confirm-username':'wrong'}}),deleteEnv);assert.equal(r.status,400);assert.equal(deleted.length,0);r=await worker.fetch(new Request('https://admin.example.com/api/users/admin',{method:'DELETE',headers}),deleteEnv);assert.equal(r.status,200);const data=await r.json();assert.equal(data.r2Queued,true);assert.deepEqual(deleted,[]);const sql=events.flatMap(x=>x.batch||[x]).map(x=>x.sql||'').join('\n');assert.match(sql,/INSERT INTO pending_r2_deletions[\s\S]*SELECT/);assert.match(sql,/DELETE FROM users/);assert.match(sql,/attachment_versions WHERE user_id/);assert.match(sql,/secure_share_objects/);assert.match(sql,/WHERE changes\(\)=1/);const expectedPrefix=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode('u1'))).toString('base64url')+'/%';assert.ok(events.flatMap(x=>x.batch||[x]).flatMap(x=>x.args||[]).filter(x=>typeof x==='string').includes(expectedPrefix))});
test('注册控制和注册码更新使用带版本前缀的服务端 pepper HMAC 且不回显明文',async()=>{const {default:worker}=await mod();const sql=[];class ConfigDB{prepare(s){const x={args:[],bind(...a){this.args=a;return this},first:async()=>null,all:async()=>({results:[]}),run:async()=>{sql.push([s,x.args]);return{meta:{changes:1}}}};return x}async batch(stmts){return Promise.all(stmts.map(x=>x.run()))}}const e={...env,DB:new ConfigDB()},h={...access('admin@example.com'),origin:'https://admin.example.com','content-type':'application/json'};const code='x';let r=await worker.fetch(new Request('https://admin.example.com/api/registration',{method:'PUT',headers:h,body:JSON.stringify({enabled:false,inviteCode:code})}),e);assert.equal(r.status,200);const boundValues=sql.flatMap(x=>x[1]),hashArg=boundValues.find(x=>typeof x==='string'&&x.startsWith('hmac-sha256:v1:'));assert.equal(boundValues.includes(code),false);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(e.INVITE_CODE_PEPPER),{name:'HMAC',hash:'SHA-256'},false,['sign']),expected=Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(code))).toString('base64url');assert.equal(hashArg,'hmac-sha256:v1:'+expected);const text=JSON.stringify(sql);assert.match(text,/registration_enabled/);assert.match(text,/invite_code_hash/);r=await worker.fetch(new Request('https://admin.example.com/api/registration',{method:'PUT',headers:{...h,origin:'https://evil.example'},body:'{}'}),e);assert.equal(r.status,403)});

test('设置邀请码时 pepper 缺失明确返回503且不执行任何D1写入',async()=>{const {default:worker}=await mod();let batches=0;const e={...env,INVITE_CODE_PEPPER:undefined,DB:{prepare(){return{bind(){return this}}},async batch(){batches++;return[]}}},headers={...access('admin@example.com'),origin:'https://admin.example.com','content-type':'application/json'},r=await worker.fetch(new Request('https://admin.example.com/api/registration',{method:'PUT',headers,body:JSON.stringify({enabled:true,inviteCode:'x'})}),e);assert.equal(r.status,503);assert.deepEqual(await r.json(),{error:'invite_code_pepper_unavailable'});assert.equal(batches,0)});

test('动态 Access JWKS 同 issuer 复用缓存且 kid 缺失时强制刷新一次',async()=>{const originalFetch=globalThis.fetch;let certFetches=0;try{globalThis.fetch=async url=>{assert.match(String(url),/\/cdn-cgi\/access\/certs$/);certFetches++;return new Response(JSON.stringify({keys:[jwk]}),{headers:{'content-type':'application/json'}})};const {default:worker}=await mod(),dynamicEnv={...env,ACCESS_JWKS:undefined,MAIN_SITE_URL:undefined};assert.equal((await worker.fetch(req('/',access('admin@example.com')),dynamicEnv)).status,200);assert.equal((await worker.fetch(req('/',access('admin@example.com')),dynamicEnv)).status,200);assert.equal(certFetches,1);assert.equal((await worker.fetch(req('/',access('admin@example.com',{}, {kid:'missing-key'})),dynamicEnv)).status,401);assert.equal(certFetches,2)}finally{globalThis.fetch=originalFetch}});

test('ACCESS_JWKS 静态配置验证不发起任何网络请求',async()=>{const originalFetch=globalThis.fetch;try{globalThis.fetch=async()=>{throw new Error('network must not be used')};const {default:worker}=await mod();assert.equal((await worker.fetch(req('/',access('admin@example.com')),{...env,MAIN_SITE_URL:undefined})).status,200)}finally{globalThis.fetch=originalFetch}});

test('R2真实统计完整遍历超过20页并仅在确实未完成时标记截断',async()=>{const {default:worker}=await mod();let calls=0;const e={...env,ATTACHMENTS:{list:async()=>{calls++;return{objects:[{size:calls}],truncated:calls<21,cursor:calls<21?'cursor-'+calls:undefined}}}};const r=await worker.fetch(req('/api/overview',access('admin@example.com')),e),data=await r.json();assert.equal(r.status,200);assert.equal(calls,21);assert.equal(data.resources.r2.objects,21);assert.equal(data.resources.r2.bytes,231);assert.equal(data.resources.r2.truncated,false);assert.equal(data.health.r2,true)});

test('Admin R2容量配置仅使用源码8GiB口径且wrangler不保留10GiB漂移变量',async()=>{const config=await readFile(new URL('../apps/admin-worker/wrangler.jsonc',import.meta.url),'utf8');assert.doesNotMatch(config,/R2_LIMIT_BYTES/);assert.doesNotMatch(config,/10737418240/);const {default:worker}=await mod(),data=await (await worker.fetch(req('/api/overview',access('admin@example.com')),env)).json();assert.equal(data.resources.r2.limitBytes,8*1024**3)});

test('强制退出和维护重试必须同源并写入审计记录',async()=>{const {default:worker}=await mod();const sql=[];class ActionDB{prepare(s){const x={sql:s,args:[],bind(...a){this.args=a;return this},first:async()=>s.startsWith('SELECT id FROM users')?{id:'u1',session_count:2}:s.includes('pending_r2_deletions')?null:null,all:async()=>({results:[]}),run:async()=>{sql.push([s,x.args]);return{meta:{changes:2}}}};return x}async batch(stmts){return Promise.all(stmts.map(x=>x.run()))}}const actionEnv={...env,DB:new ActionDB(),ATTACHMENTS:{...env.ATTACHMENTS,delete:async()=>{}}},h={...access('admin@example.com'),origin:'https://admin.example.com'};let r=await worker.fetch(new Request('https://admin.example.com/api/users/admin/sessions',{method:'DELETE',headers:h}),actionEnv);assert.equal(r.status,200);assert.equal((await r.json()).revoked,2);r=await worker.fetch(new Request('https://admin.example.com/api/maintenance/retry',{method:'POST',headers:h}),actionEnv);assert.equal(r.status,200);assert.ok(sql.some(x=>x[0].includes('admin_audit_logs')));r=await worker.fetch(new Request('https://admin.example.com/api/maintenance/retry',{method:'POST',headers:{...h,origin:'https://evil.example'}}),actionEnv);assert.equal(r.status,403)});

test('管理员表单和确认流程使用面板自有控件而非浏览器原生弹窗',async()=>{const {default:worker}=await mod();const headers=access('admin@example.com');const html=await (await worker.fetch(req('/',headers),env)).text(),js=await (await worker.fetch(req('/app.js',headers),env)).text();assert.match(html,/<dialog id="admin-dialog"/);assert.match(html,/class="field-control"/);assert.match(html,/\[hidden\]\{display:none!important\}/);assert.match(js,/openAdminDialog/);assert.doesNotMatch(js,/\bprompt\s*\(/);assert.doesNotMatch(js,/\bconfirm\s*\(/);assert.doesNotMatch(js,/\balert\s*\(/)});

test('容量指标紧凑展示已用总量剩余且不显示NaN',async()=>{const {default:worker}=await mod();let rendered='';const root={set innerHTML(v){rendered=v},get innerHTML(){return rendered},querySelectorAll(){return[]},querySelector(){return null}};const fetch=async()=>({ok:true,json:async()=>({summary:{users:2,entries:256,attachments:5,attachmentBytes:1406248,activeSessions:1,pendingDeletions:0,inflightUploads:0,backupLocks:0},resources:{r2:{objects:5,bytes:1406248,limitBytes:10000000000,classA:43,classB:116,classALimitMonthly:1000000,classBLimitMonthly:10000000},d1:{bytes:356352,limitBytes:500000000},workers:{requestsMonth:15354,errorsMonth:4,requestLimitDaily:100000}},users:[{username:'<admin&"',createdAt:1000,entries:2,attachments:1,attachmentBytes:1200,activeSessions:1,lastAuthMethod:'password',lastSeenAt:4000,passkeys:0}],health:{dbMs:3,r2Ms:4,r2:true},registration:{enabled:true,inviteCodeSet:true},trend:[],healthEvents:[],audit:[{actor:'admin@example.com',action:'update_registration',target:'',details:'{"enabled":true,"inviteCodeSet":true}',createdAt:5000},{actor:'admin@example.com',action:'delete_user',target:'aaa',details:'{}',createdAt:4000}],runtime:{version:'12345678-abcd-1234-abcd-123456789abc',appVersion:'1.1.72'}})});const r=await worker.fetch(req('/app.js',access('admin@example.com')),env),scriptText=await r.text();vm.runInNewContext(scriptText,{Intl,Date,fetch,setInterval:()=>0,document:{hidden:false,querySelector:()=>root}});await new Promise(resolve=>setTimeout(resolve,0));assert.doesNotMatch(rendered,/NaN/);assert.match(rendered,/D1 存储/);assert.match(rendered,/356 KB \/ 500 MB/);assert.match(rendered,/R2 存储/);assert.match(rendered,/1\.41 MB \/ 10 GB/);assert.match(rendered,/剩余/);assert.match(rendered,/系统状态/);assert.match(rendered,/运行正常/);assert.match(rendered,/D1 正常/);assert.match(rendered,/R2 正常/);assert.match(rendered,/删除用户/);assert.match(await (await worker.fetch(req('/',access('admin@example.com')),env)).text(),/退出登录[\s\S]*?<\/a>/);assert.match(await (await worker.fetch(req('/',access('admin@example.com')),env)).text(),/\/cdn-cgi\/access\/logout/);assert.match(rendered,/data-delete-index/);assert.match(rendered,/v1\.1\.72/);assert.match(rendered,/Worker [0-9a-f-]+/);assert.match(rendered,/用户搜索/);assert.match(rendered,/最近活动/);assert.match(rendered,/查看详情/);assert.match(rendered,/强制退出/);assert.match(rendered,/运维任务/);assert.match(rendered,/审计记录/);assert.match(rendered,/D1 [0-9]+ ms/);assert.match(rendered,/R2 [0-9]+ ms/);assert.match(rendered,/注册控制/);assert.match(rendered,/更新注册码/);assert.match(rendered,/D1 0\.07%/);assert.match(rendered,/已用 356 KB/);assert.match(rendered,/R2 0\.01%/);assert.match(rendered,/已用 1\.41 MB/);assert.match(rendered,/最近异常/);assert.match(rendered,/更新注册设置/);assert.match(rendered,/操作者：admin@example\.com/);assert.match(rendered,/目标：用户 aaa/);assert.doesNotMatch(rendered,/update_registration/);assert.doesNotMatch(rendered,/<admin&"/);assert.ok((rendered.match(/class="card metric"/g)||[]).length<=4)});


test('页面提供局部刷新按钮且刷新时保留搜索排序状态',async()=>{const {default:worker}=await mod();const js=await (await worker.fetch(req('/app.js',access('admin@example.com')),env)).text();assert.match(js,/data-refresh/);assert.match(js,/正在刷新/);assert.match(js,/await load\(\)/);assert.match(js,/search\.value=query/);assert.match(js,/sort\.value=order/)});

test('移动端管理面板使用清晰的两列统计并让真实用户卡片在窄屏重排',async()=>{const {default:worker}=await mod();const h=access('admin@example.com'),html=await (await worker.fetch(req('/',h),env)).text(),js=await (await worker.fetch(req('/app.js',h),env)).text();assert.match(html,/PASS VAULT · ADMIN/);assert.match(html,/class="brand-mark"/);assert.match(html,/data-refresh[^>]*aria-label="刷新面板数据"/);assert.match(html,/@media\(max-width:760px\)[\s\S]*\.summary-grid\{grid-template-columns:repeat\(2,1fr\)/);assert.match(html,/@media\(max-width:760px\)[\s\S]*\.section-head:has\(\.controls\)\{[^}]*margin-bottom:16px/);assert.match(html,/@media\(max-width:760px\)[\s\S]*\.section-head:has\(\+\.detail-grid\)\{[^}]*margin-bottom:16px/);assert.match(html,/@media\(max-width:760px\)[\s\S]*\.user\{[^}]*grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);assert.match(html,/@media\(max-width:760px\)[\s\S]*\.user>div\{[^}]*min-width:0/);assert.match(html,/@media\(max-width:760px\)[\s\S]*\.row-actions\{[^}]*grid-column:1\/-1/);assert.match(html,/\.refresh-action/);assert.match(js,/class="grid summary-grid"/)});


test('R2维护重试保护仍被引用对象并以changes条件防止并发重复扣减',async()=>{const {default:worker}=await mod();const sql=[],deleted=[];class MaintenanceDB{prepare(s){sql.push([s,[]]);const x={sql:s,args:[],bind(...a){this.args=a;sql.at(-1)[1]=a;return this},first:async()=>s.startsWith('SELECT 1 FROM attachments')&&x.args[0]==='live'?{1:1}:null,all:async()=>s.startsWith('SELECT user_id,object_key,ciphertext_size FROM pending_r2_deletions')?{results:[{user_id:'u1',object_key:'live',ciphertext_size:10},{user_id:'u1',object_key:'stale',ciphertext_size:20}]}:{results:[]},run:async()=>{sql.push([s,x.args]);return{meta:{changes:1}}}};return x}async batch(stmts){for(const x of stmts)sql.push([x.sql,x.args]);return stmts.map((x,i)=>({meta:{changes:i===0?1:1}}))}}const e={...env,DB:new MaintenanceDB(),ATTACHMENTS:{...env.ATTACHMENTS,delete:async key=>deleted.push(key)}},h={...access('admin@example.com'),origin:'https://admin.example.com'};const r=await worker.fetch(new Request('https://admin.example.com/api/maintenance/retry',{method:'POST',headers:h}),e);assert.equal(r.status,200);assert.deepEqual(await r.json(),{processed:1,failed:0,protected:1});assert.deepEqual(deleted,['stale']);const text=sql.map(x=>x[0]).join('\n');assert.match(text,/attachment_versions/);assert.match(text,/secure_share_objects/);assert.match(text,/changes\(\)=1/);assert.match(text,/reserved_bytes>=\?/)});

test('注册设置和强制退出将核心D1写入与审计放在同一batch',async()=>{const {default:worker}=await mod();const batches=[];class AtomicDB{prepare(s){return{sql:s,args:[],bind(...a){this.args=a;return this},first:async()=>s.startsWith('SELECT id FROM users')?{id:'u1',session_count:3}:null,all:async()=>({results:[]}),run:async()=>({meta:{changes:1}})}}async batch(stmts){batches.push(stmts.map(x=>x.sql));return stmts.map(()=>({meta:{changes:1}}))}}const e={...env,DB:new AtomicDB()},base={...access('admin@example.com'),origin:'https://admin.example.com'};let r=await worker.fetch(new Request('https://admin.example.com/api/registration',{method:'PUT',headers:{...base,'content-type':'application/json'},body:JSON.stringify({enabled:false})}),e);assert.equal(r.status,200);r=await worker.fetch(new Request('https://admin.example.com/api/users/admin/sessions',{method:'DELETE',headers:base}),e);assert.equal(r.status,200);assert.ok(batches[0].some(s=>s.includes('admin_settings'))&&batches[0].some(s=>s.includes('admin_audit_logs')));assert.ok(batches[1].some(s=>s.includes('DELETE FROM sessions'))&&batches[1].some(s=>s.includes('admin_audit_logs')))});

test('安全事件和审计记录提供紧凑筛选摘要且不暴露内部键或敏感值',async()=>{const {default:worker}=await mod(),h=access('admin@example.com'),js=await (await worker.fetch(req('/app.js',h),env)).text(),html=await (await worker.fetch(req('/',h),env)).text();for(const label of ['安全事件','审计日志','全部事件','全部操作','登录失败','登录限流','删除用户','强制退出'])assert.match(js,new RegExp(label));assert.match(js,/data-security-filter/);assert.match(js,/data-audit-filter/);assert.match(js,/安全事件只保存聚合计数/);assert.doesNotMatch(js,/subject_hash/);assert.match(html,/\.ops-list/);assert.match(html,/@media\(max-width:760px\)[\s\S]*\.ops-toolbar/)});

test('Admin 概览提供维护任务、安全摘要与生效配额但不泄露内部对象键',async()=>{const {default:worker}=await mod(),prepared=[];class OpsDB extends DB{prepare(sql){prepared.push(sql);const stmt=super.prepare(sql);if(sql.includes('FROM maintenance_runs'))stmt.all=async()=>({results:[{status:'failed',started_at:1000,finished_at:2000,processed:2,failed:1,error_code:'maintenance_failed'}]});if(sql.includes('LEFT JOIN user_quotas'))stmt.all=async()=>({results:[{username:'admin',created_at:1000,entry_count:2,attachment_count:1,attachment_bytes:1200,active_sessions:1,last_seen_at:4000,last_auth_method:'password',passkey_count:0,password_iterations:100000,entry_limit:500,attachment_count_limit:20,attachment_bytes_limit:209715200,quota_expires_at:null}]});return stmt}}const e={...env,DB:new OpsDB()},h=access('admin@example.com'),r=await worker.fetch(req('/api/overview',h),e),text=await r.text(),data=JSON.parse(text);assert.equal(data.maintenance.latest.status,'failed');assert.equal(data.securitySummary.failed24h>=0,true);assert.equal(data.users[0].quota.entryLimit,500);assert.equal(text.includes('object_key'),false);assert.ok(prepared.some(s=>s.includes('maintenance_runs')));assert.ok(prepared.some(s=>s.includes('user_quotas')))});

test('Admin 配额更新要求同源、严格边界并与审计记录原子提交',async()=>{const {default:worker}=await mod(),batches=[];class QuotaDB{prepare(sql){return{sql,args:[],bind(...args){this.args=args;return this},first:async()=>sql.startsWith('SELECT id FROM users')?{id:'u1'}:null,all:async()=>({results:[]}),run:async()=>({meta:{changes:1}})}}async batch(stmts){batches.push(stmts);return stmts.map(()=>({meta:{changes:1}}))}}const e={...env,DB:new QuotaDB()},base={...access('admin@example.com'),origin:'https://admin.example.com','content-type':'application/json'};let r=await worker.fetch(new Request('https://admin.example.com/api/users/admin/quota',{method:'PUT',headers:{...base,origin:'https://evil.example'},body:'{}'}),e);assert.equal(r.status,403);r=await worker.fetch(new Request('https://admin.example.com/api/users/admin/quota',{method:'PUT',headers:base,body:JSON.stringify({entryLimit:500,attachmentCountLimit:20,attachmentBytesLimit:209715200,expiresAt:null})}),e);assert.equal(r.status,200);assert.ok(batches[0].some(x=>x.sql.includes('user_quotas')));assert.ok(batches[0].some(x=>x.sql.includes('admin_audit_logs')));r=await worker.fetch(new Request('https://admin.example.com/api/users/admin/quota',{method:'PUT',headers:base,body:JSON.stringify({entryLimit:0,attachmentCountLimit:-1,attachmentBytesLimit:1,expiresAt:null})}),e);assert.equal(r.status,400)});

test('Admin 用紧凑运维区、用户配额弹窗和一张安全摘要展示新增能力',async()=>{const {default:worker}=await mod(),h=access('admin@example.com'),html=await (await worker.fetch(req('/',h),env)).text(),js=await (await worker.fetch(req('/app.js',h),env)).text();for(const label of ['运维任务','最近运行','连续失败','编辑配额','安全摘要'])assert.match(js,new RegExp(label));assert.match(js,/data-quota-user/);assert.match(js,/\/quota/);assert.match(html,/\.ops-section/);assert.match(html,/@media\(max-width:760px\)[\s\S]*\.ops-row/)});

test('Admin 可将单用户覆盖恢复为系统默认并原子写入审计',async()=>{const {default:worker}=await mod(),batches=[];class ResetDB{prepare(sql){return{sql,args:[],bind(...args){this.args=args;return this},first:async()=>sql.startsWith('SELECT id FROM users')?{id:'u1'}:null,all:async()=>({results:[]}),run:async()=>({meta:{changes:1}})}}async batch(stmts){batches.push(stmts);return stmts.map(()=>({meta:{changes:1}}))}}const e={...env,DB:new ResetDB()},headers={...access('admin@example.com'),origin:'https://admin.example.com'};let r=await worker.fetch(new Request('https://admin.example.com/api/users/admin/quota',{method:'DELETE',headers:{...headers,origin:'https://evil.example'}}),e);assert.equal(r.status,403);r=await worker.fetch(new Request('https://admin.example.com/api/users/admin/quota',{method:'DELETE',headers}),e);assert.equal(r.status,200);assert.ok(batches[0].some(x=>x.sql.startsWith('DELETE FROM user_quotas')));assert.ok(batches[0].some(x=>x.sql.includes('admin_audit_logs')&&x.args.includes('reset_user_quota')))});

test('重复恢复默认配额不写成功审计并返回无覆盖状态',async()=>{const {default:worker}=await mod(),batches=[];class NoOverrideDB{prepare(sql){return{sql,args:[],bind(...args){this.args=args;return this},first:async()=>sql.startsWith('SELECT id FROM users')?{id:'u1'}:null,all:async()=>({results:[]}),run:async()=>({meta:{changes:0}})}}async batch(stmts){batches.push(stmts);return stmts.map(()=>({meta:{changes:0}}))}}const e={...env,DB:new NoOverrideDB()},headers={...access('admin@example.com'),origin:'https://admin.example.com'},r=await worker.fetch(new Request('https://admin.example.com/api/users/admin/quota',{method:'DELETE',headers}),e);assert.equal(r.status,409);assert.equal((await r.json()).error,'no_quota_override');assert.match(batches[0][1].sql,/WHERE changes\(\)>0/)});

test('Admin 提供按 70/85/95 阈值排序的紧凑配额预警名单',async()=>{const {default:worker}=await mod(),h=access('admin@example.com'),html=await (await worker.fetch(req('/',h),env)).text(),js=await (await worker.fetch(req('/app.js',h),env)).text();for(const label of ['配额预警','接近上限','恢复默认配额','95%','85%','70%','零上限已超限'])assert.match(js,new RegExp(label));assert.match(js,/quotaAlerts/);assert.match(js,/zeroLimitExceeded/);assert.match(js,/data-quota-reset/);assert.match(html,/\.quota-alert/);assert.match(html,/@media\(max-width:760px\)[\s\S]*\.quota-alert/);class AlertDB extends DB{prepare(sql){const stmt=super.prepare(sql);if(sql.includes('LEFT JOIN user_quotas'))stmt.all=async()=>({results:[{username:'finite',entry_count:200,attachment_count:0,attachment_bytes:0,entry_limit:100,attachment_count_limit:10,attachment_bytes_limit:100},{username:'zero',entry_count:0,attachment_count:1,attachment_bytes:0,entry_limit:100,attachment_count_limit:0,attachment_bytes_limit:100}]});return stmt}}const response=await worker.fetch(req('/api/overview',h),{...env,DB:new AlertDB()}),data=await response.json();assert.equal(data.quotaAlerts[0].username,'zero');assert.equal(data.quotaAlerts[0].zeroLimitExceeded,true);assert.equal(data.quotaAlerts[1].username,'finite')});

test('Admin 提供用户风险计数和可组合筛选且不把正常用户误报',async()=>{const {default:worker}=await mod(),h=access('admin@example.com'),js=await (await worker.fetch(req('/app.js',h),env)).text();for(const label of ['需要关注','接近配额','长期未登录','未设置 Passkey','会话异常','全部用户'])assert.match(js,new RegExp(label));assert.match(js,/data-risk-filter/);assert.match(js,/value="quotaNearLimit"/);assert.match(js,/value="manySessions"/);assert.match(js,/riskSummary\?\.quotaNearLimit/);assert.match(js,/riskSummary\?\.manySessions/);assert.match(js,/riskFlags/);class RiskDB extends DB{prepare(sql){const stmt=super.prepare(sql);if(sql.includes('LEFT JOIN user_quotas'))stmt.all=async()=>({results:[{username:'risky',created_at:1,entry_count:80,attachment_count:0,attachment_bytes:0,active_sessions:3,last_seen_at:1,last_auth_method:'password',passkey_count:0,password_iterations:100000,entry_limit:100,attachment_count_limit:10,attachment_bytes_limit:100},{username:'normal',created_at:1,entry_count:1,attachment_count:0,attachment_bytes:0,active_sessions:1,last_seen_at:Date.now(),last_auth_method:'passkey',passkey_count:1,password_iterations:100000,entry_limit:100,attachment_count_limit:10,attachment_bytes_limit:100}]});return stmt}}const data=await (await worker.fetch(req('/api/overview',h),{...env,DB:new RiskDB()})).json();assert.deepEqual(data.users[0].riskFlags,{quotaNearLimit:true,inactive:true,noPasskey:true,manySessions:true});assert.deepEqual(data.users[1].riskFlags,{quotaNearLimit:false,inactive:false,noPasskey:false,manySessions:false});assert.deepEqual(data.riskSummary,{attention:1,quotaNearLimit:1,inactive:1,noPasskey:1,manySessions:1})});

test('新注册且从未登录的用户仅在账户超过90天后标为长期未登录',async()=>{const {default:worker}=await mod(),h=access('admin@example.com');class NewUserDB extends DB{prepare(sql){const stmt=super.prepare(sql);if(sql.includes('LEFT JOIN user_quotas'))stmt.all=async()=>({results:[{username:'fresh',created_at:Date.now()-86400000,entry_count:0,attachment_count:0,attachment_bytes:0,active_sessions:0,last_seen_at:null,last_auth_method:null,passkey_count:0,password_iterations:100000},{username:'old',created_at:Date.now()-100*86400000,entry_count:0,attachment_count:0,attachment_bytes:0,active_sessions:0,last_seen_at:null,last_auth_method:null,passkey_count:0,password_iterations:100000}]});return stmt}}const data=await (await worker.fetch(req('/api/overview',h),{...env,DB:new NewUserDB()})).json();assert.equal(data.users[0].riskFlags.inactive,false);assert.equal(data.users[1].riskFlags.inactive,true)});

test('配额历史按每个用户保留最近记录而非全局100条截断',async()=>{const {default:worker}=await mod(),h=access('admin@example.com'),prepared=[];class PerUserHistoryDB extends DB{prepare(sql){prepared.push(sql);return super.prepare(sql)}}await worker.fetch(req('/api/overview',h),{...env,DB:new PerUserHistoryDB()});const sql=prepared.find(x=>x.includes("action IN ('update_user_quota','reset_user_quota')"));assert.match(sql,/ROW_NUMBER\(\) OVER \(PARTITION BY target_username ORDER BY created_at DESC/);assert.match(sql,/WHERE history_rank<=20/);assert.doesNotMatch(sql,/ORDER BY created_at DESC LIMIT 100/)});

test('用户详情展示结构化配额调整历史且不泄露内部动作键或敏感值',async()=>{const {default:worker}=await mod(),h=access('admin@example.com'),js=await (await worker.fetch(req('/app.js',h),env)).text();for(const label of ['配额调整历史','条目上限','附件数量上限','附件容量上限','恢复系统默认'])assert.match(js,new RegExp(label));assert.match(js,/quotaHistory/);assert.doesNotMatch(js,/details_json/);class HistoryDB extends DB{prepare(sql){const stmt=super.prepare(sql);if(sql.includes("action IN ('update_user_quota','reset_user_quota')"))stmt.all=async()=>({results:[{actor_email:'ops@example.com',action:'update_user_quota',target_username:'admin',details_json:'{"entryLimit":500,"attachmentCountLimit":20,"attachmentBytesLimit":209715200,"expiresAt":null}',created_at:5000},{actor_email:'ops@example.com',action:'reset_user_quota',target_username:'admin',details_json:'{}',created_at:4000}]});return stmt}}const data=await (await worker.fetch(req('/api/overview',h),{...env,DB:new HistoryDB()})).json(),text=JSON.stringify(data);assert.equal(data.quotaHistory.admin.length,2);assert.equal(data.quotaHistory.admin[0].details.entryLimit,500);assert.equal(text.includes('details_json'),false);assert.equal(text.includes('SECRET'),false)});

test('所有成功写操作都区分后续页面刷新失败且响应含HSTS',async()=>{const {default:worker}=await mod();const h=access('admin@example.com');const r=await worker.fetch(req('/app.js',h),env),js=await r.text();for(const message of ['会话已撤销，但列表刷新失败','注册状态已更新，但页面刷新失败','注册码已更新，但页面刷新失败','维护已执行，但页面刷新失败'])assert.match(js,new RegExp(message));assert.match(r.headers.get('strict-transport-security'),/max-age=31536000/)});
