import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit, devices } from 'playwright';
import { spawn } from 'node:child_process';
import { rm } from 'node:fs/promises';
import { withTestInviteEnv } from './fixtures.mjs';

const port=4333,base=`http://localhost:${port}`,db=`/tmp/pass-vault-auth-entrance-${process.pid}.sqlite`;
let server;
test.before(async()=>{server=spawn(process.execPath,['apps/server/server.mjs'],{env:{...withTestInviteEnv(),PORT:String(port),DB_PATH:db,ATTACHMENTS_DIR:`/tmp/pass-vault-auth-entrance-${process.pid}-files`,COOKIE_SECURE:'false'}});for(let i=0;i<120;i++){try{if((await fetch(base)).ok)return}catch{}await new Promise(r=>setTimeout(r,50))}throw Error('server timeout')});
test.after(async()=>{if(server?.exitCode===null){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r))}await rm(db,{force:true});await rm(`${db}-shm`,{force:true});await rm(`${db}-wal`,{force:true});await rm(`/tmp/pass-vault-auth-entrance-${process.pid}-files`,{recursive:true,force:true})});

const sample=()=>{const shell=document.querySelector('#auth'),el=document.querySelector('#auth-form'),style=getComputedStyle(el),box=shell.getBoundingClientRect();return{opacity:Number(style.opacity),transform:style.transform,animationName:style.animationName,animationDuration:style.animationDuration,box:[box.x,box.y,box.width,box.height],starts:window.__authStarts||0}};
const typography=()=>{const px=selector=>parseFloat(getComputedStyle(document.querySelector(selector)).fontSize);return{body:px('body'),eyebrow:px('.eyebrow'),title:px('#auth-title'),help:px('#auth-help'),label:px('#auth-form label'),hint:px('#username-hint'),input:px('#auth-form input'),button:px('#auth-form button')}};
async function run(browser,options,reducedMotion){const context=await browser.newContext({...options,reducedMotion});await context.addInitScript(()=>{window.__authStarts=0;window.__authStartSample=null;addEventListener('animationstart',event=>{if(event.animationName!=='auth-in')return;window.__authStarts++;const style=getComputedStyle(event.target);window.__authStartSample={opacity:Number(style.opacity),animationName:style.animationName,animationDuration:style.animationDuration}},true)});const page=await context.newPage();await page.goto(base,{waitUntil:'domcontentloaded'});const samples=await page.evaluate(async source=>{const get=(0,eval)(`(${source})`),out=[{ms:'same-frame',...get()}],started=performance.now();for(const ms of [0,16,50,120,180,240,420,600,760,850]){const wait=started+ms-performance.now();if(wait>0)await new Promise(r=>setTimeout(r,wait));out.push({ms,...get()})}return out},sample.toString());
 const startSample=await page.evaluate(()=>window.__authStartSample); const boxes=samples.map(x=>x.box);assert.ok(boxes.every(x=>JSON.stringify(x)===JSON.stringify(boxes[0])),'auth entrance shifted layout');
 if(reducedMotion==='reduce'){assert.ok(samples.every(x=>x.opacity===1&&x.transform==='none'&&x.animationName==='none'&&x.starts===0),JSON.stringify(samples))}
 else {assert.ok(startSample?.animationName==='auth-in'&&startSample.opacity<.9,'initial login should visibly fade in instead of flashing');assert.ok(parseFloat(startSample.animationDuration)>=.65,'login entrance should be smooth enough to perceive');assert.ok(samples.every(x=>x.starts<=1),'auth entrance replayed');assert.ok(samples.at(-1).opacity>.99,JSON.stringify(samples));await page.waitForFunction(()=>!document.querySelector('#auth').classList.contains('auth-initial'));const settled=await page.evaluate(sample);assert.equal(settled.opacity,1);assert.equal(settled.transform,'none');assert.equal(settled.animationName,'none');assert.equal(settled.starts,1);await page.getByRole('button',{name:'创建新库'}).click();await page.getByRole('button',{name:'返回登录'}).click();await page.getByRole('button',{name:'登录并解锁'}).click();await page.waitForTimeout(50);assert.equal((await page.evaluate(sample)).starts,1)}
 await context.close()}

async function verifyTypography(browser,options){const context=await browser.newContext(options);const page=await context.newPage();await page.goto(base,{waitUntil:'domcontentloaded'});const type=await page.evaluate(typography);assert.equal(type.body,15,JSON.stringify(type));assert.ok(type.eyebrow>=14,JSON.stringify(type));assert.ok(type.title>=30,JSON.stringify(type));assert.equal(type.help,16,JSON.stringify(type));assert.ok(type.label>=15,JSON.stringify(type));assert.ok(type.hint>=14,JSON.stringify(type));assert.equal(type.input,16,JSON.stringify(type));assert.equal(type.button,16,JSON.stringify(type));await context.close()}

test('auth typography keeps readable 14/16px hierarchy on desktop and phone',async()=>{for(const [launcher,cases] of [[chromium,[{viewport:{width:1280,height:800}},{viewport:{width:390,height:844}}]],[webkit,[{viewport:{width:1280,height:800}},{...devices['iPhone 13']}]]]){const browser=await launcher.launch({headless:true});try{for(const options of cases)await verifyTypography(browser,options)}finally{await browser.close()}}});

test('initial auth enters exactly once after first paint without layout shift or reduced-motion delay',async()=>{for(const [launcher,cases] of [[chromium,[{viewport:{width:1280,height:800}},{viewport:{width:390,height:844}}]],[webkit,[{viewport:{width:1280,height:800}},{...devices['iPhone 13']}]]]){const browser=await launcher.launch({headless:true});try{for(const options of cases)for(const motion of ['no-preference','reduce'])await run(browser,options,motion)}finally{await browser.close()}}});