import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
import { chromium, webkit } from 'playwright';

let server,base;
test.before(async()=>{server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://x').pathname,file=path==='/'?'public/index.html':path.startsWith('/shared/')?path.slice(1):join('public',path.slice(1)),body=await readFile(file);res.setHeader('content-type',({'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.svg':'image/svg+xml'}[extname(file)]||'application/octet-stream'));res.end(body)}catch{res.statusCode=404;res.end()}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}`});
test.after(()=>new Promise(r=>server.close(r)));
async function setup(page){let registration,revision=0,entries=[];await page.route('**/api/**',async route=>{const req=route.request(),path=new URL(req.url()).pathname,json=(body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});if(path==='/api/register'){registration=req.postDataJSON();return json({ok:true})}if(path==='/api/login')return json({csrf:'csrf',sessionId:'session',kdf:registration.kdf,wrappedKey:registration.wrappedKey,capabilities:{backend:'cloudflare'}});if(path==='/api/entries'&&req.method()==='GET')return json({items:entries});if(path==='/api/attachments'&&req.method()==='GET')return json({items:[]});if(path==='/api/session')return json({username:'conditional-ui',sessionId:'session',kdf:registration.kdf,wrappedKey:registration.wrappedKey});if(/^\/api\/entries\//.test(path)&&req.method()==='PUT'){const value={...req.postDataJSON(),createdAt:Date.now(),revision:++revision};entries=entries.filter(x=>x.id!==value.id);entries.push(value);return json(value)}return json({})});await page.goto(base);await page.getByRole('button',{name:'创建新库'}).click();await page.getByLabel('邀请码').fill('invite');await page.locator('#auth-form input[name=username]').fill('conditional-ui');await page.getByLabel('主密码',{exact:true}).fill('password');await page.getByRole('button',{name:'创建并进入'}).click();await page.locator('#vault').waitFor({state:'visible'});await page.locator('#menu').click();await page.getByRole('menuitem',{name:'自定义资料'}).click()}

for(const engine of [chromium,webkit])test(`${engine.name()} 条件字段按前置字段值显隐且不使用原生选择器`,async()=>{const browser=await engine.launch({headless:true}),page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});try{await setup(page);await page.getByRole('button',{name:'+ 新建'}).click();await page.getByRole('button',{name:'自定义资料',exact:true}).click();await page.getByRole('dialog',{name:'选择自定义资料模板'}).getByRole('button',{name:/空白资料/}).click();const editor=page.locator('#editor');await editor.getByLabel('标题',{exact:true}).fill('条件资料');await editor.getByRole('button',{name:'添加字段'}).click();await editor.getByRole('button',{name:'添加字段'}).click();await editor.getByLabel('字段名称 1').fill('环境');await editor.getByLabel('字段内容 1').fill('生产');await editor.getByLabel('字段名称 2').fill('堡垒机');await editor.getByLabel('字段内容 2').fill('jump.example.com');await editor.getByRole('button',{name:'设置字段 2 显示条件'}).click();const dialog=page.getByRole('dialog',{name:'设置显示条件'});assert.equal(await dialog.locator('select').count(),0);await dialog.getByRole('radio',{name:'环境'}).click();await dialog.getByLabel('等于').fill('生产');await dialog.getByRole('button',{name:'保存条件'}).click();await editor.getByRole('button',{name:'保存'}).click();await page.locator('.item-card',{hasText:'条件资料'}).click();const detail=page.locator('#detail');assert.match(await detail.textContent(),/堡垒机.*jump\.example\.com/s);await detail.getByRole('button',{name:'编辑'}).click();await editor.getByLabel('字段内容 1').fill('测试');await editor.getByRole('button',{name:'保存'}).click();await editor.waitFor({state:'hidden'});assert.equal((await detail.textContent()).includes('jump.example.com'),false)}finally{await browser.close()}});
