import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {extname,join} from 'node:path';
import {chromium,webkit} from 'playwright';

let server,base;
test.before(async()=>{server=createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://x').pathname,file=pathname==='/'?'public/index.html':pathname.startsWith('/shared/')?pathname.slice(1):join('public',pathname.slice(1)),body=await readFile(file);res.setHeader('content-type',({'.html':'text/html','.mjs':'text/javascript','.css':'text/css'}[extname(file)]||'application/octet-stream'));res.end(body)}catch{res.statusCode=404;res.end()}}).listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));base=`http://127.0.0.1:${server.address().port}`});
test.after(()=>new Promise(resolve=>server.close(resolve)));

async function openMore(page){let registration,entry;await page.route('**/api/**',async route=>{const request=route.request(),path=new URL(request.url()).pathname,json=(body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});if(path==='/api/register'){registration=request.postDataJSON();return json({ok:true},201)}if(path==='/api/login')return json({csrf:'csrf',sessionId:'session',kdf:registration.kdf,wrappedKey:registration.wrappedKey,capabilities:{backend:'d1'}});if(path==='/api/session')return json({username:'more-test',sessionId:'session',kdf:registration.kdf,wrappedKey:registration.wrappedKey});if(path==='/api/entries'&&request.method()==='GET')return json({items:entry?[entry]:[]});if(path==='/api/attachments')return json({items:[]});if(/^\/api\/entries\//.test(path)&&request.method()==='PUT'){entry={...request.postDataJSON(),createdAt:1,revision:1};return json(entry)}if(/\/versions$/.test(path))return json({versions:[]});if(path==='/api/shares')return json({shares:[]});return json({})});await page.goto(base);await page.getByRole('button',{name:'创建新库'}).click();await page.getByLabel('邀请码').fill('custom-more-invite');await page.locator('#auth-form input[name=username]').fill('more-test');await page.getByLabel('主密码',{exact:true}).fill('password');await page.getByRole('button',{name:'创建并进入'}).click();await page.locator('#vault').waitFor({state:'visible'});await page.getByRole('button',{name:'+ 新建'}).click();await page.getByRole('button',{name:'自定义资料',exact:true}).click();await page.getByRole('dialog',{name:'选择自定义资料模板'}).getByRole('button',{name:/服务器/}).click();const editor=page.getByRole('dialog',{name:'新建自定义资料'});await editor.getByLabel('标题',{exact:true}).fill('短屏服务器');await editor.getByRole('button',{name:'保存'}).click();await page.getByText('短屏服务器',{exact:true}).click();await page.locator('#detail').getByRole('button',{name:'更多',exact:true}).click();return page.getByRole('dialog',{name:'更多操作'});}

for(const engine of [chromium,webkit])test(`${engine.name()} 320x420 更多操作内部滚动且取消按钮始终可达`,async()=>{const browser=await engine.launch({headless:true}),page=await browser.newPage({viewport:{width:320,height:420},reducedMotion:'reduce'});try{const dialog=await openMore(page),geometry=await dialog.evaluate(d=>{const r=d.getBoundingClientRect(),head=d.querySelector('.custom-more-head').getBoundingClientRect(),list=d.querySelector('.custom-more-list'),lr=list.getBoundingClientRect(),footer=d.querySelector('.custom-more-footer').getBoundingClientRect(),cancel=d.querySelector('.custom-more-footer button').getBoundingClientRect();list.scrollTop=list.scrollHeight;return{display:getComputedStyle(d).display,direction:getComputedStyle(d).flexDirection,height:r.height,viewport:innerHeight,top:r.top,bottom:r.bottom,headTop:head.top,headBottom:head.bottom,listTop:lr.top,listBottom:lr.bottom,listOverflow:getComputedStyle(list).overflowY,listClient:list.clientHeight,listScroll:list.scrollHeight,footerTop:footer.top,footerBottom:footer.bottom,cancelTop:cancel.top,cancelBottom:cancel.bottom}});assert.equal(geometry.display,'flex',JSON.stringify(geometry));assert.equal(geometry.direction,'column',JSON.stringify(geometry));assert.ok(geometry.height<=geometry.viewport*.82+1,JSON.stringify(geometry));assert.ok(geometry.top>=0&&geometry.bottom<=420,JSON.stringify(geometry));assert.equal(geometry.listOverflow,'auto',JSON.stringify(geometry));assert.ok(geometry.listScroll>geometry.listClient,JSON.stringify(geometry));assert.ok(geometry.footerTop>=geometry.listBottom-1&&geometry.cancelBottom<=geometry.bottom+1,JSON.stringify(geometry));await dialog.getByRole('button',{name:'取消',exact:true}).click();await dialog.waitFor({state:'hidden'})}finally{await browser.close()}});
