import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, stat, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';

const script='scripts/deploy-linux-atomic.sh';
async function fixture(){const root=await mkdtemp(join(tmpdir(),'pv-deploy-')),source=join(root,'source'),app=join(root,'app');await mkdir(join(source,'dist'),{recursive:true});await mkdir(join(source,'apps/server'),{recursive:true});await mkdir(join(source,'shared'),{recursive:true});await writeFile(join(source,'dist/index.html'),'<script src="/theme-init.js?v=1.1.55"></script><script type="module" src="/app.mjs?v=1.1.55"></script>');await writeFile(join(source,'dist/theme-init.js'),'ok');await writeFile(join(source,'dist/app.mjs'),'ok');await writeFile(join(source,'dist/style.css'),'ok');await writeFile(join(source,'dist/app-shell.css'),'ok');await writeFile(join(source,'apps/server/server.mjs'),'ok');await writeFile(join(source,'shared/contract.mjs'),'ok');await writeFile(join(source,'package.json'),'{"version":"1.1.55"}');await mkdir(join(app,'releases/old'),{recursive:true});await writeFile(join(app,'releases/old/marker'),'old');await symlink(join(app,'releases/old'),join(app,'current'));return{root,source,app}}
function run(env){return spawnSync('bash',[script],{env:{...process.env,...env},encoding:'utf8'})}

test('Linux 原子部署创建只读版本、统一可读权限并输出脱敏证据',async()=>{const f=await fixture(),evidence=join(f.root,'evidence.json'),service=join(f.root,'service');await writeFile(service,'active');const r=run({PV_SOURCE:f.source,PV_APP_ROOT:f.app,PV_VERSION:'1.1.55',PV_SERVICE_COMMAND:`test -f ${service}`,PV_HEALTH_COMMAND:`grep -q 1.1.55 ${f.app}/current/dist/index.html`,PV_EVIDENCE:evidence});assert.equal(r.status,0,r.stderr||r.stdout);assert.match(await readFile(join(f.app,'current/dist/index.html'),'utf8'),/1.1.55/);assert.equal((await stat(join(f.app,'current/dist'))).mode&0o777,0o755);assert.equal((await stat(join(f.app,'current/dist/theme-init.js'))).mode&0o777,0o644);const out=JSON.parse(await readFile(evidence,'utf8'));assert.deepEqual(Object.keys(out).sort(),['at','health','rolledBack','status','version']);assert.equal(out.status,'PASS');assert.equal(out.version,'1.1.55');assert.equal(out.health,true)});

test('Linux 原子部署健康失败时恢复旧 current 并返回失败',async()=>{const f=await fixture(),evidence=join(f.root,'evidence.json');const r=run({PV_SOURCE:f.source,PV_APP_ROOT:f.app,PV_VERSION:'1.1.55',PV_SERVICE_COMMAND:'true',PV_HEALTH_COMMAND:'false',PV_EVIDENCE:evidence});assert.notEqual(r.status,0);assert.equal(await readFile(join(f.app,'current/marker'),'utf8'),'old');const out=JSON.parse(await readFile(evidence,'utf8'));assert.equal(out.status,'FAIL');assert.equal(out.rolledBack,true);assert.equal(out.health,false)});
test('Linux 原子部署拒绝覆盖同版本目录',async()=>{const f=await fixture(),candidate=join(f.app,'releases/pass-vault-v2-linux-1.1.55');await mkdir(candidate,{recursive:true});await writeFile(join(candidate,'marker'),'immutable');const r=run({PV_SOURCE:f.source,PV_APP_ROOT:f.app,PV_VERSION:'1.1.55',PV_SERVICE_COMMAND:'true',PV_HEALTH_COMMAND:'true',PV_EVIDENCE:join(f.root,'evidence.json')});assert.notEqual(r.status,0);assert.equal(await readFile(join(candidate,'marker'),'utf8'),'immutable')});
test('Linux 回滚重启失败时证据明确标记 ROLLBACK_FAILED',async()=>{const f=await fixture(),evidence=join(f.root,'evidence.json'),counter=join(f.root,'counter');await writeFile(counter,'0');const command=`n=$(cat ${counter}); echo $((n+1)) > ${counter}; test $n -eq 0`;const r=run({PV_SOURCE:f.source,PV_APP_ROOT:f.app,PV_VERSION:'1.1.55',PV_SERVICE_COMMAND:command,PV_HEALTH_COMMAND:'false',PV_EVIDENCE:evidence});assert.notEqual(r.status,0);const out=JSON.parse(await readFile(evidence,'utf8'));assert.equal(out.status,'ROLLBACK_FAILED');assert.equal(out.rolledBack,false)});

test('部署代理模板声明双端一致的关键安全头',async()=>{const nginx=await readFile('deploy/nginx.conf','utf8'),caddy=await readFile('deploy/Caddyfile','utf8');for(const text of [nginx,caddy])for(const header of ['Strict-Transport-Security','Permissions-Policy','Referrer-Policy','X-Content-Type-Options'])assert.match(text,new RegExp(header))});
