import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, stat, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';

const script='scripts/deploy-linux-atomic.sh';
async function fixture(){const root=await mkdtemp(join(tmpdir(),'pv-deploy-')),source=join(root,'source'),app=join(root,'app');await mkdir(join(source,'dist'),{recursive:true});await mkdir(join(source,'apps/server'),{recursive:true});await mkdir(join(source,'apps/admin-server'),{recursive:true});await mkdir(join(source,'shared'),{recursive:true});await writeFile(join(source,'dist/index.html'),'<script src="/theme-init.js?v=1.1.55"></script><script type="module" src="/app.mjs?v=1.1.55"></script>');await writeFile(join(source,'dist/theme-init.js'),'ok');await writeFile(join(source,'dist/app.mjs'),'ok');await writeFile(join(source,'dist/style.css'),'ok');await writeFile(join(source,'dist/app-shell.css'),'ok');await writeFile(join(source,'apps/server/server.mjs'),'ok');await writeFile(join(source,'apps/admin-server/server.mjs'),'ok');await writeFile(join(source,'shared/contract.mjs'),'ok');await writeFile(join(source,'package.json'),'{"version":"1.1.55"}');await mkdir(join(app,'releases/old'),{recursive:true});await writeFile(join(app,'releases/old/marker'),'old');await symlink(join(app,'releases/old'),join(app,'current'));return{root,source,app}}
function run(env){return spawnSync('bash',[script],{env:{...process.env,PV_POST_DEPLOY_COMMAND:'true',...env},encoding:'utf8'})}

test('Linux 原子部署创建只读版本、统一可读权限并输出脱敏证据',async()=>{const f=await fixture(),evidence=join(f.root,'evidence.json'),service=join(f.root,'service');await writeFile(service,'active');const r=run({PV_SOURCE:f.source,PV_APP_ROOT:f.app,PV_VERSION:'1.1.55',PV_SERVICE_COMMAND:`test -f ${service}`,PV_HEALTH_COMMAND:`grep -q 1.1.55 ${f.app}/current/dist/index.html`,PV_EVIDENCE:evidence});assert.equal(r.status,0,r.stderr||r.stdout);assert.match(await readFile(join(f.app,'current/dist/index.html'),'utf8'),/1.1.55/);assert.equal(await readFile(join(f.app,'current/apps/admin-server/server.mjs'),'utf8'),'ok');assert.equal((await stat(join(f.app,'current/dist'))).mode&0o777,0o755);assert.equal((await stat(join(f.app,'current/dist/theme-init.js'))).mode&0o777,0o644);const out=JSON.parse(await readFile(evidence,'utf8'));assert.deepEqual(Object.keys(out).sort(),['at','health','rolledBack','status','version']);assert.equal(out.status,'PASS');assert.equal(out.version,'1.1.55');assert.equal(out.health,true)});

test('Linux 原子部署健康失败时恢复旧 current 并返回失败',async()=>{const f=await fixture(),evidence=join(f.root,'evidence.json');const r=run({PV_SOURCE:f.source,PV_APP_ROOT:f.app,PV_VERSION:'1.1.55',PV_SERVICE_COMMAND:'true',PV_HEALTH_COMMAND:'false',PV_HEALTH_ATTEMPTS:'1',PV_HEALTH_INTERVAL:'0',PV_EVIDENCE:evidence});assert.notEqual(r.status,0);assert.equal(await readFile(join(f.app,'current/marker'),'utf8'),'old');const out=JSON.parse(await readFile(evidence,'utf8'));assert.equal(out.status,'FAIL');assert.equal(out.rolledBack,true);assert.equal(out.health,false)});
test('Linux 原子部署在切换 current 前安装锁定的生产依赖',async()=>{const f=await fixture(),evidence=join(f.root,'evidence.json'),dependency=join(f.root,'dependency');await mkdir(dependency);await writeFile(join(dependency,'package.json'),'{"name":"deployment-runtime-fixture","version":"1.0.0","type":"module","exports":"./index.mjs"}');await writeFile(join(dependency,'index.mjs'),'export const ready=true;');const packed=spawnSync('npm',['pack','--pack-destination',f.root],{cwd:dependency,encoding:'utf8'});assert.equal(packed.status,0,packed.stderr||packed.stdout);const tarball=join(f.root,packed.stdout.trim().split('\n').at(-1));await writeFile(join(f.source,'package.json'),JSON.stringify({version:'1.1.55',type:'module',dependencies:{'deployment-runtime-fixture':`file:${tarball}`}}));const lock=spawnSync('npm',['install','--package-lock-only','--ignore-scripts','--no-audit','--no-fund'],{cwd:f.source,encoding:'utf8'});assert.equal(lock.status,0,lock.stderr||lock.stdout);const service=`cd ${f.app}/current && node --input-type=module -e "import('deployment-runtime-fixture').then(m=>{if(!m.ready)process.exit(1)})"`;const r=run({PV_SOURCE:f.source,PV_APP_ROOT:f.app,PV_VERSION:'1.1.55',PV_SERVICE_COMMAND:service,PV_HEALTH_COMMAND:'true',PV_EVIDENCE:evidence});assert.equal(r.status,0,r.stderr||r.stdout);assert.equal((await stat(join(f.app,'current/node_modules/deployment-runtime-fixture'))).isDirectory(),true)});
test('Linux 原子部署拒绝覆盖同版本目录',async()=>{const f=await fixture(),candidate=join(f.app,'releases/pass-vault-linux-1.1.55');await mkdir(candidate,{recursive:true});await writeFile(join(candidate,'marker'),'immutable');const r=run({PV_SOURCE:f.source,PV_APP_ROOT:f.app,PV_VERSION:'1.1.55',PV_SERVICE_COMMAND:'true',PV_HEALTH_COMMAND:'true',PV_EVIDENCE:join(f.root,'evidence.json')});assert.notEqual(r.status,0);assert.equal(await readFile(join(candidate,'marker'),'utf8'),'immutable')});
test('Linux 原子部署支持commit绑定版本目录且静态验收失败会回滚',async()=>{const f=await fixture(),evidence=join(f.root,'evidence.json');const r=run({PV_SOURCE:f.source,PV_APP_ROOT:f.app,PV_VERSION:'1.1.55+g0123456789ab',PV_SERVICE_COMMAND:'true',PV_HEALTH_COMMAND:'true',PV_POST_DEPLOY_COMMAND:'false',PV_EVIDENCE:evidence});assert.notEqual(r.status,0);assert.equal(await readFile(join(f.app,'current/marker'),'utf8'),'old');const out=JSON.parse(await readFile(evidence,'utf8'));assert.equal(out.rolledBack,true);assert.equal(out.health,false)});
test('Linux 回滚重启失败时证据明确标记 ROLLBACK_FAILED',async()=>{const f=await fixture(),evidence=join(f.root,'evidence.json'),counter=join(f.root,'counter');await writeFile(counter,'0');const command=`n=$(cat ${counter}); echo $((n+1)) > ${counter}; test $n -eq 0`;const r=run({PV_SOURCE:f.source,PV_APP_ROOT:f.app,PV_VERSION:'1.1.55',PV_SERVICE_COMMAND:command,PV_HEALTH_COMMAND:'false',PV_HEALTH_ATTEMPTS:'1',PV_HEALTH_INTERVAL:'0',PV_EVIDENCE:evidence});assert.notEqual(r.status,0);const out=JSON.parse(await readFile(evidence,'utf8'));assert.equal(out.status,'ROLLBACK_FAILED');assert.equal(out.rolledBack,false)});

test('Linux 健康检查支持有界重试，瞬时未就绪不触发回滚',async()=>{const f=await fixture(),evidence=join(f.root,'evidence.json'),counter=join(f.root,'health-counter');await writeFile(counter,'0');const health=`n=$(cat ${counter}); echo $((n+1)) > ${counter}; test $n -ge 2`;const r=run({PV_SOURCE:f.source,PV_APP_ROOT:f.app,PV_VERSION:'1.1.55',PV_SERVICE_COMMAND:'true',PV_HEALTH_COMMAND:health,PV_HEALTH_ATTEMPTS:'3',PV_HEALTH_INTERVAL:'0',PV_EVIDENCE:evidence});assert.equal(r.status,0,r.stderr);assert.equal((await readFile(counter,'utf8')).trim(),'3');const out=JSON.parse(await readFile(evidence,'utf8'));assert.equal(out.status,'PASS');assert.equal(out.rolledBack,false)});

test('Linux 原子部署拒绝声明版本与包或HTML资产键不一致',async()=>{const f=await fixture(),base={PV_SOURCE:f.source,PV_APP_ROOT:f.app,PV_SERVICE_COMMAND:'true',PV_HEALTH_COMMAND:'true',PV_EVIDENCE:join(f.root,'evidence.json')};let r=run({...base,PV_VERSION:'1.1.56'});assert.notEqual(r.status,0);await writeFile(join(f.source,'package.json'),JSON.stringify({version:'1.1.56'}));r=run({...base,PV_VERSION:'1.1.56'});assert.notEqual(r.status,0);assert.equal(await readFile(join(f.app,'current/marker'),'utf8'),'old')});

test('部署代理模板声明双端一致的关键安全头',async()=>{const nginx=await readFile('deploy/nginx.conf','utf8'),caddy=await readFile('deploy/Caddyfile','utf8');for(const text of [nginx,caddy])for(const header of ['Strict-Transport-Security','Permissions-Policy','Referrer-Policy','X-Content-Type-Options'])assert.match(text,new RegExp(header))});

test('Linux systemd 模板采用最小权限沙箱、动态身份路径与依赖且不注入服务器托管 Vault Key',async()=>{for(const name of ['pass-vault.service','pass-vault-admin.service']){const unit=await readFile(`deploy/${name}`,'utf8');assert.match(unit,/^User=@APP_USER@$/m);assert.match(unit,/^Group=@APP_GROUP@$/m);assert.match(unit,/^EnvironmentFile=@ENV_FILE@$/m);for(const marker of ['@APP_DIR@','@DATA_DIR@'])assert.match(unit,new RegExp(marker));assert.doesNotMatch(unit,/PASSKEY_UNLOCK_KEK/)}const main=await readFile('deploy/pass-vault.service','utf8'),admin=await readFile('deploy/pass-vault-admin.service','utf8');assert.match(admin,/^After=@MAIN_UNIT@$/m);assert.match(admin,/^Wants=@MAIN_UNIT@$/m);for(const directive of ['UMask=0077','PrivateDevices=true','ProtectHome=true','ProtectKernelTunables=true','ProtectKernelModules=true','ProtectKernelLogs=true','ProtectControlGroups=true','RestrictSUIDSGID=true','LockPersonality=true','RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6','SystemCallArchitectures=native','RestartSec=5s'])assert.match(main,new RegExp(`^${directive.replaceAll('=','\\=')}$`,'m'))});

test('Linux 品牌改名文档只引导执行严格迁移脚本并覆盖完整迁移边界',async()=>{for(const file of ['docs/server-deployment.zh-CN.md','docs/server-deployment.en.md']){const guide=await readFile(file,'utf8'),migration=guide.split(/\n## 2\./,1)[0];for(const required of ['/opt/pass-vault-v2','/var/lib/pass-vault-v2','/etc/pass-vault-v2/pass-vault-v2.env','pass-vault-v2.service','PV_MIGRATION_MAINTENANCE_CONFIRMED=YES','scripts/migrate-linux-layout.sh','id -gn "$APP_USER"','APP_USER','APP_GROUP','cp -a','shares/','PASSKEY_UNLOCK_KEK','systemctl disable pass-vault-v2','PRAGMA quick_check'])assert.match(migration,new RegExp(required.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(migration,/STAMP=\$\(date|sudo cp -a \/var\/lib\/pass-vault-v2/);assert.match(migration,/WAL\/SHM/);assert.match(migration,/attachments\//);assert.match(migration,/shares\//);assert.match(migration,/rollback|回滚/i);assert.match(migration,/backup restore|备份恢复/i)}});
test('Linux 布局迁移严格失败关闭、保护既有unit并同步动态模板值',async()=>{const migration=await readFile('scripts/migrate-linux-layout.sh','utf8');for(const required of ['set -Eeuo pipefail','trap rollback_on_exit EXIT','status != 0 && STOP_ATTEMPTED && ! COMPLETED','STOP_ATTEMPTED=1','OLD_MAIN_WAS_ACTIVE','OLD_ADMIN_WAS_ACTIVE','APP_GROUP=$(id -gn "$APP_USER")','new unit destination already exists','cp -a -- "$OLD_DATA"/. "$NEW_DATA"/','PV_MIGRATION_MAINTENANCE_CONFIRMED','systemd-analyze verify','@APP_GROUP@','@ENV_FILE@','@MAIN_UNIT@'])assert.match(migration,new RegExp(required.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(migration,/APP_GROUP="\$APP_USER"/);assert.ok(migration.indexOf('STOP_ATTEMPTED=1')<migration.indexOf('systemctl stop "$OLD_ADMIN_UNIT" "$OLD_MAIN_UNIT"'))});
