import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
import { chromium, webkit } from 'playwright';

let server,base;
test.before(async()=>{server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://x').pathname,file=path==='/'?'public/index.html':path.startsWith('/shared/')?path.slice(1):join('public',path.slice(1)),body=await readFile(file);res.setHeader('content-type',({'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.svg':'image/svg+xml'}[extname(file)]||'application/octet-stream'));res.end(body)}catch{res.statusCode=404;res.end()}}).listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));base=`http://127.0.0.1:${server.address().port}`});
test.after(()=>new Promise(resolve=>server.close(resolve)));

async function setup(page){let registration;await page.route('**/api/**',async route=>{const req=route.request(),path=new URL(req.url()).pathname,json=(body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});if(path==='/api/register'){registration=req.postDataJSON();return json({ok:true})}if(path==='/api/login')return json({csrf:'csrf',sessionId:'session',kdf:registration.kdf,wrappedKey:registration.wrappedKey,capabilities:{backend:'cloudflare'}});if(path==='/api/entries'&&req.method()==='GET')return json({items:[]});if(path==='/api/attachments'&&req.method()==='GET')return json({items:[]});if(path==='/api/session')return json({username:'menu-focus',sessionId:'session',kdf:registration.kdf,wrappedKey:registration.wrappedKey});return json({})});await page.goto(base);await page.getByRole('button',{name:'创建新库'}).click();await page.getByLabel('邀请码').fill('menu-focus-invite');await page.locator('#auth-form input[name=username]').fill('menu-focus');await page.getByLabel('主密码',{exact:true}).fill('password');await page.getByRole('button',{name:'创建并进入'}).click();await page.locator('#vault').waitFor({state:'visible'})}

async function assertNoTextEntryFocus(page,dialogSelector){const state=await page.evaluate(selector=>{const dialog=document.querySelector(selector),active=document.activeElement;return{inside:dialog?.contains(active),tag:active?.tagName,type:active?.getAttribute?.('type'),contenteditable:active?.isContentEditable}},dialogSelector);assert.equal(state.inside,true,`${dialogSelector} 打开后焦点应留在弹窗内`);const textEntry=state.tag==='TEXTAREA'||state.tag==='INPUT'&&!['button','checkbox','radio','file','hidden','submit'].includes(state.type)||state.contenteditable;assert.equal(textEntry,false,`${dialogSelector} 打开后不应自动聚焦输入框`)}

for(const engine of [chromium,webkit])test(`${engine.name()} 带输入框的菜单打开后不自动聚焦输入框`,async()=>{const browser=await engine.launch({headless:true}),page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});try{await setup(page);await page.evaluate(()=>{window.__dialogFocusEntries=[];document.addEventListener('focusin',event=>{if(event.target.closest?.('dialog'))window.__dialogFocusEntries.push({id:event.target.id,tag:event.target.tagName,type:event.target.getAttribute?.('type')})})});
 await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'全站搜索'}).click();await assertNoTextEntryFocus(page,'#global-search');assert.equal(await page.evaluate(()=>window.__dialogFocusEntries.some(x=>x.id==='global-search-input')),false,'全站搜索打开过程中也不能短暂聚焦输入框');await page.locator('#global-search-input').click();assert.equal(await page.evaluate(()=>document.activeElement?.id),'global-search-input');await page.locator('#global-search [data-close="global-search"]').click();
 await page.evaluate(()=>window.__dialogFocusEntries=[]);await page.getByRole('button',{name:'+ 新建'}).click();await page.getByRole('button',{name:'自定义资料',exact:true}).click();await page.getByRole('dialog',{name:'选择自定义资料模板'}).getByRole('button',{name:/空白资料/}).click();const editor=page.locator('#editor');await editor.getByRole('button',{name:'添加字段'}).click();await editor.getByRole('button',{name:'添加字段'}).click();await editor.getByRole('button',{name:'设置字段 2 显示条件'}).click();await assertNoTextEntryFocus(page,'#custom-field-condition-dialog');assert.equal(await page.evaluate(()=>window.__dialogFocusEntries.some(x=>x.id==='custom-field-condition-value')),false,'条件菜单打开过程中也不能短暂聚焦输入框');await page.locator('#custom-field-condition-value').click();assert.equal(await page.evaluate(()=>document.activeElement?.id),'custom-field-condition-value');
 }finally{await browser.close()}});
