import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Miniflare} from 'miniflare';

async function executeSql(db,sql){const normalized=sql.replace(/\r/g,'').split('\n').filter(line=>!line.trim().startsWith('--')).join('\n').trim(),triggerAt=normalized.indexOf('CREATE TRIGGER');const prefix=triggerAt<0?normalized:normalized.slice(0,triggerAt),trigger=triggerAt<0?'':normalized.slice(triggerAt);for(const statement of prefix.split(';').map(x=>x.trim()).filter(Boolean))await db.prepare(statement).run();if(trigger)await db.prepare(trigger.replace(/;\s*$/,'')).run()}
async function database(schema,migrations=[]){const mf=new Miniflare({modules:true,compatibilityDate:'2026-07-11',d1Databases:['DB'],script:'export default {fetch(){return new Response("ok")}}'});const db=await mf.getD1Database('DB');await executeSql(db,schema);for(const file of migrations)await executeSql(db,await readFile(new URL(file,import.meta.url),'utf8'));return{mf,db}}

const base=`PRAGMA foreign_keys=ON;
CREATE TABLE users(id TEXT PRIMARY KEY);
CREATE TABLE entries(user_id TEXT NOT NULL,id TEXT NOT NULL,type TEXT NOT NULL,version INTEGER NOT NULL,iv TEXT NOT NULL,ciphertext TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,revision INTEGER NOT NULL,PRIMARY KEY(user_id,id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);`;

test('D1条目更新原子归档旧密文，单项保留10版且删除联动清理',async()=>{const {mf,db}=await database(base,['../apps/worker/migrations/0022_entry_versions.sql']);try{await db.prepare('INSERT INTO users VALUES(?)').bind('u1').run();await db.prepare('INSERT INTO entries VALUES(?,?,?,?,?,?,?,?,?)').bind('u1','entry_123','account',1,'iv0','cipher0',1,1,1).run();for(let revision=1;revision<=12;revision++)await db.prepare('UPDATE entries SET iv=?,ciphertext=?,updated_at=?,revision=revision+1 WHERE user_id=? AND id=? AND revision=?').bind(`iv${revision}`,`cipher${revision}`,revision+1,'u1','entry_123',revision).run();const rows=await db.prepare('SELECT source_revision,iv,ciphertext FROM entry_versions WHERE user_id=? AND entry_id=? ORDER BY source_revision').bind('u1','entry_123').all();assert.equal(rows.results.length,10);assert.deepEqual(rows.results[0],{source_revision:3,iv:'iv2',ciphertext:'cipher2'});assert.deepEqual(rows.results.at(-1),{source_revision:12,iv:'iv11',ciphertext:'cipher11'});await db.prepare('DELETE FROM entries WHERE user_id=? AND id=?').bind('u1','entry_123').run();assert.equal((await db.prepare('SELECT COUNT(*) n FROM entry_versions').first()).n,0)}finally{await mf.dispose()}});

test('D1历史只在成功CAS时产生且settings不归档',async()=>{const {mf,db}=await database(base,['../apps/worker/migrations/0022_entry_versions.sql']);try{await db.prepare('INSERT INTO users VALUES(?)').bind('u1').run();await db.prepare('INSERT INTO entries VALUES(?,?,?,?,?,?,?,?,?)').bind('u1','entry_123','note',1,'iv0','cipher0',1,1,1).run();let r=await db.prepare('UPDATE entries SET iv=?,ciphertext=?,revision=revision+1 WHERE user_id=? AND id=? AND revision=?').bind('bad','bad','u1','entry_123',99).run();assert.equal(r.meta.changes,0);assert.equal((await db.prepare('SELECT COUNT(*) n FROM entry_versions').first()).n,0);await db.prepare('INSERT INTO entries VALUES(?,?,?,?,?,?,?,?,?)').bind('u1','settings1','settings',1,'iv','cipher',1,1,1).run();await db.prepare('UPDATE entries SET iv=?,ciphertext=?,revision=2 WHERE user_id=? AND id=?').bind('iv2','cipher2','u1','settings1').run();assert.equal((await db.prepare('SELECT COUNT(*) n FROM entry_versions').first()).n,0)}finally{await mf.dispose()}});


test('D1带历史触发器的CAS以RETURNING实际revision连续成功且旧revision失败',async()=>{const {mf,db}=await database(base,['../apps/worker/migrations/0022_entry_versions.sql']);try{await db.prepare('INSERT INTO users VALUES(?)').bind('u1').run();await db.prepare('INSERT INTO entries VALUES(?,?,?,?,?,?,?,?,?)').bind('u1','entry_cas','note',1,'iv0','cipher0',1,1,1).run();const update=revision=>db.prepare('UPDATE entries SET iv=?,ciphertext=?,updated_at=?,revision=revision+1 WHERE user_id=? AND id=? AND revision=? RETURNING revision').bind(`iv${revision}`,`cipher${revision}`,revision+1,'u1','entry_cas',revision).first();assert.deepEqual(await update(1),{revision:2});assert.deepEqual(await update(2),{revision:3});assert.equal(await update(1),null);assert.equal((await db.prepare('SELECT revision FROM entries WHERE user_id=? AND id=?').bind('u1','entry_cas').first()).revision,3)}finally{await mf.dispose()}});

test('D1附件metadata与内容快照原子归档裁剪、登记R2待删并级联清理',async()=>{const schema=`PRAGMA foreign_keys=ON;CREATE TABLE users(id TEXT PRIMARY KEY);CREATE TABLE attachments(user_id TEXT NOT NULL,id TEXT NOT NULL,metadata_iv TEXT NOT NULL,metadata_ciphertext TEXT NOT NULL,object_key TEXT NOT NULL,ciphertext_size INTEGER NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,revision INTEGER NOT NULL,PRIMARY KEY(user_id,id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);CREATE TABLE pending_r2_deletions(object_key TEXT PRIMARY KEY,ciphertext_size INTEGER NOT NULL,created_at INTEGER NOT NULL);`;const {mf,db}=await database(schema,['../apps/worker/migrations/0023_attachment_versions.sql']);try{await db.prepare('INSERT INTO users VALUES(?)').bind('u1').run();await db.prepare('INSERT INTO attachments VALUES(?,?,?,?,?,?,?,?,?)').bind('u1','attach_123','iv1','cipher1','object1',16,1,1,1).run();for(let revision=1;revision<=12;revision++)await db.prepare('UPDATE attachments SET metadata_iv=?,metadata_ciphertext=?,object_key=?,ciphertext_size=?,updated_at=?,revision=revision+1 WHERE user_id=? AND id=? AND revision=?').bind(`iv${revision+1}`,`cipher${revision+1}`,`object${revision+1}`,16,revision+1,'u1','attach_123',revision).run();const versions=(await db.prepare('SELECT source_revision FROM attachment_versions ORDER BY source_revision').all()).results;assert.equal(versions.length,10);assert.deepEqual(versions.map(x=>x.source_revision),[3,4,5,6,7,8,9,10,11,12]);assert.deepEqual((await db.prepare('SELECT object_key FROM pending_r2_deletions ORDER BY object_key').all()).results,[{object_key:'object1'},{object_key:'object2'}]);await db.prepare('DELETE FROM attachments WHERE user_id=? AND id=?').bind('u1','attach_123').run();assert.equal((await db.prepare('SELECT COUNT(*) n FROM attachment_versions').first()).n,0)}finally{await mf.dispose()}});

test('D1附件历史按用户原子保留最近50版且隔离其他用户',async()=>{const schema=`PRAGMA foreign_keys=ON;CREATE TABLE users(id TEXT PRIMARY KEY);CREATE TABLE attachments(user_id TEXT NOT NULL,id TEXT NOT NULL,metadata_iv TEXT NOT NULL,metadata_ciphertext TEXT NOT NULL,object_key TEXT NOT NULL,ciphertext_size INTEGER NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,revision INTEGER NOT NULL,PRIMARY KEY(user_id,id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);CREATE TABLE pending_r2_deletions(object_key TEXT PRIMARY KEY,ciphertext_size INTEGER NOT NULL,created_at INTEGER NOT NULL);`;const {mf,db}=await database(schema,['../apps/worker/migrations/0023_attachment_versions.sql']);try{for(const user of ['u1','u2'])await db.prepare('INSERT INTO users VALUES(?)').bind(user).run();for(let item=0;item<6;item++){const id=`attach_${item}`;await db.prepare('INSERT INTO attachments VALUES(?,?,?,?,?,?,?,?,?)').bind('u1',id,'iv0','cipher0',`u1-${item}-0`,16,1,item,1).run();for(let revision=1;revision<=10;revision++)await db.prepare('UPDATE attachments SET metadata_iv=?,metadata_ciphertext=?,object_key=?,updated_at=?,revision=revision+1 WHERE user_id=? AND id=? AND revision=?').bind(`iv${revision}`,`cipher${revision}`,`u1-${item}-${revision}`,item*100+revision,'u1',id,revision).run()}await db.prepare('INSERT INTO attachments VALUES(?,?,?,?,?,?,?,?,?)').bind('u2','attach_other','iv0','cipher0','u2-0',16,1,1,1).run();for(let revision=1;revision<=3;revision++)await db.prepare('UPDATE attachments SET metadata_iv=?,metadata_ciphertext=?,object_key=?,updated_at=?,revision=revision+1 WHERE user_id=? AND id=? AND revision=?').bind(`iv${revision}`,`cipher${revision}`,`u2-${revision}`,revision,'u2','attach_other',revision).run();assert.equal((await db.prepare('SELECT COUNT(*) n FROM attachment_versions WHERE user_id=?').bind('u1').first()).n,50);assert.equal((await db.prepare('SELECT COUNT(*) n FROM attachment_versions WHERE user_id=?').bind('u2').first()).n,3);assert.equal((await db.prepare('SELECT COUNT(*) n FROM pending_r2_deletions WHERE object_key LIKE ?').bind('u1-%').first()).n,10)}finally{await mf.dispose()}});

test('D1分享原子限次消费、撤销和过期均fail-closed',async()=>{const schema=`CREATE TABLE users(id TEXT PRIMARY KEY);INSERT INTO users VALUES('u1');`;const {mf,db}=await database(schema,['../apps/worker/migrations/0021_secure_shares.sql']);try{const now=Date.now(),hash='h'.repeat(43);await db.prepare('INSERT INTO secure_shares(token_hash,user_id,version,iv,ciphertext,owner_note_version,owner_note_iv,owner_note_ciphertext,expires_at,max_views,view_count,revoked_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,0,NULL,?)').bind(hash,'u1',1,'i'.repeat(16),'cipher',1,'n'.repeat(16),'note',now+60000,3,now).run();const consume=()=>db.prepare('UPDATE secure_shares SET view_count=view_count+1 WHERE token_hash=? AND revoked_at IS NULL AND expires_at>? AND view_count<max_views RETURNING version,iv,ciphertext').bind(hash,now).first();const results=await Promise.all(Array.from({length:8},consume));assert.equal(results.filter(Boolean).length,3);assert.equal((await db.prepare('SELECT view_count FROM secure_shares WHERE token_hash=?').bind(hash).first()).view_count,3);await db.prepare('UPDATE secure_shares SET view_count=0,revoked_at=? WHERE token_hash=?').bind(now,hash).run();assert.equal(await consume(),null);await db.prepare('UPDATE secure_shares SET revoked_at=NULL,expires_at=? WHERE token_hash=?').bind(now-1,hash).run();assert.equal(await consume(),null)}finally{await mf.dispose()}});

test('D1分享v2 pending对象完整后commit，首次打开与单浏览器claim均原子',async()=>{const schema=`CREATE TABLE users(id TEXT PRIMARY KEY);INSERT INTO users VALUES('u1');`;const {mf,db}=await database(schema,['../apps/worker/migrations/0024_secure_shares_v2.sql']);try{const now=Date.now(),hash='p'.repeat(43),object='o'.repeat(43);await db.prepare("INSERT INTO secure_share_packages(token_hash,user_id,status,manifest_version,manifest_iv,manifest_ciphertext,owner_note_version,owner_note_iv,owner_note_ciphertext,upload_token_hash,expires_at,max_views,first_open,single_browser,created_at) VALUES(?,?,'pending',2,?,?,1,?,?,?, ?,10,1,1,?)").bind(hash,'u1','i'.repeat(16),'manifest','n'.repeat(16),'note','u'.repeat(43),now+60000,now).run();await db.prepare('INSERT INTO secure_share_objects(share_token_hash,opaque_id,object_key,expected_size) VALUES(?,?,?,?)').bind(hash,object,'share/object',4).run();let commit=await db.prepare("UPDATE secure_share_packages SET status='active',committed_at=? WHERE token_hash=? AND status='pending' AND NOT EXISTS(SELECT 1 FROM secure_share_objects WHERE share_token_hash=? AND (uploaded_at IS NULL OR ciphertext_size<>expected_size))").bind(now,hash,hash).run();assert.equal(commit.meta.changes,0);await db.prepare('UPDATE secure_share_objects SET ciphertext_size=4,uploaded_at=? WHERE share_token_hash=? AND opaque_id=?').bind(now,hash,object).run();commit=await db.prepare("UPDATE secure_share_packages SET status='active',committed_at=? WHERE token_hash=? AND status='pending' AND NOT EXISTS(SELECT 1 FROM secure_share_objects WHERE share_token_hash=? AND (uploaded_at IS NULL OR ciphertext_size<>expected_size))").bind(now,hash,hash).run();assert.equal(commit.meta.changes,1);const claim=()=>db.prepare("UPDATE secure_share_packages SET view_count=view_count+1,first_claimed_at=COALESCE(first_claimed_at,?),last_claimed_at=? WHERE token_hash=? AND status='active' AND revoked_at IS NULL AND expires_at>? AND view_count<max_views AND (first_open=0 OR view_count=0) AND (single_browser=0 OR NOT EXISTS(SELECT 1 FROM secure_share_sessions WHERE share_token_hash=? AND expires_at>?)) RETURNING view_count").bind(now,now,hash,now,hash,now).first();const results=await Promise.all(Array.from({length:8},claim));assert.equal(results.filter(Boolean).length,1);assert.equal(results.find(Boolean).view_count,1);await db.prepare('INSERT INTO secure_share_sessions(id_hash,share_token_hash,created_at,expires_at) VALUES(?,?,?,?)').bind('s'.repeat(43),hash,now,now+60000).run();assert.equal(await claim(),null)}finally{await mf.dispose()}});
