import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {encryptSharedSnapshot,decryptSharedSnapshot,parseShareFragment,encryptSharePackage,decryptSharePackage,encryptShareObject,decryptShareObject,wrapSharePackageKey,unwrapSharePackageKey,encodeShareFragment} from '../public/share-crypto.mjs';

const shareId='A'.repeat(43),snapshot={type:'account',plain:{platform:'Example',credentials:[{username:'alice',password:'secret'}]},sharedAt:123};

test('安全分享使用独立随机AES密钥、AAD绑定token并只从fragment解析',async()=>{const first=await encryptSharedSnapshot(snapshot,shareId),second=await encryptSharedSnapshot(snapshot,shareId);assert.match(first.key,/^[A-Za-z0-9_-]{43}$/);assert.notEqual(first.key,second.key);assert.notDeepEqual(first.envelope,second.envelope);assert.equal(JSON.stringify(first.envelope).includes('secret'),false);assert.deepEqual(await decryptSharedSnapshot(first.envelope,first.key,shareId),snapshot);await assert.rejects(()=>decryptSharedSnapshot(first.envelope,first.key,'B'.repeat(43)));assert.deepEqual(parseShareFragment(`#${shareId}.${first.key}`),{id:shareId,key:first.key});assert.equal(parseShareFragment(`?key=${first.key}`),null);assert.equal(parseShareFragment(`#${first.key}`),null)});

test('安全分享拒绝错误key、非规范key别名、错误token和畸形envelope',async()=>{const encrypted=await encryptSharedSnapshot(snapshot,shareId),alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_',last=alphabet.indexOf(encrypted.key.at(-1)),alias=encrypted.key.slice(0,-1)+alphabet[last+1],wrong=encrypted.key.slice(0,-2)+(encrypted.key.at(-2)==='A'?'B':'A')+encrypted.key.at(-1);assert.notEqual(alias,encrypted.key);await assert.rejects(()=>decryptSharedSnapshot(encrypted.envelope,wrong,shareId));await assert.rejects(()=>decryptSharedSnapshot(encrypted.envelope,alias,shareId),/invalid_base64url/);await assert.rejects(()=>encryptSharedSnapshot(snapshot,'short'));await assert.rejects(()=>decryptSharedSnapshot({...encrypted.envelope,plaintext:'leak'},encrypted.key,shareId));assert.equal(parseShareFragment('#bad.bad'),null)});

test('分享v2密码使用固定PBKDF2包装package key且fragment不携带原key',async()=>{const manifest={version:2,items:[snapshot],objects:[]},encrypted=await encryptSharePackage(manifest,shareId),wrapped=await wrapSharePackageKey(encrypted.key,'正确密码',shareId);assert.deepEqual(wrapped.kdf.iterations,310000);assert.equal(Buffer.from(wrapped.kdf.salt,'base64url').length,16);assert.equal(wrapped.wrap.version,2);const fragment=encodeShareFragment(shareId,{password:wrapped});assert.equal(fragment.includes(encrypted.key),false);const parsed=parseShareFragment(fragment);assert.equal(parsed.version,2);assert.equal(parsed.passwordProtected,true);const key=await unwrapSharePackageKey(parsed.password,'正确密码',shareId);assert.equal(key,encrypted.key);assert.deepEqual(await decryptSharePackage(encrypted.envelope,key,shareId),manifest);await assert.rejects(()=>unwrapSharePackageKey(parsed.password,'错误密码',shareId));});

test('分享v2无密码fragment、manifest和对象均使用规范base64url与token/object AAD隔离',async()=>{const encrypted=await encryptSharePackage({version:2,items:[snapshot],objects:[{id:'B'.repeat(43)}]},shareId),fragment=encodeShareFragment(shareId,{key:encrypted.key}),parsed=parseShareFragment(fragment);assert.deepEqual(parsed,{version:2,id:shareId,key:encrypted.key,passwordProtected:false});const objectId='B'.repeat(43),object=await encryptShareObject(new Uint8Array([1,2,3,4]),encrypted.key,shareId,objectId);assert.match(object.iv,/^[A-Za-z0-9_-]+$/);assert.match(object.ciphertext,/^[A-Za-z0-9_-]+$/);assert.deepEqual(await decryptShareObject(object,encrypted.key,shareId,objectId),new Uint8Array([1,2,3,4]));await assert.rejects(()=>decryptShareObject(object,encrypted.key,shareId,'C'.repeat(43)));await assert.rejects(()=>decryptSharePackage(encrypted.envelope,encrypted.key,'D'.repeat(43)));assert.equal(parseShareFragment(fragment+'='),null)});

test('历史异步解密与匿名附件下载都绑定可撤销生命周期 generation',async()=>{const app=await readFile(new URL('../public/app.mjs',import.meta.url),'utf8'),view=await readFile(new URL('../public/share-view.mjs',import.meta.url),'utf8');assert.match(app,/historyOperationGeneration=0/);assert.match(app,/\+\+historyOperationGeneration/);assert.match(app,/valid=\(\)=>vaultSessionValid\(key,generation\)&&operationGeneration===historyOperationGeneration/);assert.match(app,/await decryptItem[\s\S]*?if\(!valid\(\)\)return/);assert.match(view,/viewGeneration=0/);assert.match(view,/const generation=viewGeneration/);assert.match(view,/generation!==viewGeneration/);assert.match(view,/function clear\(\)\{\+\+viewGeneration/)});
