import test from 'node:test';
import assert from 'node:assert/strict';
import {MARKERS_ID,normalizeMarkerRegistry,markerRegistryFromResources,applyMarkerRegistry,markerRegistryWithChanges,applyMarkerPatches} from '../public/marker-state.mjs';

test('收藏置顶注册表严格规范化且设置ID稳定',()=>{assert.equal(MARKERS_ID,'markers_registry');assert.deepEqual(normalizeMarkerRegistry({version:1,items:[{type:'note',id:'entry_123',favorite:true,pinned:true,pinRank:2}]}),{version:1,items:[{type:'note',id:'entry_123',favorite:true,pinned:true,pinRank:2}]});assert.equal(normalizeMarkerRegistry({version:1,items:[{type:'note',id:'bad id',favorite:true}]}),null)});

test('收藏置顶状态与正文资源物理分离并可重新合并',()=>{const resources=[{type:'note',id:'entry_123',title:'正文',favorite:true,pinned:true,pinRank:0},{type:'attachment',id:'attach_123',name:'文件',favorite:true}],registry=markerRegistryFromResources(resources);assert.deepEqual(registry,{version:1,items:[{type:'note',id:'entry_123',favorite:true,pinned:true,pinRank:0},{type:'attachment',id:'attach_123',favorite:true}]});const plain=resources.map(({favorite,pinned,pinRank,...row})=>row);applyMarkerRegistry(plain,registry);assert.equal(plain[0].title,'正文');assert.deepEqual(plain.map(x=>({favorite:x.favorite,pinned:x.pinned,pinRank:x.pinRank})),[{favorite:true,pinned:true,pinRank:0},{favorite:true,pinned:undefined,pinRank:undefined}])});

test('跨页冲突按字段补丁重放并保留远端同项其他状态',()=>{const latest={version:1,items:[{type:'note',id:'entry_aaa',favorite:true},{type:'note',id:'entry_bbb',pinned:true}]};assert.deepEqual(applyMarkerPatches(latest,[{type:'note',id:'entry_aaa',field:'pinned',value:true}]),{version:1,items:[{type:'note',id:'entry_aaa',favorite:true,pinned:true},{type:'note',id:'entry_bbb',pinned:true}]});assert.deepEqual(applyMarkerPatches({version:1,items:[{type:'note',id:'entry_aaa',favorite:true,pinned:true,pinRank:2}]},[{type:'note',id:'entry_aaa',field:'favorite',value:false}]),{version:1,items:[{type:'note',id:'entry_aaa',pinned:true,pinRank:2}]});assert.deepEqual(applyMarkerPatches({version:1,items:[{type:'note',id:'entry_aaa',favorite:true,pinned:true,pinRank:2}]},[{type:'note',id:'entry_aaa',field:'pinned',value:false}]),{version:1,items:[{type:'note',id:'entry_aaa',favorite:true}]});const migration=markerRegistryWithChanges(latest,[{type:'note',id:'entry_aaa',pinned:true},{type:'note',id:'entry_ccc',favorite:true}],{preserveExisting:true});assert.deepEqual(migration,{version:1,items:[{type:'note',id:'entry_aaa',favorite:true},{type:'note',id:'entry_bbb',pinned:true},{type:'note',id:'entry_ccc',favorite:true}]})});
