import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit, devices } from 'playwright';
import { spawn } from 'node:child_process';
import { rm, readFile } from 'node:fs/promises';
import { withTestInviteEnv } from './fixtures.mjs';

const port=4357,base=`http://localhost:${port}`,db=`/tmp/pass-vault-mobile-input-zoom-${process.pid}.sqlite`;
let server;
test.before(async()=>{server=spawn(process.execPath,['apps/server/server.mjs'],{env:{...withTestInviteEnv(),PORT:String(port),DB_PATH:db,ATTACHMENTS_DIR:`/tmp/pass-vault-mobile-input-zoom-${process.pid}-files`,COOKIE_SECURE:'false'}});for(let i=0;i<120;i++){try{if((await fetch(base)).ok)return}catch{}await new Promise(r=>setTimeout(r,50))}throw Error('server timeout')});
test.after(async()=>{if(server?.exitCode===null){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r))}await rm(db,{force:true});await rm(`${db}-shm`,{force:true});await rm(`${db}-wal`,{force:true});await rm(`/tmp/pass-vault-mobile-input-zoom-${process.pid}-files`,{recursive:true,force:true})});

const editable='textarea,select,input:not([type="hidden"]):not([type="checkbox"]):not([type="radio"]):not([type="file"]):not([type="button"]):not([type="submit"]):not([type="reset"])';
async function inspectMobilePage(page,path){await page.goto(base+path,{waitUntil:'domcontentloaded'});return page.evaluate(selector=>{const production=[...document.querySelectorAll(selector)].map((node,index)=>({control:`production:${node.tagName.toLowerCase()}:${node.type||''}:${node.id||node.name||index}`,size:parseFloat(getComputedStyle(node).fontSize)}));const host=document.createElement('form'),types=['text','password','search','email','url','tel','number','date','time','datetime-local'];for(const type of types){const node=document.createElement('input');node.type=type;node.dataset.probe=type;host.append(node)}const area=document.createElement('textarea');area.dataset.probe='textarea';host.append(area);const select=document.createElement('select');select.dataset.probe='select';select.append(new Option('一'));host.append(select);document.body.append(host);const probes=[...host.elements].map(node=>({control:`probe:${node.dataset.probe}`,size:parseFloat(getComputedStyle(node).fontSize)}));const viewport=document.querySelector('meta[name="viewport"]')?.content||'';return{controls:[...production,...probes],viewport,overflow:document.documentElement.scrollWidth>innerWidth}},editable)}

test('手机端文本控件至少16px并禁用页面缩放',async()=>{for(const [launcher,options] of [[chromium,{...devices['Pixel 7']}],[webkit,{...devices['iPhone 13']}]] ){const browser=await launcher.launch({headless:true}),context=await browser.newContext(options),page=await context.newPage();try{for(const path of ['/','/share.html']){const evidence=await inspectMobilePage(page,path);assert.ok(evidence.controls.length>0,`${path} missing controls`);assert.ok(evidence.controls.every(({size})=>size>=16),JSON.stringify({path,...evidence}));assert.match(evidence.viewport,/maximum-scale\s*=\s*1(?:\.0*)?(?:,|$)/i,`${path}: ${evidence.viewport}`);assert.match(evidence.viewport,/user-scalable\s*=\s*no/i,`${path}: ${evidence.viewport}`);assert.equal(evidence.overflow,false,JSON.stringify({path,...evidence}))}}finally{await context.close();await browser.close()}}const redirect=await readFile('public/share/index.html','utf8');assert.match(redirect,/url=\/share\.html/);assert.equal(/user-scalable\s*=\s*no|maximum-scale\s*=\s*1(?:\.0*)?(?:,|\")/i.test(redirect),false)});
