import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';
import { spawn } from 'node:child_process';
import { rm } from 'node:fs/promises';
import { TEST_INVITE_CODE, withTestInviteEnv } from './fixtures.mjs';

const port=4397,base=`http://localhost:${port}`,db=`/tmp/pass-vault-quick-unlock-${process.pid}.sqlite`;let server;
async function start(){server=spawn(process.execPath,['apps/server/server.mjs'],{env:{...withTestInviteEnv(),PORT:String(port),DB_PATH:db,COOKIE_SECURE:'false'}});await new Promise((resolve,reject)=>{const end=Date.now()+5000;const ping=async()=>{try{if((await fetch(base)).ok)return resolve()}catch{}if(Date.now()>end)return reject(Error('server timeout'));setTimeout(ping,80)};ping()})}
async function stop(){if(server?.exitCode===null){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r))}await rm(db,{force:true})}
async function register(page){await page.goto(base);await page.getByRole('button',{name:'创建新库'}).click();await page.getByLabel('邀请码').fill(TEST_INVITE_CODE);const username=`quick-${Date.now()}-${Math.random()}`;await page.getByLabel('用户名').fill(username);await page.getByLabel('主密码',{exact:true}).fill('correct horse battery staple');await page.getByRole('button',{name:'创建并进入'}).click();await page.locator('#vault').waitFor({state:'visible'});return username}
async function installPrf(page){const cdp=await page.context().newCDPSession(page);await cdp.send('WebAuthn.enable');const {authenticatorId}=await cdp.send('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',ctap2Version:'ctap2_1',transport:'internal',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,hasPrf:true,automaticPresenceSimulation:true}});return{cdp,authenticatorId}}
async function peerLock(page){await page.evaluate(async()=>{const session=await fetch('/api/session').then(response=>response.json()),channel=new BroadcastChannel('pass-vault-sync');channel.postMessage({type:'lock',source:`test-peer-${crypto.randomUUID()}`,username:session.username,at:Date.now()});channel.close()});await page.locator('#auth').waitFor({state:'visible'})}

test.before(start);test.after(stop);

test('快速解锁弹窗准确披露同步凭据与浏览器数据迁移边界',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();try{await page.goto(base);assert.equal(await page.getByText('系统凭据可能由设备账户同步；快速解锁材料保存在当前浏览器。浏览器配置或整机数据迁移可能带走该材料，解锁仍需系统用户验证和原绑定登录会话。',{exact:true}).count(),1);assert.equal(await page.getByText('当前浏览器快速解锁',{exact:true}).count(),1)}finally{await page.close();await browser.close()}});

test('开启成功提示使用当前浏览器边界',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();await installPrf(page);try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await page.getByText('已开启当前浏览器快速解锁',{exact:true}).waitFor()}finally{await page.close();await browser.close()}});

async function installSafariRegistrationShape(page,{flags=0x05,malformed=false,variant='plain'}={}){
 await page.evaluate(({flags,malformed,variant})=>{
  const nativeCreate=navigator.credentials.create.bind(navigator.credentials);
  navigator.credentials.create=async options=>{
   const credential=await nativeCreate(options),authenticatorData=new Uint8Array(credential.response.getAuthenticatorData()),key=new TextEncoder().encode('authData');
   authenticatorData[32]=flags;
   let encoded=malformed?Uint8Array.of(0xa1,0x68,...key,0x58):Uint8Array.of(0xa1,0x68,...key,0x58,authenticatorData.length,...authenticatorData);
   if(variant==='tagged')encoded=Uint8Array.of(0xc0,...encoded);
   if(variant==='oversized'){const junk=new Uint8Array(16385);encoded=Uint8Array.of(0xa2,0x68,...key,0x58,authenticatorData.length,...authenticatorData,0x64,0x6a,0x75,0x6e,0x6b,0x5a,0,0,0x40,1,...junk)}
   if(variant==='deep'){const nested=Uint8Array.of(...Array(10).fill(0x81),0xf6);encoded=Uint8Array.of(0xa2,0x68,...key,0x58,authenticatorData.length,...authenticatorData,0x64,0x6a,0x75,0x6e,0x6b,...nested)}
   return {type:credential.type,rawId:credential.rawId,response:{attestationObject:encoded.buffer},getClientExtensionResults:()=>credential.getClientExtensionResults()};
  };
 },{flags,malformed,variant});
}

test('Safari注册响应仅提供attestationObject时仍严格验证UV并开启快速解锁',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();await installPrf(page);try{await register(page);await installSafariRegistrationShape(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByText('已开启').waitFor();assert.equal(await page.evaluate(async()=>(await import('/quick-unlock-device.mjs')).readQuickUnlock().then(Boolean)),true)}finally{await page.close();await browser.close()}});

test('WebKit引擎可从Safari标准attestationObject完成严格UV快速解锁记录写入',async()=>{const browser=await webkit.launch({headless:true}),page=await browser.newPage();try{await page.goto(base);const result=await page.evaluate(async()=>{const authData=new Uint8Array(37);authData[32]=0x05;const key=new TextEncoder().encode('authData'),attestationObject=Uint8Array.of(0xa1,0x68,...key,0x58,authData.length,...authData).buffer,prf=crypto.getRandomValues(new Uint8Array(32)),rawId=crypto.getRandomValues(new Uint8Array(32));Object.defineProperty(navigator,'credentials',{value:{create:async()=>({type:'public-key',rawId,response:{attestationObject},getClientExtensionResults:()=>({prf:{results:{first:prf}}})})},configurable:true});const module=await import('/quick-unlock-device.mjs'),vaultKey=await crypto.subtle.generateKey({name:'AES-GCM',length:256},true,['encrypt','decrypt']),record=await module.createQuickUnlock(vaultKey,'csrf-token','webkit-user','public-session');return{stored:Boolean(await module.readQuickUnlock()),credentialId:record.credentialId}});assert.equal(result.stored,true);assert.ok(result.credentialId)}finally{await page.close();await browser.close()}});

test('WebKit引擎允许UV已验证的同步型平台凭据写入当前浏览器快速解锁记录',async()=>{const browser=await webkit.launch({headless:true}),page=await browser.newPage();try{await page.goto(base);const result=await page.evaluate(async()=>{const authData=new Uint8Array(37);authData[32]=0x0d;const key=new TextEncoder().encode('authData'),attestationObject=Uint8Array.of(0xa1,0x68,...key,0x58,authData.length,...authData).buffer,prf=crypto.getRandomValues(new Uint8Array(32)),rawId=crypto.getRandomValues(new Uint8Array(32));Object.defineProperty(navigator,'credentials',{value:{create:async()=>({type:'public-key',rawId,response:{attestationObject},getClientExtensionResults:()=>({prf:{results:{first:prf}}})})},configurable:true});const module=await import('/quick-unlock-device.mjs'),vaultKey=await crypto.subtle.generateKey({name:'AES-GCM',length:256},true,['encrypt','decrypt']),record=await module.createQuickUnlock(vaultKey,'csrf-token','webkit-sync-user','public-session');return{stored:Boolean(await module.readQuickUnlock()),credentialId:record.credentialId}});assert.equal(result.stored,true);assert.ok(result.credentialId)}finally{await page.close();await browser.close()}});

test('Safari attestationObject缺少UV、CBOR截断或超限歧义编码时必须拒绝',async()=>{const browser=await chromium.launch({headless:true});for(const shape of [{flags:0x01},{flags:0x05,malformed:true},{variant:'tagged'},{variant:'oversized'},{variant:'deep'}]){const page=await browser.newPage();await installPrf(page);try{await register(page);await installSafariRegistrationShape(page,shape);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await enable.getByText('设备未完成本机用户验证，无法开启快速解锁').waitFor();assert.equal(await page.evaluate(async()=>(await import('/quick-unlock-device.mjs')).readQuickUnlock().then(Boolean)),false)}finally{await page.close()}}await browser.close()});

test('同步型平台凭据在锁库后仍可完成UV快速解锁且不重新登录',async()=>{const browser=await chromium.launch({headless:true}),context=await browser.newContext(),page=await context.newPage();await installPrf(page);let loginRequests=0;page.on('request',request=>{if(request.method()==='POST'&&request.url().endsWith('/api/login'))loginRequests++});try{const username=await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByText('已开启').waitFor();await security.getByRole('button',{name:'关闭',exact:true}).click();await peerLock(page);await page.evaluate(()=>{const native=navigator.credentials.get.bind(navigator.credentials);navigator.credentials.get=async options=>{const credential=await native(options),data=new Uint8Array(credential.response.authenticatorData);data[32]|=0x08;return{type:credential.type,rawId:credential.rawId,response:{authenticatorData:data.buffer},getClientExtensionResults:()=>credential.getClientExtensionResults()}}});const before=loginRequests;await page.getByRole('button',{name:'使用此设备快速解锁'}).click();await page.locator('#vault').waitFor({state:'visible'});assert.equal(loginRequests,before);assert.equal(await page.evaluate(()=>window.__vaultKeyPresent()),true)}finally{await context.close();await browser.close()}});

test('开启本机快速解锁后自动锁定可用设备验证恢复且不重新登录',async()=>{const browser=await chromium.launch({headless:true}),context=await browser.newContext(),page=await context.newPage();await installPrf(page);let loginRequests=0;page.on('request',request=>{if(request.method()==='POST'&&request.url().endsWith('/api/login'))loginRequests++});try{const username=await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByText('已开启').waitFor();assert.equal(await page.evaluate(()=>indexedDB.databases().then(rows=>rows.some(row=>row.name==='pass-vault-quick-unlock'))),true);await security.getByRole('button',{name:'关闭',exact:true}).click();await peerLock(page);await page.locator('#auth').waitFor({state:'visible'});await page.locator('[name=username]').waitFor();await page.waitForFunction(expected=>document.querySelector('[name=username]')?.value===expected,username);assert.equal(await page.locator('[name=username]').inputValue(),username);const before=loginRequests;await page.getByRole('button',{name:'使用此设备快速解锁'}).click();await page.locator('#vault').waitFor({state:'visible'});assert.equal(loginRequests,before);assert.equal(await page.evaluate(()=>window.__vaultKeyPresent()),true)}finally{await context.close();await browser.close()}});

test('主密码回退登录新会话会清理旧快速解锁记录',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();await installPrf(page);try{const username=await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();let security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();let enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByText('已开启').waitFor();await security.getByRole('button',{name:'关闭',exact:true}).click();await peerLock(page);await page.getByLabel('用户名').fill(username);await page.getByLabel('主密码',{exact:true}).fill('correct horse battery staple');await page.getByRole('button',{name:'登录并解锁'}).click();await page.locator('#vault').waitFor({state:'visible'});await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();security=page.getByRole('dialog',{name:'安全中心'});await security.getByText('未开启').waitFor();assert.equal(await page.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('pass-vault-quick-unlock');r.onsuccess=()=>{const q=r.result.transaction('records').objectStore('records').get('current');q.onsuccess=()=>resolve(Boolean(q.result))}})),false)}finally{await page.close();await browser.close()}});

test('旧操作条件删除不得误删另一标签写入的新记录',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();try{await page.goto(base);const result=await page.evaluate(async()=>{const module=await import('/quick-unlock-device.mjs'),baseRecord={version:1,username:'compare-user',sessionId:'session',credentialId:'credential',prfInput:'input',sealed:{version:1,iv:'iv',ciphertext:'ciphertext'},createdAt:1};await module.writeQuickUnlock({...baseRecord,recordId:'old'});await module.writeQuickUnlock({...baseRecord,recordId:'new'});await module.deleteQuickUnlockIfCurrent('old');return (await module.readQuickUnlock())?.recordId});assert.equal(result,'new')}finally{await page.close();await browser.close()}});

test('关闭快速解锁会删除本机记录且锁定页不再显示入口',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();await installPrf(page);try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByRole('button',{name:'关闭快速解锁'}).click();await security.getByText('未开启').waitFor();await security.getByRole('button',{name:'关闭',exact:true}).click();await peerLock(page);assert.equal(await page.getByRole('button',{name:'使用此设备快速解锁'}).count(),0)}finally{await page.close();await browser.close()}});

test('错误主密码和不支持的设备都不能创建快速解锁记录',async()=>{const browser=await chromium.launch({headless:true});for(const supported of [true,false]){const page=await browser.newPage();if(supported)await installPrf(page);else await page.addInitScript(()=>Object.defineProperty(globalThis,'PublicKeyCredential',{value:undefined,configurable:true}));try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});if(!supported){assert.equal(await security.getByRole('button',{name:'开启快速解锁'}).isDisabled(),true);assert.match(await security.locator('#quick-unlock-status').textContent(),/不支持/);continue}await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('wrong password here');await enable.getByRole('button',{name:'确认开启'}).click();await enable.getByText('当前主密码不正确').waitFor();assert.equal(await page.evaluate(()=>indexedDB.databases().then(async rows=>{if(!rows.some(row=>row.name==='pass-vault-quick-unlock'))return false;return new Promise(resolve=>{const r=indexedDB.open('pass-vault-quick-unlock');r.onsuccess=()=>{const q=r.result.transaction('records').objectStore('records').get('current');q.onsuccess=()=>resolve(Boolean(q.result))}})})),false)}finally{await page.close()}}await browser.close()});

test('会话失效时先失败，不触发设备PRF也不恢复本机密钥',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();await installPrf(page);try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByText('已开启').waitFor();await security.getByRole('button',{name:'关闭',exact:true}).click();await peerLock(page);await page.route('**/api/session',route=>route.fulfill({status:401,contentType:'application/json',body:'{"error":"unauthorized"}'}));await page.getByRole('button',{name:'使用此设备快速解锁'}).click();await page.getByText('登录已失效，请重新登录',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.__vaultKeyPresent()),false)}finally{await page.close();await browser.close()}});

test('设备验证等待期间发生锁库，迟到PRF不得恢复密钥',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();await installPrf(page);try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByText('已开启').waitFor();await security.getByRole('button',{name:'关闭',exact:true}).click();await peerLock(page);await page.evaluate(async()=>{const record=await new Promise(resolve=>{const open=indexedDB.open('pass-vault-quick-unlock');open.onsuccess=()=>{const get=open.result.transaction('records').objectStore('records').get('current');get.onsuccess=()=>resolve(get.result)}}),decode=value=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));const credential=await navigator.credentials.get({publicKey:{challenge:crypto.getRandomValues(new Uint8Array(32)),allowCredentials:[{type:'public-key',id:decode(record.credentialId)}],userVerification:'required',extensions:{prf:{eval:{first:decode(record.prfInput)}}}}}),prf=credential.getClientExtensionResults().prf.results.first,authenticatorData=credential.response.authenticatorData;window.__releaseNativeGet=null;navigator.credentials.get=()=>new Promise(resolve=>{window.__releaseNativeGet=()=>resolve({type:'public-key',rawId:decode(record.credentialId),response:{getAuthenticatorData:()=>authenticatorData},getClientExtensionResults:()=>({prf:{results:{first:prf}}})})})});await page.getByRole('button',{name:'使用此设备快速解锁'}).click();await page.waitForFunction(()=>window.__releaseNativeGet);await peerLock(page);await page.evaluate(()=>window.__releaseNativeGet());await page.waitForFunction(()=>!window.__vaultKeyPresent());assert.equal(await page.locator('#vault').isHidden(),true);assert.equal(await page.locator('#auth').isVisible(),true)}finally{await page.close();await browser.close()}});

test('主动退出并锁定会撤销本机快速解锁材料',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();await installPrf(page);try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByText('已开启').waitFor();await security.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'退出并锁定'}).click();await page.locator('#auth').waitFor({state:'visible'});assert.equal(await page.getByRole('button',{name:'使用此设备快速解锁'}).count(),0);assert.equal(await page.evaluate(()=>window.__vaultKeyPresent()),false);assert.equal(await page.evaluate(()=>fetch('/api/session').then(response=>response.status)),401)}finally{await page.close();await browser.close()}});

test('取消开启弹窗后迟到凭据不得留下本机记录',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage(),auth=await installPrf(page);try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await auth.cdp.send('WebAuthn.setAutomaticPresenceSimulation',{authenticatorId:auth.authenticatorId,enabled:false});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await enable.getByRole('button',{name:'正在验证…'}).waitFor();await enable.getByRole('button',{name:'取消'}).click();await enable.waitFor({state:'hidden'});await auth.cdp.send('WebAuthn.setAutomaticPresenceSimulation',{authenticatorId:auth.authenticatorId,enabled:true});await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('pass-vault-quick-unlock');r.onsuccess=()=>{const q=r.result.transaction('records').objectStore('records').get('current');q.onsuccess=()=>resolve(Boolean(q.result))}})),false);assert.equal(await security.getByText('未开启').isVisible(),true)}finally{await page.close();await browser.close()}});

test('记录提交后的刷新窗口取消仍必须回滚快速解锁',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();await installPrf(page);try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await page.evaluate(()=>{const original=indexedDB.open.bind(indexedDB);let opens=0;window.__quickRefreshWindow=false;indexedDB.open=(...args)=>{const request=original(...args);if(args[0]==='pass-vault-quick-unlock'&&++opens===2)request.addEventListener('success',event=>{event.stopImmediatePropagation();window.__quickRefreshWindow=true;setTimeout(()=>request.dispatchEvent(new Event('success')),600)},{capture:true,once:true});return request}});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await page.waitForFunction(()=>window.__quickRefreshWindow);await enable.getByRole('button',{name:'取消'}).click();await enable.waitFor({state:'hidden'});await page.waitForTimeout(800);assert.equal(await page.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('pass-vault-quick-unlock');r.onsuccess=()=>{const q=r.result.transaction('records').objectStore('records').get('current');q.onsuccess=()=>resolve(Boolean(q.result))}})),false);assert.equal(await security.getByText('未开启').isVisible(),true)}finally{await page.close();await browser.close()}});

test('开启设备验证等待期间锁库，迟到结果不得留下本机记录',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage(),auth=await installPrf(page);try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await auth.cdp.send('WebAuthn.setAutomaticPresenceSimulation',{authenticatorId:auth.authenticatorId,enabled:false});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await enable.getByRole('button',{name:'正在验证…'}).waitFor();await peerLock(page);await auth.cdp.send('WebAuthn.setAutomaticPresenceSimulation',{authenticatorId:auth.authenticatorId,enabled:true});await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('pass-vault-quick-unlock');r.onsuccess=()=>{const q=r.result.transaction('records').objectStore('records').get('current');q.onsuccess=()=>resolve(Boolean(q.result))}})),false);assert.equal(await page.evaluate(()=>window.__vaultKeyPresent()),false)}finally{await page.close();await browser.close()}});

test('同账户换成新会话时旧设备材料不得调用PRF或半解锁',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();await installPrf(page);try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByText('已开启').waitFor();await security.getByRole('button',{name:'关闭',exact:true}).click();await peerLock(page);await page.route('**/api/session',async route=>{const response=await route.fetch(),body=await response.json();await route.fulfill({response,json:{...body,sessionId:'different_session_public_id'}})});await page.getByRole('button',{name:'使用此设备快速解锁'}).click();await page.getByText('登录会话已失效，请使用主密码登录',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.__vaultKeyPresent()),false)}finally{await page.close();await browser.close()}});

test('设备验证后会话改变时第二次检查拒绝安装已解包密钥',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();await installPrf(page);try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByText('已开启').waitFor();await security.getByRole('button',{name:'关闭',exact:true}).click();await peerLock(page);let calls=0;await page.route('**/api/session',async route=>{calls++;const response=await route.fetch(),body=await response.json();await route.fulfill({response,json:calls===1?body:{...body,sessionId:'changed_after_device_verification'}})});await page.getByRole('button',{name:'使用此设备快速解锁'}).click();await page.getByText('登录会话已失效，请使用主密码登录',{exact:true}).waitFor();assert.equal(calls,2);assert.equal(await page.evaluate(()=>window.__vaultKeyPresent()),false);assert.equal(await page.locator('#vault').isHidden(),true)}finally{await page.close();await browser.close()}});

test('旧标签关闭快速解锁不得删除另一标签刚写入的新记录',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();await installPrf(page);try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByText('已开启').waitFor();await page.evaluate(async()=>{const module=await import('/quick-unlock-device.mjs'),record=await module.readQuickUnlock();await module.writeQuickUnlock({...record,recordId:'new-from-peer'})});await security.getByRole('button',{name:'关闭快速解锁'}).click();assert.equal(await page.evaluate(async()=>(await import('/quick-unlock-device.mjs')).readQuickUnlock().then(record=>record?.recordId)),'new-from-peer')}finally{await page.close();await browser.close()}});

test('旧标签logout不得删除另一标签刚写入的新记录',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();await installPrf(page);try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByText('已开启').waitFor();await security.getByRole('button',{name:'关闭',exact:true}).click();await page.evaluate(async()=>{const module=await import('/quick-unlock-device.mjs'),record=await module.readQuickUnlock();await module.writeQuickUnlock({...record,recordId:'new-from-peer'})});await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'退出并锁定'}).click();await page.locator('#auth').waitFor({state:'visible'});assert.equal(await page.evaluate(async()=>(await import('/quick-unlock-device.mjs')).readQuickUnlock().then(record=>record?.recordId)),'new-from-peer')}finally{await page.close();await browser.close()}});

test('IndexedDB删除失败时关闭不得伪报成功',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();await installPrf(page);try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByText('已开启').waitFor();await page.evaluate(()=>{const original=indexedDB.open.bind(indexedDB);indexedDB.open=(...args)=>{const request=original(...args);request.addEventListener('success',()=>{const database=request.result,transaction=database.transaction.bind(database);database.transaction=(...txArgs)=>{const tx=transaction(...txArgs);if(txArgs[1]==='readwrite')queueMicrotask(()=>tx.abort());return tx}},{capture:true});return request}});await security.getByRole('button',{name:'关闭快速解锁'}).click();await page.getByText('关闭失败，当前浏览器快速解锁仍保持开启',{exact:true}).waitFor();await security.getByText('已开启').waitFor();assert.equal(await page.evaluate(async()=>(await import('/quick-unlock-device.mjs')).readQuickUnlock().then(Boolean)),true)}finally{await page.close();await browser.close()}});

test('服务器logout与IndexedDB删除双失败时同步锁库并明确提示',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();await installPrf(page);try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByText('已开启').waitFor();await security.getByRole('button',{name:'关闭',exact:true}).click();await page.route('**/api/logout',route=>route.abort('failed'));await page.evaluate(()=>{const original=indexedDB.open.bind(indexedDB);indexedDB.open=(...args)=>{const request=original(...args);request.addEventListener('success',()=>{const database=request.result,transaction=database.transaction.bind(database);database.transaction=(...txArgs)=>{const tx=transaction(...txArgs);if(txArgs[1]==='readwrite')queueMicrotask(()=>tx.abort());return tx}},{capture:true});return request}});await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'退出并锁定'}).click();await page.locator('#auth').waitFor({state:'visible'});await page.getByText('退出未完成：服务器会话和本机快速解锁材料均未撤销，请保持锁定并稍后重试',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.__vaultKeyPresent()),false);assert.equal(await page.locator('#vault').isHidden(),true)}finally{await page.close();await browser.close()}});

test('缺少recordId的旧撤销广播不得隐藏新记录入口',async()=>{const browser=await chromium.launch({headless:true}),context=await browser.newContext(),page=await context.newPage();await installPrf(page);try{const username=await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByText('已开启').waitFor();const peer=await context.newPage();await installPrf(peer);await peer.goto(base);await peer.getByRole('button',{name:'使用此设备快速解锁'}).waitFor();await peer.evaluate(username=>{const channel=new BroadcastChannel('pass-vault-sync');channel.postMessage({type:'quick-unlock-revoked',source:`legacy-peer-${crypto.randomUUID()}`,username,at:Date.now()});channel.close()},username);await peer.waitForTimeout(100);assert.equal(await peer.getByRole('button',{name:'使用此设备快速解锁'}).isVisible(),true);await peer.close()}finally{await context.close();await browser.close()}});

test('一个标签关闭快速解锁会立即撤销其他标签的内存入口',async()=>{const browser=await chromium.launch({headless:true}),context=await browser.newContext(),page=await context.newPage();await installPrf(page);try{await register(page);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const security=page.getByRole('dialog',{name:'安全中心'});await security.getByRole('button',{name:'开启快速解锁'}).click();const enable=page.getByRole('dialog',{name:'开启当前浏览器快速解锁'});await enable.getByLabel('当前主密码').fill('correct horse battery staple');await enable.getByRole('button',{name:'确认开启'}).click();await security.getByText('已开启').waitFor();const peer=await context.newPage();await installPrf(peer);await peer.goto(base);await peer.getByRole('button',{name:'使用此设备快速解锁'}).waitFor();await security.getByRole('button',{name:'关闭快速解锁'}).click();await peer.getByRole('button',{name:'使用此设备快速解锁'}).waitFor({state:'hidden'});assert.equal(await peer.getByRole('button',{name:'使用此设备快速解锁'}).isHidden(),true);await peer.close()}finally{await context.close();await browser.close()}});
