import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';
import { spawn } from 'node:child_process';
import { rm } from 'node:fs/promises';
import { TEST_INVITE_CODE, withTestInviteEnv } from './fixtures.mjs';

const port=4337,base=`http://localhost:${port}`,db=`/tmp/pass-vault-security-${process.pid}.sqlite`;let server;
async function start(){server=spawn(process.execPath,['apps/server/server.mjs'],{env:{...withTestInviteEnv(),PORT:String(port),DB_PATH:db,COOKIE_SECURE:'false',CLIENT_IP_HEADER:'x-test-client-ip'},stdio:['ignore','ignore','pipe']});await new Promise((resolve,reject)=>{let settled=false;const fail=error=>{if(settled)return;settled=true;reject(error)};server.once('exit',code=>fail(Error(`server exited before ready: ${code}`)));const deadline=Date.now()+5000;const ping=async()=>{if(settled)return;try{if((await fetch(base)).ok){settled=true;return resolve()}}catch{}if(Date.now()>deadline)return fail(Error('server timeout'));setTimeout(ping,80)};ping()})}
async function stop(){if(server?.exitCode===null){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r))}await rm(db,{force:true})}
async function register(page){await page.goto(base);await page.getByRole('button',{name:'创建新库'}).click();await page.getByLabel('邀请码').fill(TEST_INVITE_CODE);const username=`security-${Date.now()}-${Math.random()}`;await page.locator('[name=username]').fill(username);await page.getByLabel('主密码',{exact:true}).fill('correct horse battery staple');await page.getByRole('button',{name:'创建并进入'}).click();await page.locator('#vault').waitFor({state:'visible'});return username}
async function login(page,username){await page.goto(base);await page.locator('[name=username]').fill(username);await page.getByLabel('主密码',{exact:true}).fill('correct horse battery staple');await page.getByRole('button',{name:'登录并解锁'}).click();await page.locator('#vault').waitFor({state:'visible'})}

test.before(start);test.after(stop);

test('更多只提供安全中心入口，本机设置持久化且会话显示设备、IP和登录时间',async()=>{for(const launcher of [chromium,webkit]){const browser=await launcher.launch({headless:true}),context=await browser.newContext({viewport:{width:390,height:844},extraHTTPHeaders:{'x-test-client-ip':'198.51.100.44'}}),page=await context.newPage();try{await register(page);await page.getByRole('button',{name:'更多'}).click();assert.equal(await page.locator('#idle-lock-setting').count(),0);await page.getByRole('menuitem',{name:'安全中心'}).click();const dialog=page.getByRole('dialog',{name:'安全中心'});await dialog.waitFor();await dialog.getByLabel('自动锁定时间').selectOption('900000');await dialog.getByLabel('剪贴板自动清除').selectOption('15000');assert.deepEqual(await page.evaluate(()=>[localStorage.getItem('pass-vault-idle-lock-ms'),localStorage.getItem('pass-vault-clipboard-clear-ms')]),['900000','15000']);const current=dialog.locator('.security-session',{hasText:'当前设备'});await current.waitFor();assert.match(await current.textContent(),/198\.51\.100\.44/);assert.match(await current.textContent(),/登录时间/);assert.match(await current.textContent(),/(手机|平板|电脑|未知设备)/);const box=await dialog.boundingBox();assert.ok(box&&box.x>=8&&box.y>=8&&box.x+box.width<=398&&box.y+box.height<=852);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false)}finally{await context.close();await browser.close()}}});

test('安全中心显示 Passkey 会话的认证方式',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();try{await register(page);await page.route('**/api/sessions',async route=>{const response=await route.fetch(),value=await response.json();for(const session of value.sessions)session.authMethod='passkey';await route.fulfill({response,json:value})});await page.getByRole('button',{name:'更多'}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const current=page.locator('#security-center .security-session',{hasText:'当前设备'});await current.waitFor();assert.match(await current.textContent(),/Passkey 登录/)}finally{await page.close();await browser.close()}});

test('可单独注销其他会话并一键注销其他所有设备，当前会话始终保留',async()=>{const browser=await chromium.launch({headless:true}),a=await browser.newContext({extraHTTPHeaders:{'x-test-client-ip':'203.0.113.10'}}),b=await browser.newContext({extraHTTPHeaders:{'x-test-client-ip':'203.0.113.11'}}),c=await browser.newContext({extraHTTPHeaders:{'x-test-client-ip':'203.0.113.12'}}),p1=await a.newPage(),p2=await b.newPage(),p3=await c.newPage();try{const username=await register(p1);await login(p2,username);await p1.getByRole('button',{name:'更多'}).click();await p1.getByRole('menuitem',{name:'安全中心'}).click();const dialog=p1.getByRole('dialog',{name:'安全中心'});await dialog.locator('.security-session').filter({hasText:'203.0.113.11'}).getByRole('button',{name:'注销此会话'}).click();await p1.getByText('会话已注销',{exact:true}).waitFor();assert.equal((await p2.evaluate(()=>fetch('/api/session').then(r=>r.status))),401);await login(p3,username);await dialog.getByRole('button',{name:'刷新会话'}).click();await dialog.getByRole('button',{name:'注销其他所有设备'}).click();await p1.getByText('其他设备已注销',{exact:true}).waitFor();assert.equal((await p3.evaluate(()=>fetch('/api/session').then(r=>r.status))),401);assert.equal((await p1.evaluate(()=>fetch('/api/session').then(r=>r.status))),200);assert.equal(await dialog.locator('.security-session').count(),1);assert.match(await dialog.locator('.security-session').textContent(),/当前设备/)}finally{await a.close();await b.close();await c.close();await browser.close()}});

test('会话接口离线失败不阻止修改本机锁定和剪贴板设置',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();try{await register(page);await page.route('**/api/sessions',route=>route.abort());await page.getByRole('button',{name:'更多'}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const dialog=page.getByRole('dialog',{name:'安全中心'});await dialog.locator('#security-session-status').getByText(/无法加载会话/).waitFor();await dialog.getByLabel('自动锁定时间').selectOption('60000');await dialog.getByLabel('剪贴板自动清除').selectOption('0');assert.deepEqual(await page.evaluate(()=>[localStorage.getItem('pass-vault-idle-lock-ms'),localStorage.getItem('pass-vault-clipboard-clear-ms')]),['60000','0'])}finally{await page.close();await browser.close()}});

test('关闭安全中心后延迟注销响应不得刷新界面或显示提示',async()=>{const browser=await chromium.launch({headless:true}),a=await browser.newContext({extraHTTPHeaders:{'x-test-client-ip':'203.0.113.40'}}),b=await browser.newContext({extraHTTPHeaders:{'x-test-client-ip':'203.0.113.41'}}),p1=await a.newPage(),p2=await b.newPage();try{const username=await register(p1);await login(p2,username);let release;const delayed=new Promise(resolve=>{release=resolve});await p1.route('**/api/sessions/*',async route=>{if(route.request().method()==='DELETE'){await delayed;return route.continue()}return route.continue()});await p1.getByRole('button',{name:'更多'}).click();await p1.getByRole('menuitem',{name:'安全中心'}).click();const dialog=p1.getByRole('dialog',{name:'安全中心'});const revoke=dialog.locator('.security-session',{hasText:'203.0.113.41'}).getByRole('button',{name:'注销此会话'});await revoke.click();await dialog.getByRole('button',{name:'关闭'}).click();await dialog.waitFor({state:'hidden'});release();await p1.waitForTimeout(100);assert.equal(await p1.locator('#security-center').evaluate(el=>el.open),false);assert.equal(await p1.getByText('会话已注销',{exact:true}).count(),0)}finally{await a.close();await b.close();await browser.close()}});

test('剪贴板自动清除提示反映当前选择的时长',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();try{await register(page);await page.getByRole('button',{name:'更多'}).click();await page.getByRole('menuitem',{name:'安全中心'}).click();const dialog=page.getByRole('dialog',{name:'安全中心'}),hint=dialog.locator('#security-clipboard-hint');await dialog.getByLabel('剪贴板自动清除').selectOption('15000');assert.equal(await hint.textContent(),'复制密码后 15 秒自动清除（仅当剪贴板内容未变化）');await dialog.getByLabel('剪贴板自动清除').selectOption('0');assert.equal(await hint.textContent(),'不自动清除剪贴板内容')}finally{await page.close();await browser.close()}});

test('剪贴板计时只清除仍由密码库写入的值，不误清用户后来复制的内容',async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();await page.addInitScript(()=>{window.__CLIPBOARD_CLEAR_MS=40;window.__clip='';window.__writes=[];Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>{window.__clip=value;window.__writes.push(value)},readText:async()=>window.__clip}})});try{await register(page);await page.getByRole('button',{name:'+ 新建'}).click();await page.getByRole('dialog').getByRole('button',{name:'账号',exact:true}).click();const editor=page.locator('#editor');await editor.getByLabel('平台').fill('剪贴板测试');await editor.getByLabel('登录网址').fill('https://example.com');await editor.getByLabel('备注').fill('剪贴板计时验证');await editor.getByLabel('标签（逗号分隔）').fill('');await editor.locator('[name=credentialUsername]').fill('alice');await editor.locator('[name=credentialPassword]').fill('secret-value');await editor.getByRole('button',{name:'保存'}).click();await page.getByText('已保存',{exact:true}).waitFor();await page.locator('.item-card',{hasText:'剪贴板测试'}).click();const detail=page.locator('#detail');await detail.getByRole('button',{name:'复制密码'}).click();await page.waitForTimeout(70);assert.equal(await page.evaluate(()=>window.__clip),'');await detail.getByRole('button',{name:'复制密码'}).click();await page.evaluate(()=>{window.__clip='用户后来复制的内容'});await page.waitForTimeout(70);assert.equal(await page.evaluate(()=>window.__clip),'用户后来复制的内容')}finally{await page.close();await browser.close()}});
