import test from 'node:test';
import assert from 'node:assert/strict';
import { webkit } from 'playwright';
import { spawn } from 'node:child_process';
import { mkdir, rm } from 'node:fs/promises';
import { TEST_INVITE_CODE, withTestInviteEnv } from './fixtures.mjs';

const port=4397,base=`http://127.0.0.1:${port}`;let server,browser,dir;
test.before(async()=>{dir=`/tmp/pass-vault-totp-lifecycle-${process.pid}`;await rm(dir,{recursive:true,force:true});await mkdir(dir,{recursive:true});server=spawn(process.execPath,['apps/server/server.mjs'],{env:{...withTestInviteEnv(),PORT:String(port),DB_PATH:`${dir}/vault.sqlite`,ATTACHMENTS_DIR:`${dir}/attachments`,COOKIE_SECURE:'false'}});const deadline=Date.now()+6000;while(Date.now()<deadline){try{if((await fetch(base)).ok)break}catch{}await new Promise(r=>setTimeout(r,60))}browser=await webkit.launch({headless:true})});
test.after(async()=>{await browser?.close();if(server?.exitCode===null){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r))}await rm(dir,{recursive:true,force:true})});

async function register(page){await page.goto(base);await page.getByRole('button',{name:'创建新库'}).click();await page.getByLabel('邀请码').fill(TEST_INVITE_CODE);await page.getByLabel('用户名').fill(`totp-life-${Date.now()}`);await page.getByLabel('主密码',{exact:true}).fill('correct horse battery staple');await page.getByRole('button',{name:'创建并进入'}).click();await page.locator('#vault').waitFor({state:'visible'})}

test('TOTP完整接入加密分组、置顶、最近查看与回收站恢复',async()=>{const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),writes=[];page.on('request',request=>{if(request.method()==='PUT')writes.push(request.postData()||'')});try{await register(page);await page.locator('nav').getByRole('button',{name:'TOTP',exact:true}).click();await page.getByRole('button',{name:/管理TOTP分组/}).click();const groups=page.getByRole('dialog',{name:'分组',exact:true});await groups.getByLabel('新分组名称').fill('验证器');await groups.getByRole('button',{name:'创建分组'}).click();await groups.getByRole('button',{name:'验证器（0）',exact:true}).click();await groups.waitFor({state:'hidden'});assert.match(await page.getByRole('button',{name:/管理TOTP分组/}).textContent(),/验证器/);await page.getByRole('button',{name:'+ 新建'}).click();await page.locator('#picker').getByRole('button',{name:'TOTP',exact:true}).click();const editor=page.locator('#editor');await editor.getByLabel('账号',{exact:true}).fill('生命周期验证码');await editor.getByLabel('密钥',{exact:true}).fill('JBSWY3DPEHPK3PXP');await editor.getByLabel('分组').selectOption({label:'验证器'});await editor.getByRole('button',{name:'保存'}).click();await page.getByText('已保存',{exact:true}).waitFor();assert.equal(writes.some(body=>body.includes('验证器')||body.includes('生命周期验证码')||body.includes('JBSWY3DPEHPK3PXP')),false);const card=page.locator('.item-card',{hasText:'生命周期验证码'});await card.click();const detail=page.locator('#detail');await detail.getByRole('button',{name:'置顶'}).click();await page.getByText('已置顶',{exact:true}).waitFor();await detail.getByRole('button',{name:'← 返回'}).click().catch(()=>{});await page.waitForTimeout(300);assert.equal(await page.locator('.recents').getByRole('button',{name:/生命周期验证码/}).count(),1);await page.getByRole('button',{name:'生命周期验证码的更多操作',exact:true}).click();await page.getByRole('menuitem',{name:'删除'}).click();await page.getByRole('button',{name:'移入回收站'}).click();await page.getByText('已移入回收站',{exact:true}).waitFor();assert.equal(await page.locator('.item-card',{hasText:'生命周期验证码'}).count(),0);await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'回收站'}).click();const trash=page.getByRole('dialog',{name:'回收站'});const row=trash.locator('.trash-item',{hasText:'生命周期验证码'});assert.equal(await row.count(),1);await row.getByRole('button',{name:'恢复'}).click();await page.getByText('已恢复',{exact:true}).waitFor();await trash.getByRole('button',{name:'关闭'}).click();assert.equal(await page.locator('.item-card',{hasText:'生命周期验证码'}).count(),1)}finally{await page.close()}});
