import test from 'node:test';
import assert from 'node:assert/strict';
import { webkit, devices } from 'playwright';
import { spawn } from 'node:child_process';
import { mkdir, rm } from 'node:fs/promises';
import { TEST_INVITE_CODE, withTestInviteEnv } from './fixtures.mjs';

const port=4396,base=`http://127.0.0.1:${port}`;let server,browser,dir;
test.before(async()=>{dir=`/tmp/pass-vault-totp-${process.pid}`;await rm(dir,{recursive:true,force:true});await mkdir(dir,{recursive:true});server=spawn(process.execPath,['apps/server/server.mjs'],{env:{...withTestInviteEnv(),PORT:String(port),DB_PATH:`${dir}/vault.sqlite`,ATTACHMENTS_DIR:`${dir}/attachments`,COOKIE_SECURE:'false'}});const deadline=Date.now()+6000;while(Date.now()<deadline){try{if((await fetch(base)).ok)break}catch{}await new Promise(r=>setTimeout(r,60))}browser=await webkit.launch({headless:true})});
test.after(async()=>{await browser?.close();if(server?.exitCode===null){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r))}await rm(dir,{recursive:true,force:true})});

async function register(page){const username=`totp-${Date.now()}`;await page.goto(base);await page.getByRole('button',{name:'创建新库'}).click();await page.getByLabel('邀请码').fill(TEST_INVITE_CODE);await page.getByLabel('用户名').fill(username);await page.getByLabel('主密码',{exact:true}).fill('correct horse battery staple');await page.getByRole('button',{name:'创建并进入'}).click();await page.locator('#vault').waitFor({state:'visible'});return username}

test('iPhone独立TOTP菜单保存加密密钥并跨30秒窗口自动刷新验证码',async()=>{const context=await browser.newContext({...devices['iPhone 13'],reducedMotion:'reduce'}),page=await context.newPage(),writes=[],errors=[];page.on('request',request=>{if(request.method()==='PUT'&&request.url().includes('/api/entries/'))writes.push(request.postData()||'')});page.on('pageerror',error=>errors.push(error.message));try{await register(page);await page.evaluate(()=>{window.__TOTP_NOW=()=>59000});assert.deepEqual(await page.locator('nav [data-type]').allTextContents(),['账号','网站','笔记','TOTP','附件']);await page.getByRole('button',{name:'+ 新建'}).click();await page.locator('#picker').getByRole('button',{name:'TOTP',exact:true}).click();const editor=page.locator('#editor');await editor.getByLabel('账号',{exact:true}).fill('GitHub · alice@example.com');await editor.getByLabel('密钥',{exact:true}).fill('jbsw-y3dp ehpk3pxp');await editor.getByRole('button',{name:'保存'}).click();try{await page.getByText('已保存',{exact:true}).waitFor({timeout:10000})}catch{throw Error(`TOTP保存未完成: toast=${await page.locator('#toast').textContent()} editorOpen=${await page.locator('#editor').getAttribute('open')} errors=${errors.join('|')}`)};assert.equal(writes.some(body=>body.includes('JBSWY3DPEHPK3PXP')||body.includes('alice@example.com')),false,'账号和TOTP密钥不得出现在网络明文');const card=page.locator('.item-card',{hasText:'GitHub · alice@example.com'});await card.waitFor();const code=card.locator('[data-totp-code]');await page.waitForFunction(()=>/^\d{6}$/.test(document.querySelector('[data-totp-code]')?.textContent||''));const first=await code.textContent();await page.evaluate(async()=>{window.__TOTP_NOW=()=>89000;await window.__refreshTotp()});await page.waitForFunction(previous=>/^\d{6}$/.test(document.querySelector('[data-totp-code]')?.textContent||'')&&document.querySelector('[data-totp-code]').textContent!==previous,first);assert.notEqual(await code.textContent(),first);assert.match(await card.locator('[data-totp-remaining]').textContent(),/^\d+ 秒后刷新$/);await card.click();const detail=page.locator('#detail');assert.equal(await detail.getByText('JBSWY3DPEHPK3PXP',{exact:true}).count(),0,'详情不得直接显示密钥');await page.waitForFunction(()=>/^\d{6}$/.test(document.querySelector('#detail [data-totp-code]')?.textContent||''));assert.match(await detail.locator('[data-totp-code]').textContent(),/^\d{6}$/)}finally{await context.close()}});

test('iPhone复制TOTP在点击用户激活失效前写入剪贴板',async()=>{
 const context=await browser.newContext({...devices['iPhone 13'],reducedMotion:'reduce'});
 await context.addInitScript(()=>{
  window.__totpClipboardWrites=[];
  window.__totpCopyClicked=false;
  window.__totpSignedAfterCopyClick=false;
  document.addEventListener('click',event=>{
   if(event.target?.textContent==='复制验证码')window.__totpCopyClicked=true;
  },true);
  const sign=crypto.subtle.sign.bind(crypto.subtle);
  crypto.subtle.sign=async(...args)=>{
   if(window.__totpCopyClicked)window.__totpSignedAfterCopyClick=true;
   return sign(...args);
  };
  Object.defineProperty(navigator,'clipboard',{configurable:true,value:{
   writeText:async value=>{
    if(window.__totpSignedAfterCopyClick)throw Error('NotAllowedError');
    window.__totpClipboardWrites.push(value);
   }
  }});
  document.execCommand=()=>false;
 });
 const page=await context.newPage();
 try{
  await register(page);
  const account=await createTotp(page,'gesture-copy-review');
  await page.locator('.item-card',{hasText:account}).click();
  const detail=page.locator('#detail');
  await detail.waitFor({state:'visible'});
  await page.waitForFunction(()=>/^\d{6}$/.test(document.querySelector('#detail [data-totp-code]')?.textContent||''));
  const code=await detail.locator('[data-totp-code]').textContent();
  await detail.getByRole('button',{name:'复制验证码'}).click();
  await page.getByText('验证码已复制',{exact:true}).waitFor();
  assert.deepEqual(await page.evaluate(()=>window.__totpClipboardWrites),[code]);
 }finally{await context.close()}
});

async function createTotp(page,account='lock-review'){await page.locator('nav').getByRole('button',{name:'TOTP',exact:true}).click();await page.getByRole('button',{name:'+ 新建'}).click();await page.locator('#picker').getByRole('button',{name:'TOTP',exact:true}).click();const editor=page.locator('#editor');await editor.getByLabel('账号',{exact:true}).fill(account);await editor.getByLabel('密钥',{exact:true}).fill('JBSWY3DPEHPK3PXP');await editor.getByRole('button',{name:'保存'}).click();await page.getByText('已保存',{exact:true}).waitFor();await page.waitForFunction(()=>/^\d{6}$/.test(document.querySelector('[data-totp-code]')?.textContent||''));return account}

test('退出锁库在等待服务端前立即清除TOTP密钥、验证码和解密DOM',async()=>{const page=await browser.newPage({viewport:{width:390,height:844}});try{await register(page);const account=await createTotp(page);const card=page.locator('.item-card',{hasText:account});await card.getByRole('button',{name:new RegExp(`${account}的更多操作`)}).click();await card.getByRole('menuitem',{name:'编辑'}).click();const editor=page.locator('#editor');await editor.getByLabel('密钥',{exact:true}).fill('MZXW6YTBOI======');await page.route('**/api/logout',async route=>{await new Promise(r=>setTimeout(r,2000));await route.continue()});await page.evaluate(()=>document.querySelector('#logout').click());await page.waitForTimeout(100);const state=await page.evaluate(()=>({key:window.__vaultKeyPresent(),secret:document.querySelector('#fields input[name="secret"]')?.value||'',codes:[...document.querySelectorAll('[data-totp-code]')].map(x=>x.textContent),list:document.querySelector('#list').textContent,detail:document.querySelector('#detail').textContent,editorOpen:document.querySelector('#editor').open}));assert.deepEqual(state,{key:false,secret:'',codes:[],list:'',detail:'',editorOpen:false})}finally{await page.close()}});

test('改密成功在视图动画前立即通过统一锁库清除所有敏感DOM',async()=>{const page=await browser.newPage({viewport:{width:390,height:844}});try{await register(page);const account=await createTotp(page,'password-lock-review');await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'修改密码'}).click();const dialog=page.getByRole('dialog',{name:'修改主密码'});await dialog.locator('input[name="current"]').fill('correct horse battery staple');await dialog.locator('input[name="next"]').fill('another secure password');await dialog.locator('input[name="confirm"]').fill('another secure password');const response=page.waitForResponse(r=>r.url().endsWith('/api/change-password')&&r.ok());await dialog.getByRole('button',{name:'确认修改'}).click();await response;await page.waitForTimeout(50);const immediate=await page.evaluate(()=>({key:window.__vaultKeyPresent(),passwordDialogOpen:document.querySelector('#password-dialog').open,passwords:[...document.querySelectorAll('#password-form input')].map(x=>x.value).filter(Boolean),codes:document.querySelectorAll('[data-totp-code]').length,list:document.querySelector('#list').textContent,detail:document.querySelector('#detail').textContent}));assert.deepEqual(immediate,{key:false,passwordDialogOpen:false,passwords:[],codes:0,list:'',detail:''});await page.locator('#auth').waitFor({state:'visible'})}finally{await page.close()}});

test('锁库期间已启动的TOTP签名完成后不得写回已脱离文档的旧DOM',async()=>{const page=await browser.newPage({viewport:{width:390,height:844}});await page.addInitScript(()=>{const sign=crypto.subtle.sign.bind(crypto.subtle);let release;window.__delayTotpSign=false;window.__releaseTotpSign=()=>release?.();crypto.subtle.sign=async(...args)=>{if(window.__delayTotpSign)await new Promise(r=>{release=r});return sign(...args)}});try{await register(page);await createTotp(page,'pending-sign-review');await page.evaluate(()=>{const host=document.querySelector('.totp-card-code');window.__oldTotpHost=host;window.__oldTotpCode=host.querySelector('[data-totp-code]');window.__oldTotpCode.textContent='LOCKED';window.__delayTotpSign=true;window.__refreshTotp();window.__lastActivityAt(Date.now()-600000);window.__checkIdleDeadline()});await page.waitForFunction(()=>window.__vaultKeyPresent()===false);await page.evaluate(()=>window.__releaseTotpSign());await page.waitForTimeout(100);const state=await page.evaluate(()=>({connected:window.__oldTotpHost.isConnected,oldCode:window.__oldTotpCode.textContent,codes:document.querySelectorAll('[data-totp-code]').length,list:document.querySelector('#list').textContent,detail:document.querySelector('#detail').textContent}));assert.deepEqual(state,{connected:false,oldCode:'LOCKED',codes:0,list:'',detail:''})}finally{await page.close()}});

test('锁库后剪贴板异步失败不得通过fallback复制旧验证码',async()=>{const page=await browser.newPage({viewport:{width:390,height:844}});await page.addInitScript(()=>{let reject;window.__clipboardPending=false;window.__fallbackCopies=0;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>{window.__clipboardPending=true;return new Promise((_,r)=>{reject=r})}}});document.execCommand=command=>{if(command==='copy')window.__fallbackCopies++;return true};window.__rejectClipboard=()=>reject?.(Error('denied'))});try{await register(page);const account=await createTotp(page,'copy-lock-review');await page.locator('.item-card',{hasText:account}).click();await page.waitForFunction(()=>/^\d{6}$/.test(document.querySelector('#detail [data-totp-code]')?.textContent||''));await page.locator('#detail').getByRole('button',{name:'复制验证码'}).click({noWaitAfter:true});await page.waitForFunction(()=>window.__clipboardPending===true);await page.evaluate(()=>{window.__lastActivityAt(Date.now()-600000);window.__checkIdleDeadline()});await page.waitForFunction(()=>window.__vaultKeyPresent()===false);await page.evaluate(()=>window.__rejectClipboard());await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.__fallbackCopies),0)}finally{await page.close()}});

test('锁库同步撤销附件预览URL并清空文件、重命名和分组敏感状态',async()=>{const page=await browser.newPage({viewport:{width:390,height:844}});await page.addInitScript(()=>{const revoke=URL.revokeObjectURL.bind(URL);window.__revokedUrls=[];URL.revokeObjectURL=url=>{window.__revokedUrls.push(url);return revoke(url)}});try{await register(page);await page.evaluate(()=>{const preview=document.createElement('img');preview.src='blob:http://127.0.0.1/sensitive-preview';preview.alt='private-file.png';document.querySelector('#preview-body').append(preview);document.querySelector('#rename-form [name="name"]').value='private-file.png';document.querySelector('#groups-form [name="newGroup"]').value='Private Group';const dt=new DataTransfer();dt.items.add(new File(['secret'],'private-file.txt',{type:'text/plain'}));document.querySelector('#attachment-form [name="file"]').files=dt.files;window.__trackObjectUrl('blob:http://127.0.0.1/sensitive-preview');window.__lastActivityAt(Date.now()-600000);window.__checkIdleDeadline()});await page.waitForFunction(()=>window.__vaultKeyPresent()===false);const state=await page.evaluate(()=>({preview:document.querySelector('#preview-body').textContent+document.querySelector('#preview-body').children.length,rename:document.querySelector('#rename-form [name="name"]').value,group:document.querySelector('#groups-form [name="newGroup"]').value,files:document.querySelector('#attachment-form [name="file"]').files.length,revoked:window.__revokedUrls}));assert.deepEqual(state,{preview:'0',rename:'',group:'',files:0,revoked:['blob:http://127.0.0.1/sensitive-preview']})}finally{await page.close()}});

test('锁库关闭条目菜单并释放对已解密旧卡片的内部引用',async()=>{const page=await browser.newPage({viewport:{width:390,height:844}});try{await register(page);const account=await createTotp(page,'menu-lock-review'),card=page.locator('.item-card',{hasText:account}),more=card.getByRole('button',{name:new RegExp(`${account}的更多操作`)});await more.click();await page.evaluate(()=>{window.__oldMenuCard=document.querySelector('.item-card');window.__oldMenu=document.querySelector('.item-menu:not([hidden])');window.__lastActivityAt(Date.now()-600000);window.__checkIdleDeadline()});await page.waitForFunction(()=>window.__vaultKeyPresent()===false);const state=await page.evaluate(()=>({internal:window.__itemMenuOpen(),connected:window.__oldMenuCard.isConnected,hidden:window.__oldMenu.hidden,expanded:window.__oldMenu.previousElementSibling.getAttribute('aria-expanded'),list:document.querySelector('#list').textContent}));assert.deepEqual(state,{internal:false,connected:false,hidden:true,expanded:'false',list:''})}finally{await page.close()}});

test('保存TOTP响应在锁库后返回不得重新写入明文内存或DOM',async()=>{const page=await browser.newPage({viewport:{width:390,height:844}});let release,putPending;const pending=new Promise(resolve=>{putPending=resolve});try{await register(page);await page.route('**/api/entries/**',async route=>{if(route.request().method()==='PUT'){putPending();await new Promise(resolve=>{release=resolve});await route.continue()}else await route.continue()});await page.locator('nav').getByRole('button',{name:'TOTP',exact:true}).click();await page.getByRole('button',{name:'+ 新建'}).click();await page.locator('#picker').getByRole('button',{name:'TOTP',exact:true}).click();const editor=page.locator('#editor');await editor.getByLabel('账号',{exact:true}).fill('delayed-save-secret');await editor.getByLabel('密钥',{exact:true}).fill('JBSWY3DPEHPK3PXP');await editor.getByRole('button',{name:'保存'}).click();await pending;await page.evaluate(()=>{window.__lastActivityAt(Date.now()-600000);window.__checkIdleDeadline()});await page.waitForFunction(()=>window.__vaultKeyPresent()===false);release();await page.waitForTimeout(300);const state=await page.evaluate(()=>({key:window.__vaultKeyPresent(),list:document.querySelector('#list').textContent,detail:document.querySelector('#detail').textContent,codes:document.querySelectorAll('[data-totp-code]').length}));assert.deepEqual(state,{key:false,list:'',detail:'',codes:0})}finally{release?.();await page.close()}});

test('跨标签刷新解密中锁库不得提交局部明文或重建DOM',async()=>{const page=await browser.newPage({viewport:{width:390,height:844}});await page.addInitScript(()=>{const decrypt=crypto.subtle.decrypt.bind(crypto.subtle);let release;window.__delayPeerDecrypt=false;window.__peerDecryptPending=false;window.__releasePeerDecrypt=()=>release?.();crypto.subtle.decrypt=async(...args)=>{if(window.__delayPeerDecrypt){window.__peerDecryptPending=true;await new Promise(resolve=>{release=resolve})}return decrypt(...args)}});try{const username=await register(page);await createTotp(page,'peer-refresh-secret');await page.evaluate(user=>{window.__delayPeerDecrypt=true;const channel=new BroadcastChannel('pass-vault-sync');channel.postMessage({type:'update',source:'peer-test',username:user,at:Date.now()});channel.close()},username);await page.waitForFunction(()=>window.__peerDecryptPending===true);await page.evaluate(()=>{window.__lastActivityAt(Date.now()-600000);window.__checkIdleDeadline()});await page.waitForFunction(()=>window.__vaultKeyPresent()===false);await page.evaluate(()=>window.__releasePeerDecrypt());await page.waitForTimeout(300);const state=await page.evaluate(()=>({key:window.__vaultKeyPresent(),list:document.querySelector('#list').textContent,detail:document.querySelector('#detail').textContent,codes:document.querySelectorAll('[data-totp-code]').length}));assert.deepEqual(state,{key:false,list:'',detail:'',codes:0})}finally{await page.evaluate(()=>window.__releasePeerDecrypt?.()).catch(()=>{});await page.close()}});

test('登录加载解密中收到跨标签锁定不得重新显示保险库',async()=>{const page=await browser.newPage({viewport:{width:390,height:844}});await page.addInitScript(()=>{const decrypt=crypto.subtle.decrypt.bind(crypto.subtle);let release;window.__delayLoginDecrypt=false;window.__loginDecryptPending=false;window.__releaseLoginDecrypt=()=>release?.();crypto.subtle.decrypt=async(...args)=>{if(window.__delayLoginDecrypt){window.__loginDecryptPending=true;await new Promise(resolve=>{release=resolve})}return decrypt(...args)}});try{const username=await register(page);await createTotp(page,'login-lock-secret');await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'退出并锁定'}).click();await page.locator('#auth').waitFor({state:'visible'});await page.evaluate(()=>{window.__delayLoginDecrypt=true});await page.locator('#auth-form input[name="username"]').fill(username);await page.getByLabel('主密码',{exact:true}).fill('correct horse battery staple');await page.getByRole('button',{name:'登录并解锁'}).click();await page.waitForFunction(()=>window.__loginDecryptPending===true);await page.evaluate(user=>{const channel=new BroadcastChannel('pass-vault-sync');channel.postMessage({type:'lock',source:'peer-login-lock',username:user,at:Date.now()});channel.close()},username);await page.waitForFunction(()=>window.__vaultKeyPresent()===false);await page.evaluate(()=>window.__releaseLoginDecrypt());await page.waitForTimeout(500);const state=await page.evaluate(()=>({key:window.__vaultKeyPresent(),authHidden:document.querySelector('#auth').hidden,vaultHidden:document.querySelector('#vault').hidden,list:document.querySelector('#list').textContent}));assert.deepEqual(state,{key:false,authHidden:false,vaultHidden:true,list:''})}finally{await page.evaluate(()=>window.__releaseLoginDecrypt?.()).catch(()=>{});await page.close()}});

test('自动清理DELETE在锁库后返回不得广播旧会话更新',async()=>{const page=await browser.newPage({viewport:{width:390,height:844}});let release,deletePending;const pending=new Promise(resolve=>{deletePending=resolve});try{const username=await register(page),account=await createTotp(page,'expired-cleanup-secret');await page.evaluate(()=>{Date.now=()=>1000000000000});await page.getByRole('button',{name:`${account}的更多操作`,exact:true}).click();await page.getByRole('menuitem',{name:'删除'}).click();await page.getByRole('button',{name:'移入回收站'}).click();await page.getByText('已移入回收站',{exact:true}).waitFor();await page.evaluate(()=>{Date.now=()=>1000000000000+31*24*60*60*1000;window.__peerUpdates=[];const channel=new BroadcastChannel('pass-vault-sync');channel.onmessage=e=>{if(e.data?.type==='update')window.__peerUpdates.push(e.data)}});await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'退出并锁定'}).click();await page.locator('#auth').waitFor({state:'visible'});await page.route('**/api/entries/**',async route=>{if(route.request().method()==='DELETE'){deletePending();await new Promise(resolve=>{release=resolve});await route.continue()}else await route.continue()});await page.locator('#auth-form input[name="username"]').fill(username);await page.getByLabel('主密码',{exact:true}).fill('correct horse battery staple');await page.getByRole('button',{name:'登录并解锁'}).click();await pending;await page.evaluate(()=>{window.__lastActivityAt(Date.now()-600000);window.__checkIdleDeadline()});await page.waitForFunction(()=>window.__vaultKeyPresent()===false);await page.evaluate(()=>{window.__peerUpdates=[]});release();await page.waitForTimeout(300);assert.deepEqual(await page.evaluate(()=>window.__peerUpdates),[])}finally{release?.();await page.close()}});

async function moveTotpToTrash(page,account){await page.getByRole('button',{name:`${account}的更多操作`,exact:true}).click();await page.getByRole('menuitem',{name:'删除'}).click();await page.getByRole('button',{name:'移入回收站'}).click();await page.getByText('已移入回收站',{exact:true}).waitFor();await page.getByRole('button',{name:'更多',exact:true}).click();await page.getByRole('menuitem',{name:'回收站'}).click()}

async function installUpdateProbe(page){await page.evaluate(()=>{window.__peerUpdates=[];const channel=new BroadcastChannel('pass-vault-sync');channel.onmessage=e=>{if(e.data?.type==='update')window.__peerUpdates.push(e.data)}})}

test('手动永久删除响应在锁库后返回不得误报成功或广播',async()=>{const page=await browser.newPage({viewport:{width:390,height:844}});let release,deletePending;const pending=new Promise(resolve=>{deletePending=resolve});try{await register(page);const account=await createTotp(page,'manual-delete-lock-secret');await moveTotpToTrash(page,account);await installUpdateProbe(page);await page.route('**/api/entries/**',async route=>{if(route.request().method()==='DELETE'){deletePending();await new Promise(resolve=>{release=resolve});await route.continue()}else await route.continue()});await page.getByRole('dialog',{name:'回收站'}).getByRole('button',{name:`彻底删除 ${account}`}).click();await page.getByRole('dialog',{name:'确认彻底删除'}).getByRole('button',{name:'彻底删除'}).click();await pending;await page.evaluate(()=>{window.__lastActivityAt(Date.now()-600000);window.__checkIdleDeadline()});await page.waitForFunction(()=>window.__vaultKeyPresent()===false);await page.evaluate(()=>{window.__peerUpdates=[]});release();await page.waitForTimeout(300);assert.deepEqual(await page.evaluate(()=>window.__peerUpdates),[]);assert.notEqual(await page.locator('#toast').textContent(),'已彻底删除')}finally{release?.();await page.close()}});

test('清空回收站响应在锁库后返回不得误报成功或广播',async()=>{const page=await browser.newPage({viewport:{width:390,height:844}});let release,deletePending;const pending=new Promise(resolve=>{deletePending=resolve});try{await register(page);const account=await createTotp(page,'empty-trash-lock-secret');await moveTotpToTrash(page,account);await installUpdateProbe(page);await page.route('**/api/entries/**',async route=>{if(route.request().method()==='DELETE'){deletePending();await new Promise(resolve=>{release=resolve});await route.continue()}else await route.continue()});const trash=page.getByRole('dialog',{name:'回收站'});await trash.getByRole('button',{name:'清空回收站'}).click();await page.getByRole('dialog',{name:'确认清空回收站'}).getByRole('button',{name:'确认清空'}).click();await pending;await page.evaluate(()=>{window.__lastActivityAt(Date.now()-600000);window.__checkIdleDeadline()});await page.waitForFunction(()=>window.__vaultKeyPresent()===false);await page.evaluate(()=>{window.__peerUpdates=[]});release();await page.waitForTimeout(300);assert.deepEqual(await page.evaluate(()=>window.__peerUpdates),[]);assert.notEqual(await page.locator('#toast').textContent(),'回收站已清空')}finally{release?.();await page.close()}});
