import test from 'node:test';
import assert from 'node:assert/strict';
import { webkit, devices } from 'playwright';
import { spawn } from 'node:child_process';
import { mkdir, rm } from 'node:fs/promises';
import { TEST_INVITE_CODE, withTestInviteEnv } from './fixtures.mjs';

const port=4396,base=`http://127.0.0.1:${port}`;let server,browser,dir;
test.before(async()=>{dir=`/tmp/pass-vault-totp-${process.pid}`;await rm(dir,{recursive:true,force:true});await mkdir(dir,{recursive:true});server=spawn(process.execPath,['apps/server/server.mjs'],{env:{...withTestInviteEnv(),PORT:String(port),DB_PATH:`${dir}/vault.sqlite`,ATTACHMENTS_DIR:`${dir}/attachments`,COOKIE_SECURE:'false'}});const deadline=Date.now()+6000;while(Date.now()<deadline){try{if((await fetch(base)).ok)break}catch{}await new Promise(r=>setTimeout(r,60))}browser=await webkit.launch({headless:true})});
test.after(async()=>{await browser?.close();if(server?.exitCode===null){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r))}await rm(dir,{recursive:true,force:true})});

async function register(page){await page.goto(base);await page.getByRole('button',{name:'创建新库'}).click();await page.getByLabel('邀请码').fill(TEST_INVITE_CODE);await page.getByLabel('用户名').fill(`totp-${Date.now()}`);await page.getByLabel('主密码',{exact:true}).fill('correct horse battery staple');await page.getByRole('button',{name:'创建并进入'}).click();await page.locator('#vault').waitFor({state:'visible'})}

test('iPhone独立TOTP菜单保存加密密钥并自动刷新验证码',async()=>{const context=await browser.newContext({...devices['iPhone 13'],reducedMotion:'reduce'}),page=await context.newPage(),writes=[],errors=[];page.on('request',request=>{if(request.method()==='PUT'&&request.url().includes('/api/entries/'))writes.push(request.postData()||'')});page.on('pageerror',error=>errors.push(error.message));try{await register(page);assert.deepEqual(await page.locator('nav [data-type]').allTextContents(),['账号','网站','笔记','TOTP','附件']);await page.getByRole('button',{name:'+ 新建'}).click();await page.locator('#picker').getByRole('button',{name:'TOTP',exact:true}).click();const editor=page.locator('#editor');await editor.getByLabel('账号',{exact:true}).fill('GitHub · alice@example.com');await editor.getByLabel('密钥',{exact:true}).fill('jbsw-y3dp ehpk3pxp');await editor.getByRole('button',{name:'保存'}).click();try{await page.getByText('已保存',{exact:true}).waitFor({timeout:10000})}catch{throw Error(`TOTP保存未完成: toast=${await page.locator('#toast').textContent()} editorOpen=${await page.locator('#editor').getAttribute('open')} errors=${errors.join('|')}`)};assert.equal(writes.some(body=>body.includes('JBSWY3DPEHPK3PXP')||body.includes('alice@example.com')),false,'账号和TOTP密钥不得出现在网络明文');const card=page.locator('.item-card',{hasText:'GitHub · alice@example.com'});await card.waitFor();const code=card.locator('[data-totp-code]');await code.waitFor();await page.waitForFunction(()=>/^\d{6}$/.test(document.querySelector('[data-totp-code]')?.textContent||''));const first=await code.textContent();assert.match(first,/^\d{6}$/);assert.match(await card.locator('[data-totp-remaining]').textContent(),/^\d+ 秒后刷新$/);await card.click();const detail=page.locator('#detail');assert.equal(await detail.getByText('JBSWY3DPEHPK3PXP',{exact:true}).count(),0,'详情不得直接显示密钥');await page.waitForFunction(()=>/^\d{6}$/.test(document.querySelector('#detail [data-totp-code]')?.textContent||''));assert.match(await detail.locator('[data-totp-code]').textContent(),/^\d{6}$/);await page.evaluate(async()=>{window.__TOTP_NOW=()=>30000;await window.__refreshTotp?.()});const at30=await detail.locator('[data-totp-code]').textContent();await page.evaluate(async()=>{window.__TOTP_NOW=()=>60000;await window.__refreshTotp?.()});const at60=await detail.locator('[data-totp-code]').textContent();assert.notEqual(at30,at60,'跨30秒窗口应自动生成新验证码');assert.deepEqual(errors,[])}finally{await context.close()}});
