import type { Env } from './runtime.ts';

const decodePart=(value:string)=>{try{const normalized=value.replaceAll('-','+').replaceAll('_','/'),bytes=Uint8Array.from(atob(normalized+'='.repeat((4-normalized.length%4)%4)),c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes)) as Record<string,unknown>}catch{return null}};
const ACCESS_JWKS_TTL_MS=5*60*1000,jwksCache=new Map<string,{keys:Record<string,unknown>[];expiresAt:number}>();
async function dynamicAccessKeys(issuer:string,force=false){const cached=jwksCache.get(issuer);if(!force&&cached&&cached.expiresAt>Date.now())return cached.keys;const response=await fetch(new URL('/cdn-cgi/access/certs',issuer));if(!response.ok)throw new Error('jwks_unavailable');const parsed=await response.json() as {keys?:unknown};if(!parsed||!Array.isArray(parsed.keys))throw new Error('jwks_invalid');const keys=parsed.keys.filter((key):key is Record<string,unknown>=>key!==null&&typeof key==='object');jwksCache.set(issuer,{keys,expiresAt:Date.now()+ACCESS_JWKS_TTL_MS});return keys}
export async function accessIdentity(req:Request,env:Env){
 const token=req.headers.get('cf-access-jwt-assertion');if(!token||!env.ACCESS_ISSUER||!env.ACCESS_AUD)return null;
 const parts=token.split('.');if(parts.length!==3)return null;const header=decodePart(parts[0]),payload=decodePart(parts[1]);if(!header||!payload||header.alg!=='RS256'||typeof header.kid!=='string')return null;
 const now=Math.floor(Date.now()/1000),aud=payload.aud,issuer=String(env.ACCESS_ISSUER).replace(/\/$/,'');if(payload.iss!==issuer||(typeof aud==='string'?aud!==env.ACCESS_AUD:!Array.isArray(aud)||!aud.some(value=>value===env.ACCESS_AUD))||typeof payload.exp!=='number'||!Number.isFinite(payload.exp)||payload.exp<=now||(payload.nbf!==undefined&&(typeof payload.nbf!=='number'||!Number.isFinite(payload.nbf)||payload.nbf>now)))return null;
 let keys:Record<string,unknown>[];try{if(env.ACCESS_JWKS){const parsed=JSON.parse(env.ACCESS_JWKS);if(!parsed||!Array.isArray(parsed.keys))return null;keys=parsed.keys}else keys=await dynamicAccessKeys(issuer)}catch{return null}
 const keyId=header.kid,findKey=()=>keys.find(key=>key!==null&&typeof key==='object'&&key.kid===keyId&&key.kty==='RSA'&&(key.alg===undefined||key.alg==='RS256')&&(key.use===undefined||key.use==='sig')&&(key.key_ops===undefined||(Array.isArray(key.key_ops)&&key.key_ops.length===1&&key.key_ops[0]==='verify')));let jwk=findKey();if(!jwk&&!env.ACCESS_JWKS)try{keys=await dynamicAccessKeys(issuer,true);jwk=findKey()}catch{return null}if(!jwk)return null;
 try{const key=await crypto.subtle.importKey('jwk',jwk as JsonWebKey,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']),signature=Uint8Array.from(atob(parts[2].replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-parts[2].length%4)%4)),c=>c.charCodeAt(0)),valid=await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,signature,new TextEncoder().encode(parts[0]+'.'+parts[1]));if(!valid||typeof payload.email!=='string')return null;return payload.email.trim().toLowerCase()}catch{return null}
}
