type D1Result={results?:Record<string,unknown>[]};
type Stmt={all:()=>Promise<D1Result>;first:<T=Record<string,unknown>>()=>Promise<T|null>};
type Env={DB:{prepare:(sql:string)=>Stmt};ATTACHMENTS:{list:(o?:{cursor?:string;limit?:number})=>Promise<{objects:{size:number}[];truncated:boolean;cursor?:string}>};ADMIN_EMAIL:string;CF_VERSION_METADATA?:{id?:string}};

const headers={
 'cache-control':'no-store, max-age=0','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; script-src 'self'; connect-src 'self'; img-src 'self' data:; base-uri 'none'; frame-ancestors 'none'; form-action 'none'",
 'x-content-type-options':'nosniff','referrer-policy':'no-referrer','permissions-policy':'camera=(), microphone=(), geolocation=()','x-frame-options':'DENY'
};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...headers,'content-type':'application/json; charset=utf-8'}});
const escapeHtml=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));

const page=()=>`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light dark"><title>密码库管理</title><style>
:root{font-family:ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#18201d;background:#f3f5f4;--card:#ffffffd9;--line:#d9dfdc;--muted:#69736f;--accent:#13795b;--soft:#e7f4ee}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:linear-gradient(180deg,#f8faf9,#eef2f0);padding:env(safe-area-inset-top) 16px env(safe-area-inset-bottom)}main{max-width:1080px;margin:auto;padding:32px 0 48px}header{display:flex;justify-content:space-between;align-items:flex-end;gap:16px;margin-bottom:22px}.eyebrow{color:var(--accent);font-size:12px;font-weight:800;letter-spacing:.15em}h1{font-size:clamp(27px,5vw,42px);margin:7px 0 5px}.muted{color:var(--muted);font-size:14px}.badge{padding:8px 12px;border:1px solid #b8d7ca;background:var(--soft);color:#0f684d;border-radius:999px;font-size:13px;font-weight:700;white-space:nowrap}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{background:var(--card);border:1px solid var(--line);border-radius:18px;padding:18px;box-shadow:0 12px 32px #1c292210;backdrop-filter:blur(16px)}.metric b{display:block;font-size:25px;margin-top:8px}.section{margin-top:18px}.section h2{font-size:18px;margin:0 0 14px}.users{display:grid;gap:10px}.user{display:grid;grid-template-columns:minmax(130px,1.2fr) repeat(5,minmax(85px,1fr));gap:12px;align-items:center;padding:14px;border:1px solid var(--line);border-radius:14px;background:#fff}.user strong{overflow-wrap:anywhere}.label{font-size:11px;color:var(--muted);display:block;margin-bottom:3px}.status{color:var(--accent);font-weight:700}.error{color:#a12d2d;background:#fff0f0;border:1px solid #efc5c5;padding:14px;border-radius:14px}.skeleton{animation:pulse 1.2s infinite alternate}@keyframes pulse{to{opacity:.45}}@media(max-width:760px){main{padding-top:22px}.grid{grid-template-columns:repeat(2,1fr)}header{align-items:flex-start;flex-direction:column}.user{grid-template-columns:1fr 1fr}.user>div:first-child{grid-column:1/-1}}@media(prefers-color-scheme:dark){:root{color:#edf4f0;background:#090c0b;--card:#141917e8;--line:#29322e;--muted:#99a69f;--soft:#15372b}body{background:linear-gradient(180deg,#090c0b,#101512)}.user{background:#111614}}
</style><script src="/app.js" defer></script></head><body><main><header><div><div class="eyebrow">PASS VAULT · READ ONLY</div><h1>Cloudflare 管理面板</h1><div class="muted">只展示账户元数据和资源使用情况，不读取密码库内容。</div></div><span class="badge">只读模式</span></header><div id="app"><div class="card skeleton">正在读取安全统计…</div></div></main></body></html>`;
const script=`const f=n=>new Intl.NumberFormat('zh-CN').format(Number(n)||0),date=n=>n?new Date(n).toLocaleString('zh-CN',{hour12:false}):'从未';async function load(){const root=document.querySelector('#app');try{const r=await fetch('/api/overview',{credentials:'same-origin'});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json(),m=[['用户',d.summary.users],['加密条目',d.summary.entries],['附件',d.summary.attachments],['附件占用',f(d.summary.attachmentBytes)+' B'],['R2 对象',d.resources.r2.objects],['R2 存储',f(d.resources.r2.bytes)+' B'],['活跃会话',d.summary.activeSessions],['D1 大小',f(d.resources.d1.bytes)+' B']];root.innerHTML='<section class="grid">'+m.map(x=>'<div class="card metric"><span class="muted">'+x[0]+'</span><b>'+(/ B$/.test(String(x[1]))?x[1]:f(x[1]))+'</b></div>').join('')+'</section><section class="card section"><h2>用户</h2><div class="users">'+d.users.map(u=>'<article class="user"><div><span class="label">用户名</span><strong>'+u.username+'</strong></div><div><span class="label">创建时间</span>'+date(u.createdAt)+'</div><div><span class="label">条目</span>'+f(u.entries)+'</div><div><span class="label">附件</span>'+f(u.attachments)+'</div><div><span class="label">活跃会话</span>'+f(u.activeSessions)+'</div><div><span class="label">最近认证</span><span class="status">'+(u.lastAuthMethod==='passkey'?'Passkey':u.lastAuthMethod==='password'?'密码':'无')+'</span><br><small class="muted">'+date(u.lastSeenAt)+'</small></div></article>').join('')+'</div></section><section class="card section"><h2>运行状态</h2><div class="grid"><div><span class="label">Worker版本</span><code>'+d.runtime.version+'</code></div><div><span class="label">待删R2</span>'+f(d.summary.pendingDeletions)+'</div><div><span class="label">在途上传</span>'+f(d.summary.inflightUploads)+'</div><div><span class="label">备份锁</span>'+f(d.summary.backupLocks)+'</div></div></section>'}catch(e){root.innerHTML='<div class="error">读取失败，请确认Cloudflare Access登录状态后刷新。</div>'}}load();`;

async function r2Stats(bucket:Env['ATTACHMENTS']){let cursor: string|undefined,objects=0,bytes=0,rounds=0;do{const page=await bucket.list({cursor,limit:1000});for(const o of page.objects){objects++;bytes+=Number(o.size)||0}cursor=page.truncated?page.cursor:undefined;rounds++}while(cursor&&rounds<20);return{objects,bytes,truncated:Boolean(cursor)}}
async function overview(env:Env){
 const [summaryResult,usersResult,r2]=await Promise.all([
  env.DB.prepare(`SELECT (SELECT COUNT(*) FROM users) users,(SELECT COUNT(*) FROM entries) entries,(SELECT COUNT(*) FROM attachments) attachments,(SELECT COALESCE(SUM(ciphertext_size),0) FROM attachments) attachment_bytes,(SELECT COUNT(*) FROM sessions WHERE expires_at>unixepoch()*1000) active_sessions,(SELECT COUNT(*) FROM pending_r2_deletions) pending_deletions,(SELECT COUNT(*) FROM r2_inflight_uploads) inflight_uploads,(SELECT COUNT(*) FROM backup_import_locks WHERE expires_at>unixepoch()*1000) backup_locks,(SELECT COALESCE(SUM(class_a),0) FROM r2_monthly_usage) class_a,(SELECT COALESCE(SUM(class_b),0) FROM r2_monthly_usage) class_b`).first<Record<string,number>>(),
  env.DB.prepare(`SELECT u.username,u.created_at,u.password_iterations,(SELECT COUNT(*) FROM entries e WHERE e.user_id=u.id) entry_count,(SELECT COUNT(*) FROM attachments a WHERE a.user_id=u.id) attachment_count,(SELECT COALESCE(SUM(a.ciphertext_size),0) FROM attachments a WHERE a.user_id=u.id) attachment_bytes,(SELECT COUNT(*) FROM sessions s WHERE s.user_id=u.id AND s.expires_at>unixepoch()*1000) active_sessions,(SELECT MAX(s.last_seen_at) FROM sessions s WHERE s.user_id=u.id) last_seen_at,(SELECT auth_method FROM sessions sx WHERE sx.user_id=u.id ORDER BY COALESCE(sx.last_seen_at,sx.created_at,0) DESC LIMIT 1) last_auth_method,(SELECT COUNT(*) FROM passkey_credentials p WHERE p.user_id=u.id) passkey_count FROM users u ORDER BY u.created_at`).all(),r2Stats(env.ATTACHMENTS)]);
 const s=summaryResult||{} as Record<string,number>;const users=(usersResult.results||[]).map(x=>({username:escapeHtml(String(x.username||'')),createdAt:Number(x.created_at)||0,entries:Number(x.entry_count)||0,attachments:Number(x.attachment_count)||0,attachmentBytes:Number(x.attachment_bytes)||0,activeSessions:Number(x.active_sessions)||0,lastSeenAt:Number(x.last_seen_at)||0,lastAuthMethod:['password','passkey'].includes(String(x.last_auth_method))?String(x.last_auth_method):'unknown',passkeys:Number(x.passkey_count)||0,passwordPolicy:Number(x.password_iterations)===100000?'Cloudflare兼容':'需检查'}));
 return{generatedAt:Date.now(),summary:{users:Number(s.users)||0,entries:Number(s.entries)||0,attachments:Number(s.attachments)||0,attachmentBytes:Number(s.attachment_bytes)||0,activeSessions:Number(s.active_sessions)||0,pendingDeletions:Number(s.pending_deletions)||0,inflightUploads:Number(s.inflight_uploads)||0,backupLocks:Number(s.backup_locks)||0},resources:{d1:{bytes:Number(s.db_bytes)||0},r2:{...r2,classA:Number(s.class_a)||0,classB:Number(s.class_b)||0}},users,runtime:{version:env.CF_VERSION_METADATA?.id||'unknown'}};
}
export default{async fetch(req:Request,env:Env){
 if(!['GET','HEAD'].includes(req.method))return json({error:'method_not_allowed'},405);
 const email=(req.headers.get('cf-access-authenticated-user-email')||'').trim().toLowerCase(),admin=(env.ADMIN_EMAIL||'').trim().toLowerCase();
 if(!email)return json({error:'access_required'},401);if(!admin||email!==admin)return json({error:'forbidden'},403);
 const path=new URL(req.url).pathname;let response:Response;
 if(path==='/api/overview')response=json(await overview(env));else if(path==='/app.js')response=new Response(script,{headers:{...headers,'content-type':'text/javascript; charset=utf-8'}});else if(path==='/'||path==='/index.html')response=new Response(page(),{headers:{...headers,'content-type':'text/html; charset=utf-8'}});else response=json({error:'not_found'},404);
 return req.method==='HEAD'?new Response(null,{status:response.status,headers:response.headers}):response;
}};
