export const TYPES=['account','website','note','totp','custom'];
export const GROUP_TYPES=['account','website','note','totp','attachment','custom'];
export const SETTINGS_ID='settings_registry';
export const RECENTS_ID='recents_registry';
export const TAGS_ID='tags_registry';
export const CUSTOM_TEMPLATES_ID='custom_templates_registry';
export const RECOVERY_ID='recovery_registry';
export const MARKERS_ID='markers_registry';
export const SETTINGS_IDS=Object.freeze([SETTINGS_ID,RECENTS_ID,TAGS_ID,CUSTOM_TEMPLATES_ID,RECOVERY_ID,MARKERS_ID]);
export const MAX_PASSWORD_HISTORY=10;
export const MAX_RECENTS=20;
const ID_RE=/^[a-zA-Z0-9_-]{8,80}$/;
export const ATTACHMENT_CATEGORIES=['image','video','other'];
export const ATTACHMENT_LIMITS=Object.freeze({image:10*1024*1024,video:100*1024*1024,other:25*1024*1024});
export const MAX_ATTACHMENT_CIPHERTEXT=ATTACHMENT_LIMITS.video+16;
export const INVITE_CODE_BOUNDS=Object.freeze({min:1,max:256});
const plainObject=x=>!!x&&typeof x==='object'&&!Array.isArray(x);
export function validateUsername(x){if(typeof x!=='string')return{valid:false,value:''};const value=x.trim();if(!value||value.length>80||/[\p{Cc}\p{Cf}]/u.test(value))return{valid:false,value:''};return{valid:true,value}}
export const validInviteCode=x=>typeof x==='string'&&x.length>=INVITE_CODE_BOUNDS.min&&x.length<=INVITE_CODE_BOUNDS.max;
export function validKdf(x){return plainObject(x)&&Object.keys(x).every(k=>['salt','iterations','hash'].includes(k))&&typeof x.salt==='string'&&x.salt.length>0&&x.salt.length<1000&&x.iterations===310000&&(x.hash===undefined||x.hash==='SHA-256')}
export function validWrappedKey(x){return plainObject(x)&&Object.keys(x).length===2&&typeof x.iv==='string'&&x.iv.length>0&&x.iv.length<1000&&typeof x.ciphertext==='string'&&x.ciphertext.length>0&&x.ciphertext.length<10000}
export function validKeyMaterial(x){return plainObject(x)&&validKdf(x.kdf)&&validWrappedKey(x.wrappedKey)}
const attachmentIdValid=x=>typeof x==='string'&&/^[a-zA-Z0-9_-]{8,80}$/.test(x);
export function validEnvelope(x){return plainObject(x)&&Object.keys(x).every(k=>['id','type','version','iv','ciphertext'].includes(k))&&(TYPES.includes(x.type)||(x.type==='settings'&&SETTINGS_IDS.includes(x.id)))&&typeof x.id==='string'&&ID_RE.test(x.id)&&typeof x.ciphertext==='string'&&x.ciphertext.length<2_000_000&&typeof x.iv==='string'&&typeof x.version==='number'}
export const legacyVisibleEnvelopes=items=>items.filter(x=>TYPES.includes(x?.type));
export function normalizeGroupRegistry(x){if(!plainObject(x)||Object.keys(x).some(k=>!GROUP_TYPES.includes(k)))return null;const supplied=Object.keys(x);if(!GROUP_TYPES.filter(type=>!['totp','custom'].includes(type)).every(type=>supplied.includes(type))||supplied.some(type=>!GROUP_TYPES.includes(type)))return null;const out={};for(const type of GROUP_TYPES){const rows=x[type]??[];if(!Array.isArray(rows)||rows.length>50)return null;const ids=new Set(),names=new Set();out[type]=[];for(const row of rows){if(!plainObject(row)||Object.keys(row).length!==2||!('id'in row)||!('name'in row)||!ID_RE.test(row.id)||typeof row.name!=='string')return null;const name=row.name.trim();if(!name||name.length>40||/[\p{Cc}\p{Cf}]/u.test(name)||ids.has(row.id)||names.has(name))return null;ids.add(row.id);names.add(name);out[type].push({id:row.id,name})}}return out}
export const TAG_COLORS=Object.freeze(['none','red','orange','yellow','green','blue','purple']);
const validTagName=x=>typeof x==='string'&&!!x.trim()&&[...x].length<=100&&!/[\p{Cc}\p{Cf}]/u.test(x);
export function normalizeTagRegistry(x){const rows=Array.isArray(x)?x.map(name=>({name,color:'none'})):plainObject(x)&&x.version===2&&Object.keys(x).length===2&&Array.isArray(x.tags)?x.tags:null;if(!rows||rows.length>200)return null;const seen=new Set(),out=[];for(const row of rows){if(!plainObject(row)||Object.keys(row).some(k=>!['name','color'].includes(k))||!validTagName(row.name)||!TAG_COLORS.includes(row.color)||seen.has(row.name))return null;seen.add(row.name);out.push({name:row.name,color:row.color})}return{version:2,tags:out}}
export function normalizeCustomTemplateRegistry(x){if(!plainObject(x)||x.version!==1||Object.keys(x).length!==2||!Array.isArray(x.templates)||x.templates.length>50)return null;const ids=new Set(),names=new Set(),templates=[];for(const row of x.templates){if(!plainObject(row)||Object.keys(row).length!==3||!['id','name','fields'].every(k=>k in row)||!ID_RE.test(row.id)||ids.has(row.id)||typeof row.name!=='string')return null;const name=row.name.trim();if(!name||name.length>80||/[\p{Cc}\p{Cf}]/u.test(name)||names.has(name)||!Array.isArray(row.fields)||row.fields.length>20)return null;const fields=[];for(const [index,field] of row.fields.entries()){if(!plainObject(field)||Object.keys(field).some(k=>!['label','type','condition'].includes(k))||!['label','type'].every(k=>k in field)||typeof field.label!=='string')return null;const label=field.label.trim();if(!label||label.length>80||/[\p{Cc}\p{Cf}]/u.test(label)||!CUSTOM_RECORD_FIELD_TYPES.includes(field.type))return null;let condition;if('condition'in field){const c=field.condition;if(!plainObject(c)||Object.keys(c).length!==3||!['fieldIndex','operator','value'].every(k=>k in c)||!Number.isSafeInteger(c.fieldIndex)||c.fieldIndex<0||c.fieldIndex>=index||c.operator!=='equals'||!boundedString(c.value,1000))return null;condition={fieldIndex:c.fieldIndex,operator:'equals',value:c.value}}fields.push({label,type:field.type,...(condition?{condition}:{})})}ids.add(row.id);names.add(name);templates.push({id:row.id,name,fields})}return{version:1,templates}}
const boundedString=(x,max)=>typeof x==='string'&&x.length<=max;
const validCredentials=x=>Array.isArray(x)&&x.length>=1&&x.length<=20&&x.every((row,index)=>plainObject(row)&&Object.keys(row).length===2&&Object.keys(row).every(k=>['username','password'].includes(k))&&boundedString(row.username,256)&&boundedString(row.password,4096)&&((row.username.length>0&&row.password.length>0)||(x.length===1&&index===0&&row.username.length===0&&row.password.length===0)));
export function normalizePlain(type,x){if(type!=='account'||!plainObject(x))return x;if(Array.isArray(x.credentials))return x;if(typeof x.username!=='string'||typeof x.password!=='string')return x;const {username,password,...rest}=x;return{...rest,credentials:[{username,password}]}}
const validTimestamp=x=>Number.isSafeInteger(x)&&x>=0&&x<=8640000000000000;
const validDeletedAt=x=>validTimestamp(x)&&x>0;
function validPasswordHistory(x){return Array.isArray(x)&&x.length<=MAX_PASSWORD_HISTORY&&x.every(row=>plainObject(row)&&Object.keys(row).length===3&&['username','password','changedAt'].every(k=>k in row)&&boundedString(row.username,256)&&boundedString(row.password,4096)&&validTimestamp(row.changedAt))}
export function normalizeRecents(x){if(!Array.isArray(x))return null;for(const row of x){if(!plainObject(row)||Object.keys(row).length!==3||!['type','id','at'].every(k=>k in row)||!GROUP_TYPES.includes(row.type)||!ID_RE.test(row.id)||!validTimestamp(row.at))return null}const sorted=[...x].sort((a,b)=>b.at-a.at),seen=new Set(),out=[];for(const row of sorted){const key=row.type+':'+row.id;if(seen.has(key))continue;seen.add(key);out.push({type:row.type,id:row.id,at:row.at})}return out.slice(0,MAX_RECENTS)}
const validTags=x=>Array.isArray(x)&&x.length<=20&&x.every(tag=>boundedString(tag,100)&&tag.trim().length>0&&!/[\p{Cc}\p{Cf}]/u.test(tag));
export const CUSTOM_FIELD_TYPES=Object.freeze(['text','secret','url','date','textarea']);
export const CUSTOM_RECORD_FIELD_TYPES=Object.freeze([...CUSTOM_FIELD_TYPES,'number']);
export const CUSTOM_RECORD_TEMPLATES=Object.freeze(['blank','bank-card','identity','api','server','software-license']);
const validFieldRows=(x,types)=>{if(!Array.isArray(x)||x.length>20)return false;const ids=new Set();return x.every(row=>{if(!plainObject(row)||Object.keys(row).some(k=>!['id','label','type','value','condition'].includes(k))||!['id','label','type','value'].every(k=>k in row)||ID_RE.test(row.id)===false||ids.has(row.id)||!boundedString(row.label,80)||!row.label.trim()||/[\p{Cc}\p{Cf}]/u.test(row.label)||!types.includes(row.type)||!boundedString(row.value,10000))return false;if('condition'in row){const c=row.condition;if(!plainObject(c)||Object.keys(c).length!==3||!['fieldId','operator','value'].every(k=>k in c)||!ids.has(c.fieldId)||c.operator!=='equals'||!boundedString(c.value,1000))return false}ids.add(row.id);return true})};
const validCustomFields=x=>validFieldRows(x,CUSTOM_FIELD_TYPES);
const customFieldsValid=x=>!('customFields'in x)||validCustomFields(x.customFields);
const optionalStateValid=x=>('groupId'in x&&!ID_RE.test(x.groupId))||('favorite'in x&&typeof x.favorite!=='boolean')||('pinned'in x&&typeof x.pinned!=='boolean')||('pinRank'in x&&(!Number.isSafeInteger(x.pinRank)||x.pinRank<0||x.pinRank>1000000||x.pinned!==true))||('deletedAt'in x&&!validDeletedAt(x.deletedAt));
export function validatePlain(type,x){if(!plainObject(x)||optionalStateValid(x)||(type!=='custom'&&!customFieldsValid(x)))return false;if(type==='custom'){const keys=['title','template','notes','tags','fields','groupId','favorite','pinned','pinRank','deletedAt'];return !Object.keys(x).some(k=>!keys.includes(k))&&['title','template','notes','tags','fields'].every(k=>k in x)&&boundedString(x.title,256)&&x.title.trim().length>0&&CUSTOM_RECORD_TEMPLATES.includes(x.template)&&boundedString(x.notes,10000)&&validTags(x.tags)&&validFieldRows(x.fields,CUSTOM_RECORD_FIELD_TYPES)}if(type==='totp'){const keys=['account','secret','tags','customFields','groupId','favorite','pinned','pinRank','deletedAt'],remainder=typeof x.secret==='string'?x.secret.length%8:-1,leftover=typeof x.secret==='string'?(x.secret.length*5)%8:0,last=typeof x.secret==='string'?'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(x.secret.at(-1)):-1;return !Object.keys(x).some(k=>!keys.includes(k))&&['account','secret','tags'].every(k=>k in x)&&boundedString(x.account,256)&&x.account.trim().length>0&&typeof x.secret==='string'&&/^[A-Z2-7]{16,256}$/.test(x.secret)&&![1,3,6].includes(remainder)&&(!leftover||!(last&((1<<leftover)-1)))&&validTags(x.tags)}if(type==='account'){const legacy='username'in x||'password'in x,keys=legacy?['platform','loginUrl','username','password','notes','tags','customFields','groupId','favorite','pinned','pinRank','deletedAt']:['platform','loginUrl','credentials','notes','tags','customFields','groupId','favorite','pinned','pinRank','updatedAt','passwordHistory','deletedAt'];if(Object.keys(x).some(k=>!keys.includes(k))||keys.filter(k=>!['groupId','favorite','pinned','pinRank','updatedAt','passwordHistory','customFields','deletedAt'].includes(k)).some(k=>!(k in x))||!validTags(x.tags))return false;if('updatedAt'in x&&!validTimestamp(x.updatedAt))return false;if('passwordHistory'in x&&!validPasswordHistory(x.passwordHistory))return false;return boundedString(x.platform,256)&&boundedString(x.loginUrl,2048)&&boundedString(x.notes,10000)&&(legacy?(typeof x.username==='string'&&typeof x.password==='string'&&boundedString(x.username,256)&&boundedString(x.password,4096)):validCredentials(x.credentials))}const keys={website:['name','url','description','tags','customFields','groupId','favorite','pinned','pinRank','deletedAt'],note:['title','body','tags','customFields','attachmentIds','groupId','favorite','pinned','pinRank','deletedAt']}[type];if(!keys||Object.keys(x).some(k=>!keys.includes(k)))return false;return keys.filter(k=>!['customFields','attachmentIds','groupId','favorite','pinned','pinRank','deletedAt'].includes(k)).every(k=>k in x)&&validTags(x.tags)&&(type!=='note'||(x.attachmentIds===undefined||(Array.isArray(x.attachmentIds)&&x.attachmentIds.length<=20&&x.attachmentIds.every(attachmentIdValid))))}
export const validAttachmentId=x=>typeof x==='string'&&/^[a-zA-Z0-9_-]{8,80}$/.test(x);
export function attachmentAad(id){if(!validAttachmentId(id))throw new TypeError('invalid_attachment_id');return new TextEncoder().encode(`pass-vault-v2:attachment:1:${id}`)}
export function validateAttachmentMetadata(x){if(!plainObject(x)||Object.keys(x).some(k=>!['name','mime','size','category','noteId','contentIv','tags','groupId','favorite','pinned','pinRank','deletedAt','trashOwnerId'].includes(k))||(x.tags!==undefined&&(!Array.isArray(x.tags)||x.tags.length>20||x.tags.some(tag=>!boundedString(tag,100)||!tag.trim()||/[\p{Cc}\p{Cf}]/u.test(tag))))||('favorite'in x&&typeof x.favorite!=='boolean')||('pinned'in x&&typeof x.pinned!=='boolean')||('pinRank'in x&&(!Number.isSafeInteger(x.pinRank)||x.pinRank<0||x.pinRank>1000000||x.pinned!==true))||('deletedAt'in x&&!validDeletedAt(x.deletedAt))||('trashOwnerId'in x&&(!ID_RE.test(x.trashOwnerId)||!('deletedAt'in x))))return false;return typeof x.name==='string'&&x.name.length>0&&x.name.length<=255&&!/[\p{Cc}\p{Cf}]/u.test(x.name)&&typeof x.mime==='string'&&x.mime.length<=255&&Number.isSafeInteger(x.size)&&x.size>=0&&ATTACHMENT_CATEGORIES.includes(x.category)&&x.size<=ATTACHMENT_LIMITS[x.category]&&(x.noteId===undefined||(validAttachmentId(x.noteId)&&x.category==='image'))&&(x.groupId===undefined||ID_RE.test(x.groupId))&&typeof x.contentIv==='string'&&/^[A-Za-z0-9+/]{16}$/.test(x.contentIv)}
export function validAttachmentEnvelope(x){return plainObject(x)&&Object.keys(x).length===3&&x.version===1&&typeof x.iv==='string'&&x.iv.length>0&&x.iv.length<1000&&typeof x.ciphertext==='string'&&x.ciphertext.length>0&&x.ciphertext.length<2_000_000}
export function validAttachmentRecord(x){return plainObject(x)&&Object.keys(x).every(k=>['id','metadata','ciphertextSize','createdAt','updatedAt'].includes(k))&&validAttachmentId(x.id)&&validAttachmentEnvelope(x.metadata)&&Number.isSafeInteger(x.ciphertextSize)&&x.ciphertextSize>=16&&x.ciphertextSize<=MAX_ATTACHMENT_CIPHERTEXT}